### ISSUE TITLE
Why many methods are not implemented in TorrentStatus?

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#100]
Hello. Recently it took me implement in my application displaying active and seeding time. But I found them only in swig `torrent_status` class. In `TorrentStatus` I found only commented-out list with isn't implemented methods:
```
//    public final int uploadsLimit;
//    public final int connectionsLimit;
//    public final int upBandwidthQueue;
//    public final int downBandwidthQueue;
//    public final int timeSinceUpload;
//    public final int timeSinceDownload;
//    public final int activeTime;
//    public final int finishedTime;
//    public final int seedingTime;
//    public final int seedRank;
//    public final int lastScrape;
//    public final int sparseRegions;
//    public final int priority;
```
Why they haven't been implemented? Maybe it's a technical reason?

**Comment by aldenml** [comment]
No technical reason, just lack of time. List the fields you need to code it in the next release (should be soon).

**Comment by proninyaroslav** [comment]
With your permission, I can make patch with the changes.

**Comment by aldenml** [comment]
Go ahead, PRs are always welcome

**Comment by aldenml** [comment]
1.1.0.36 is out in maven
