### ISSUE TITLE
How to enable/disable PeX in jlibtorrent?

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#104]
I'm a long time reading jlibtorrent's javadoc, but don't quite understand how realized PeX support and how to manage it's state (enable and disable). As far as I know, in libtorrent is realized by adding an extension, but I didn't find in jlibtorrent such possibility.
I would be grateful for any answer.

**Comment by aldenml** [comment]
The pex plugin is added when passed `add_default_plugins` to the `session` constructor in libtorrent. That flag is set by default and we don't change it, so it's added (and enabled) by default. If you want more control, to disable it for example, you need to go to the `swig.session` class and work with it.

**Comment by proninyaroslav** [comment]
Thanks for the answer!
