### ISSUE TITLE
1 session contains 1 handle.  It's bad style in terms of performance?

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#105]
Hello. I have a question to you, as a more experienced developers of this lib: 
I have a lot of torrents in memory (no more 100), each located in a separate thread, and each has its own session. Respectively in each session 1 handle, that supports a single torrent. I did this in order to simplify code, but now I understand that maybe it's not the best way. What can you say on this score?
Thanks in advance! :^)

**Comment by gubatron** [comment]
yes, this is not the best way. You only need ONE session, and then you can add thousands of torrents to that session, if the torrents are flagged as auto managed then the session will take into account your settings for bandwidth, speed, connections, etc. and manage all the different torrents for you.

All you need is one session.

Cheers!
