### ISSUE TITLE
JLibtorrent and Android Storage Access Framework

### ISSUE THREAD

**Issue by xarrange** [frostwire/frostwire-jlibtorrent#110]
Hi

Is it at least in ToDo list?

**Comment by aldenml** [comment]
A direct solution to the SAF problem is not in the scope of jlibtorrent, but the good news is that we provide a "posix layer wrapper" that you can install and customize to your needs (only in android). It was created for that problem specifically.  Take a look at https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/AndroidPlatform.java#L127

**Comment by mianharisali** [comment]
I was facing same problem , @xarrange can you post your code if you solve it using @aldenml solution.

**Comment by mianharisali** [comment]
i think this might help.
http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop
