### ISSUE TITLE
For a file larger that 2GB pieces at the end are not downloaded.

### ISSUE THREAD

**Issue by bogdanSumyUa** [frostwire/frostwire-jlibtorrent#112]
I use jlibtorrent-android-arm 1.1.1.40 
When I try to download a file which is more than 2GB pieces at the end are not downloaded at all. 
When I try to download only some number of end pieces(using piece priority) an alert listener is spammed by alerts:
Type: FILE_ERROR
What: file_error_alert
Message: torrent_name write (/storage/emulated/0/torrents/file.mp4) error: Invalid argument
Category: 73
Timestamp: -40

sometimes instead of "write" in the alert's message "open" appears.

The same alert also appears randomly every 30sec - 1 minute for pieces that are not in the end. This causes libtorrent to drop all peers and speed.

Could you please help me to fix this issue?

Note: download location of the torrent is on device's sdcard.

**Comment by aldenml** [comment]
Thanks for the report, I will test this

**Comment by gubatron** [comment]
what file system do you have on that sdcard?
does it (the filesystem) support 2GB files?

**Comment by bogdanSumyUa** [comment]
I've found that sdcard is emulated and internal storage is used. Sdcard uses tmpfs and device uses ext4. I've successfully copied a 2.2GB file on the device. Also I tried to download the torrent using a torrent client(Flud) and it was ok.

**Comment by gubatron** [comment]
excellent, we can discard that being the issue now :)

**Comment by bogdanSumyUa** [comment]
Hi guys. I've created a demo app https://github.com/bogdanSumyUa/LibtorrentTest using which you can try to reproduce the issue.
When DOWNLOAD_FROM = 1040 and DOWNLOAD_TO = 1049 pieces from this interval are not downloaded at all and I see a lot of file_error and torrent_error alerts.
However when DOWNLOAD_FROM = 540 and DOWNLOAD_TO = 549 pieces from this interval are downloading but sometimes I still can see file_error and torrent_error alerts.

**Comment by aldenml** [comment]
Thanks! I can't give you an ETA, but I will look at it soon

**Comment by aldenml** [comment]
Well, I have the feeling that this has to do with the "posix wrap" I do for android. I didn't consider the `stat64` posix call and it could be a problem. I'm testing with a solution in master, and if it works, I strongly recommend you to switch to it. But still I did fully test, this is just an update.

**Comment by bogdanSumyUa** [comment]
Cool, thank you.

**Comment by aldenml** [comment]
Hi @bogdanSumyUa , can you test with `1.2.0.1`? the `1.1.x.x` is in the process of being phased out

**Comment by bogdanSumyUa** [comment]
Hi @aldenml , sure. I'll update my demo app to use 1.2.0.1.

**Comment by bogdanSumyUa** [comment]
I've updated my demo app to use 1.2.0.1. Looks like the issue is gone. But with it I have an issue that TorrentStatus.swig().getPieces() returns a bitfield with all 0 bits and it's impossible to know what pieces have been downloaded. Shold I file another issue for this?

**Comment by aldenml** [comment]
Very good and yes, I will close this one and you open another one for the `getPieces` issue. Thanks
