### ISSUE TITLE
Download file size is large than real size

### ISSUE THREAD

**Issue by alicemmm** [frostwire/frostwire-jlibtorrent#114]
I want to know the real file size and downloading file size.
for example:
                    downloadSize = torrentHandle.status().totalWantedDone();
but It's update so slowly.

How can I get the real file downloaded size not total downloaded size?

**Comment by aldenml** [comment]
There is a `TorrentHandle#status(boolean force)` to force the update.
For the real file size, you have the torrent info, and for the real file downloaded size, take a look at `TorrentHandle#getFileProgress`

**Comment by alicemmm** [comment]
Thanks a lot !,I get the real torrent file size via TorrentHandle#getFileProgress,but if pause then resume TorrentHandle#getFileProgress get a smaller size than before

**Comment by aldenml** [comment]
strange, I will take a look at it

**Comment by aldenml** [comment]
Did you tested using `FileProgressFlags#PIECE_GRANULARITY`?

**Comment by aldenml** [comment]
Closing this, too old, open if necessary with more information.
