### ISSUE TITLE
SettingsPack activeDownloads is useless

### ISSUE THREAD

**Issue by alicemmm** [frostwire/frostwire-jlibtorrent#115]
When use SettingsPack.activeDownloads(4) method .I can download more than 4 download tasks in queue. It's unused.

**Comment by aldenml** [comment]
You need to call `SessionHandle#applySettings`. Do you?

**Comment by alicemmm** [comment]
Yes of cause.show my code

SettingsPack sp = settings();
sp.broadcastLSD(true);
sp.enableDht(false);
int maxQueuedDiskBytes = sp.maxQueuedDiskBytes();
sp.maxQueuedDiskBytes(maxQueuedDiskBytes / 2);
 int sendBufferWatermark = sp.sendBufferWatermark();
sp.sendBufferWatermark(sendBufferWatermark / 2);
sp.cacheSize(256);
sp.activeDownloads(4);
sp.activeSeeds(4);
sp.maxPeerlistSize(200);
sp.tickInterval(1000);
 sp.inactivityTimeout(60);
sp.seedingOutgoingConnections(false);
sp.connectionsLimit(200);
sp.downloadRateLimit(Settings.getDownloadRateLimit());
sp.uploadRateLimit(Settings.getUploadRateLimit());

sessionManager.applySettings(sp);

It should be download only four download tasks ,but I can download more above it.
I print the log of setting activeDownloads() is 4.

**Comment by aldenml** [comment]
it works pretty well for us, you need to be sure your torrents are marked as "auto managed"

**Comment by gubatron** [comment]
question: are you serializing your settings to a file?
If you're not actually constructing your Settings object like in the code above, you might be hurting yourself by doing stuff like this:

`sp.maxQueuedDiskBytes(maxQueuedDiskBytes / 2);`

**Comment by alicemmm** [comment]
great ! I don't set auto manage in resume and pause. now It's ok ,thanks a lot.
