### ISSUE TITLE
TorrentStatus.swig().getPieces() returns a bitfield with all zeros.

### ISSUE THREAD

**Issue by bogdanSumyUa** [frostwire/frostwire-jlibtorrent#118]
TorrentStatus.swig().getPieces() returns a bitfield with all 0 bits. However TorrentHandle.havePiece(int i) works fine. Tested on Android using com.frostwire:jlibtorrent:1.2.0.1 and com.frostwire:jlibtorrent-android-arm:1.2.0.1.

**Comment by aldenml** [comment]
To be fixed on `1.2.0.2` with https://github.com/frostwire/frostwire-jlibtorrent/commit/9cbd6dc92bd9f36dce9595843cb86a8d9d89737c

In the meantime you can call directly the status to the swig object with the right flags.

**Comment by aldenml** [comment]
@bogdanSumyUa test `1.2.0.2` and let us know. Thanks

**Comment by bogdanSumyUa** [comment]
The issue is not reproducible usingTorrentHandle.StatusFlags.QUERY_PIECES.swig() flag in a call to TorrentHandle.status().

**Comment by mianharisali** [comment]
@aldenml issue is still there , its empty in 1.2.0.2

**Comment by aldenml** [comment]
Hi @mianharisali, are you using `TorrentHandle.StatusFlags.QUERY_PIECES.swig()` in the new `TorrentHandle#status(long flags)`?

**Comment by mianharisali** [comment]
@aldenml its working with that flag.
but without that flag it is not working.

**Comment by aldenml** [comment]
Good, that's the expected behavior. Filling that field is an expensive operation, it's only done on explicit request. Check out the `libtorrent` documentation too.
