### ISSUE TITLE
Protocol problem

### ISSUE THREAD

**Issue by xiongke15117937934** [frostwire/frostwire-jlibtorrent#119]
Ask, why not support HTTPS？

**Comment by aldenml** [comment]
Because that's a not very used feature (Torrents over SSL) that requieres a lot of software infrastructure.

**Comment by xiongke15117937934** [comment]
But I need to download the seed through the HTTPS request, what should I do? (it's better to use the latest version, I know that the 1.1.4 version can be, but the latest version will not be upgraded.

**Comment by aldenml** [comment]
Could you explain a little more? what exactly is "download the seed through the HTTPS request"?

**Comment by gubatron** [comment]
If you need to make an `https://` URL request to download a `.torrent` file you can use the JRE's http client, or Apache components.

**Comment by aldenml** [comment]
What do you have in your server? the torrent? or a web seed?

**Comment by xiongke15117937934** [comment]
Is a seed

**Comment by aldenml** [comment]
if you don't use the torrent over ssl feature, why don't switch the web seed to regular HTTPS? it will save you bandwidth and CPU, the integrity of the data is guarantee by the info-hash.

**Comment by xiongke15117937934** [comment]
Very grateful, I can only use the 1.1.04 version of the jlibtorrent, the intention to update the jlibtorrent to 1.2.0.1.

**Comment by xiongke15117937934** [comment]
If you are using the latest version of the library that you can not use the HTTPS, the latest version of the library and jlibtorrent 1.1.04, what is the difference?

**Comment by aldenml** [comment]
The difference is that in libtorrent master now it's possible to drop the `ssl` integration and still keep the `libcrypto` for the fast SHA1, that's all we need
