### ISSUE TITLE
Magnet-links

### ISSUE THREAD

**Issue by Lamp-Post** [frostwire/frostwire-jlibtorrent#12]
Magnet links are not working anymore, problem seems to be in: "torrent_handle th = s.getSwig().find_torrent(info_hash)" in Downloader.java

**Comment by artouiros** [comment]
i'm tryign to use dht.waitNodes(). but it seems there is such method in jlibtorrent. somethign changed?

**Comment by aldenml** [comment]
That method was a bad API. We should provide an asynchronous one, also the name was misleading.

**Comment by artouiros** [comment]
and how I should really use magent download? I don't really like Thread.sleep(5000) in the example code. It's terrible.

**Comment by aldenml** [comment]
The current example is a really bad one. I will reopen this issue and work on it.

**Comment by aldenml** [comment]
@artouiros Take a look at this new demo: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/test/java/com/frostwire/jlibtorrent/demo/GetMagnet.java

You can recreate it with the current version, but better wait for the next version.
