### ISSUE TITLE
The latest version of the library, HTTPS configuration?

### ISSUE THREAD

**Issue by xiongke15117937934** [frostwire/frostwire-jlibtorrent#122]
According to the way you say, can only produce the latest version of the jar, but there is no so library jar package, how to do? Https://github.com/frostwire/frostwire-jlibtorrent/issues/121

**Comment by aldenml** [comment]
You need to read the `README.md` file to know how to produce the binaries, after that, if you look at the script `swig/get-binaries.sh` you will know where to place them, then you run `gradle jar` and that's it.

I recognize that the documentation is very lacking in how to produce and distribute a version, but that takes time and it's not in our priority list. I appreciate if next time you come here with some steps you already did and some errors that prevent you going further.

**Comment by xiongke15117937934** [comment]
thank you very munch
