### ISSUE TITLE
Can you help me solve the problem of a build? Is to build your library, the problems encountered

### ISSUE THREAD

**Issue by xiongke15117937934** [frostwire/frostwire-jlibtorrent#123]
https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174166348

**Comment by aldenml** [comment]
The error you are getting is in the deploy stage, copying the travis produced binaries to the S3 bucket. Review your configuration and credentials in S3 and make sure you are following the instructions step by step in `README.md`.

I recommend you reading more about travis and S3 deploy here: https://docs.travis-ci.com/user/deployment/s3/

I see you changed a line to `provider: releases`, not sure if that's correct.

And you need to put `result += <ssl>on ;` (no just remove the line)

btw, I recommend you start with a successful build with the minimal changes (or none at all) and then add your customizations little by little.
