### ISSUE TITLE
I want to know the latest version of the library, how to configure HTTPS protocol?

### ISSUE THREAD

**Issue by xiongke15117937934** [frostwire/frostwire-jlibtorrent#124]
Now build is successful, configure the HTTPS protocol or fail, I want to know how to configure?

**Comment by xiongke15117937934** [comment]
Hope to be able to say specific point

**Comment by xiongke15117937934** [comment]
I build links attached. https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174419158

**Comment by aldenml** [comment]
now we are talking :)

Well, I think the problem now is the way I configure the compilation of openssl, if you look at the `.travis.xml` (https://github.com/frostwire/frostwire-jlibtorrent/blob/master/.travis.yml#L115) I remove a lot of features, try to remove that and let me know what happens

**Comment by xiongke15117937934** [comment]
What I use is and you the same configuration, specific how should be I configuration, can open the HTTPS requests?Now this is the problem that gives me a headache, because I only read your configuration file.

**Comment by xiongke15117937934** [comment]
https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174663772
https://github.com/xiongke15117937934/frostwire-jlibtorrent/blob/master/.travis.yml
This is the result of the I deleted after, what to do next?

**Comment by xiongke15117937934** [comment]
这个是删除其中带SSL的选项最后结果，不知道这样可行不？
https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174662246

**Comment by xiongke15117937934** [comment]
This is to remove the option with SSL final results, don't know this is feasible?
https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174662246

**Comment by aldenml** [comment]
Let me take a deep look at it to see what's happening

**Comment by xiongke15117937934** [comment]
This is wrong link: https://travis-ci.org/xiongke15117937934/frostwire-jlibtorrent/builds/174699352

**Comment by aldenml** [comment]
Apparently there is a problem in the build of openssl, I will take a look at it soon

**Comment by xiongke15117937934** [comment]
Yes, I want to be able to solve it.

**Comment by xiongke15117937934** [comment]
If only the OpenSSL build has a problem, hope you can send me the correct configuration of the building code.

**Comment by xiongke15117937934** [comment]
Ask, control switch is in jlibtorrent HTTPS code, rather than in libtorrent is?

**Comment by aldenml** [comment]
Ok, the build is fine with this commit https://github.com/aldenml/frostwire-jlibtorrent/commit/44c06a9c7482c38a25c8db117df186e12c2d441c

the critical point for arm is the addition of `-fno-integrated-as`

I don't understand your last question btw

**Comment by xiongke15117937934** [comment]
I feel the OpenSSL configuration or have a question, you said I am testing my application the download speed is very slow, can you help me?

**Comment by xiongke15117937934** [comment]
Thank you very much, in accordance with your other way is a success, and can be downloaded, but I wonder is there a better openSSL configuration?

**Comment by aldenml** [comment]
Good
