### ISSUE TITLE
Trackers List is Empty if torrent is added using magnet uri.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#128]
i am trying to get trackers , but when we add torrent using magnet uri , the trackers list comes empty.

**Comment by aldenml** [comment]
I will test this

**Comment by aldenml** [comment]
If you try this code, aren't you able to get the trackers?
```java
add_torrent_params p = add_torrent_params.create_instance_disabled_storage();
error_code ec = new error_code();
libtorrent.parse_magnet_uri(uri, p, ec);
```

**Comment by mianharisali** [comment]
i will try this code , 
but the torrent is being downloaded(added via magnet) in a session i think it should give tracker list using th.trackers();

**Comment by mianharisali** [comment]
th.trackers(); is working perfect on 1.1.1.40

**Comment by aldenml** [comment]
I tested the feature and I can confirm that `TorrentHandle#trackers()` works as expected. I will close the issue but if you put some code to reproduce the problem, I can take a look at it.

**Comment by mianharisali** [comment]
@aldenml just a noob question , can this be due to trackerless torrent?

**Comment by aldenml** [comment]
has the magnet link tracker parameters (`&tr=<url>`)? I think trackless torrent is just a way to say that the peers are discovered only via DHT (and they don't have a list of trackers to discover the swarm).
