### ISSUE TITLE
Crawling the DHT with jlibtorrent.

### ISSUE THREAD

**Issue by dessalines** [frostwire/frostwire-jlibtorrent#129]
I know that the DHT can get me a list of peers from my torrents' infohashes, but is there a way to basically get a list of infohashes that my DHT peers are announcing? Is it maybe the `DHTAnnounceAlert`? 

Then possibly, add the info-hashes in a no-download state to get the name, seeders, leechers, etc?

**Comment by aldenml** [comment]
Not sure what exactly do you want. Don't you know/control the info hashes that are loaded in the sessions? or are your peers special? Do you want to load a torrent in a no-download state in a peer different from the one is announced?

**Comment by dessalines** [comment]
My goal is a DHT crawler, basically I want to get info/metadata on all the torrents my peers are announcing, stuff like torrent name, infohash, seeders/leechers, without actually downloading what my peers are announcing. 

My problem is that I don't know if there is a way to pick up this information. I know that I can call dht.getPeers on torrents that I've already loaded, but I don't know if there's a way to pick up info_hashes from torrents that aren't currently in my session. I'm wondering if `DHTAnnounceAlert`, or maybe one of the other DHT alerts will pick up info_hashes that I don't yet have in my session.

> Do you want to load a torrent in a no-download state in a peer different from the one is announced?

I think its necessary to do this, IE, add them in a no-download state in order to get extra info like the torrent name and leechers/seeders, but I'm not totally sure.

**Comment by aldenml** [comment]
I think there is no way you can listen to DHT announces of other peers in a generic way, maybe you can resort to some hacking with the plugins (and probably require some custom C++ compilation) to listen to specific clients.

You can add an info hash in a non-download state, but without active download/activity, I'm not sure how the stats are filled. I think you should ask these in the libtorrent mailing list.

**Comment by dessalines** [comment]
Ah, I think I understand. I will only receive DHT alerts if I already have that torrent in my session. I'll do this, thanks.

**Comment by dessalines** [comment]
Ah, for some reason I assumed DHT crawlers were possible, sites like [btdigg](https://en.wikipedia.org/wiki/BTDigg) seem to do it somehow.

**Comment by gubatron** [comment]
the only way I can think of is what @aldenml mentioned.

Here's a pseudo algo for a best effort approach, you're not really creating a crawler, but a catching net:

1. listen to every dht_announce alert.
2. fetch that infohash if you haven't already
3. connect to every peer on that swarm and ask for their peers to repeat cycle

it's very much a passive catching net, it only crawls network nodes, but it only listens to announced content.

**Comment by dessalines** [comment]
@gubatron @aldenml I've added a lot of highly seeded torrents, but I'm not getting any `DHT_ANNOUNCE_ALERT`s, even when there a lot of DHT peers on that torrent. Have you guys ever seen an announce alert come through?

I get plenty of `DHT_REPLY_ALERT`s though.

**Comment by aldenml** [comment]
Are you talking about `DhtAnnounceAlert` alerts generated by your own node?

**Comment by dessalines** [comment]
I was under the impression its when other nodes do the announcing: http://libtorrent.org/reference-Alerts.html#dht_announce_alert

I've been running for a while and haven't gotten one of them yet, so I'm not sure if its deprecated or just not used anymore. I think maybe `DHT_GET_PEER` alert might be the one I'm looking for to create a DHT crawler, I do see those coming in, and they are different info_hashes than the ones I currently have.

**Comment by aldenml** [comment]
I thought this was clarified above, `DhtAnnounceAlert` is local and you need to have local torrents announcing to the DHT. I don't see how `DHT_GET_PEER` can help you in a DHT crawler, because I suppose you care more about info-hashes than peer ids, but anyway, not in the scope of this ticket :)

**Comment by dessalines** [comment]
Ah, I didn't realize peer ids were also sha1 info_hashes.
