### ISSUE TITLE
New behavior of activeDuration() and seedingDuration()

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#130]
Before replacing `activeTime()` and `seedingTime()` to `activeDuration()` and `seedingDuration()`, time was total, regardless of stopping torrent, but now if I use this function I get a new time, relativity for new session rather than total time. Whether new behavior normal? is it possible to realize old behavior?

**Comment by aldenml** [comment]
I need to look at it...(we do track the latest API changes)

**Comment by aldenml** [comment]
I looked at the code, and it all seems to be the same, only that now, the time (in java) is in milliseconds.

**Comment by proninyaroslav** [comment]
Yes, but active and seeding time is not saved in resume file. Before I didn't observe this behavior.

**Comment by aldenml** [comment]
can you post a resume file that does not have these fields?

**Comment by proninyaroslav** [comment]
field is available, but for some reason after shutdown and start session every time I get a new value (old reset).

**Comment by aldenml** [comment]
hmm...hard to say...it could be a problem with the logic loading the resume data. Are you using `SessionManager`?

**Comment by proninyaroslav** [comment]
Yes.

**Comment by aldenml** [comment]
Hi @proninyaroslav, some fixes were made in `libtorrent` related to this counters. I added a test https://github.com/frostwire/frostwire-jlibtorrent/commit/7906f8bb68c4877de2b5c9e33f08136ba6c9660f and I can't replicate the issue.

Feel free to reopen if you can provide a more concrete example or tweak the unit test to make it fail.

**Comment by proninyaroslav** [comment]
Hi. it's been a long time but I'm still getting this problem. `activeDuration()` and `seedingDuration()` reset their values after stopping the session. I use a `resume` file, but for some reason the values of active and seeding time are not restored from it, although a year ago it worked perfectly.

I wrote a test program to reproduce this problem and exclude this problem in my app:
```Java
public class Main {
    public static void main(String[] args) throws Throwable {
        File torrentFile = new File("path_to_torrent");

        final SessionManager s = new SessionManager();
        final CountDownLatch signal = new CountDownLatch(10);
        s.addListener(new AlertListener() {
            @Override
            public int[] types() {
                return null;
            }

            @Override
            public void alert(Alert<?> alert) {
                AlertType type = alert.type();

                switch (type) {
                    case ADD_TORRENT:
                        System.out.println("Torrent added");
                        ((AddTorrentAlert) alert).handle().resume();
                        break;
                    case TORRENT_FINISHED:
                        System.out.println("Torrent finished");
                        ((TorrentFinishedAlert) alert).handle().saveResumeData(TorrentHandle.SAVE_INFO_DICT);
                        break;
                    case SAVE_RESUME_DATA:
                        serializeResumeData((SaveResumeDataAlert) alert);
                        break;
                    case STATS:
                        TorrentHandle th = ((StatsAlert) alert).handle();
                        if (th.status().isFinished()) {
                            TorrentStatus ts = th.status();
                            System.out.println(String.format("seeding time=%d\nactive time=%d\n",
                                                             ts.seedingDuration(), ts.activeDuration()));
                            signal.countDown();
                        }
                        break;
                }
            }
        });

        s.start();
        TorrentInfo ti = new TorrentInfo(torrentFile);
        s.download(ti, torrentFile.getParentFile());
        signal.await();
        s.restart();
        s.download(ti, torrentFile.getParentFile(), new File("resume"), null, null);

        System.in.read();
        s.stop();
    }

    private static void serializeResumeData(SaveResumeDataAlert alert)
    {
        File resume = new File("resume");
        if (resume.exists())
            return;
        byte_vector data = add_torrent_params.write_resume_data(alert.params().swig()).bencode();
        try {
            Utils.writeByteArrayToFile(resume, Vectors.byte_vector2bytes(data), false);
        } catch (IOException e) {
            System.err.println("Error saving resume data");
        }
    }
}
```
After finish torrent we save the `resume` file and print active and seeding time for about 10 seconds, then we do restart the session, add the torrent and its `resume` file again and print active and seeding time.

Results:
Torrent added
Torrent finished
seeding time=1000
active time=2000

seeding time=2000
active time=3000

...

seeding time=8000
active time=9000

seeding time=9000
active time=10000

seeding time=10000
active time=11000

Torrent added
Torrent finished
seeding time=1000
active time=3000

seeding time=2000
active time=4000

seeding time=3000
active time=5000

we see that the values were not restored from the `resume` file. I also attach `resume` file to this message.
[resume.zip](https://github.com/frostwire/frostwire-jlibtorrent/files/1603665/resume.zip)

**Comment by aldenml** [comment]
reopening to take a look at it

**Comment by aldenml** [comment]
quick update, this is a very puzzling behavior, I'm able to reproduce it but still looking for the problem

**Comment by aldenml** [comment]
I can't find any problem inside `libtorrent`, but I just found the problem in your example, it is that you save the resume data just after it's finished, and not "just" before restarting the session. You end up with a stale resume data.

See https://github.com/frostwire/frostwire-jlibtorrent/commit/fdbd0495a3de52c70be789ce86378164b54aef13

I will close this but feel free to reopen if you can provide another example with the issue.
