### ISSUE TITLE
Corrupt torrent file generated intermittently on Mac OSX

### ISSUE THREAD

**Issue by tjo** [frostwire/frostwire-jlibtorrent#131]
When generating a torrent file on Mac OSX, the tracker URL gets intermittently corrupted resulting in invalid torrent file. Tested with builds 12.2.0.2 and 12.2.0.4. Build 1.1.1.40 works fine.

**Comment by aldenml** [comment]
it may be related to the new use of `string_view`, can you post a piece of code that we can use to reproduce the crash?

**Comment by tjo** [comment]
Very simple torrent file generation:

```
import com.frostwire.jlibtorrent.Entry;
import com.frostwire.jlibtorrent.TorrentBuilder;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

public class CreateTorrent {

  public static void main(String[] args) throws Exception {
    TorrentBuilder torrentBuilder = new TorrentBuilder();
    Entry entry = torrentBuilder.path(new File("/tmp/test.bin"))
        .addTracker("http://127.0.0.1:6881/announce", 0)
        .generate()
        .entry();

    Files.write(Paths.get("/tmp/test.bin.torrent"), entry.bencode());
  }
}
```

[test.bin.torrent.zip](https://github.com/frostwire/frostwire-jlibtorrent/files/611006/test.bin.torrent.zip)

**Comment by aldenml** [comment]
good to know that you are using `TorrentBuilder`, I will take a look at it (but can't give you ETA).

**Comment by aldenml** [comment]
I detected a fundamental problem with `string_view` and the swig code. I'm working on it

**Comment by aldenml** [comment]
`1.2.0.5` is out, give it a try, it should be fixed

**Comment by tjo** [comment]
Verified the 1.2.0.5 version. Issue seems to be resolved. Thanks!
