### ISSUE TITLE
Torrents download with SAF not working

### ISSUE THREAD

**Issue by BillalGene** [frostwire/frostwire-jlibtorrent#132]
Torrents files are not creating on SD Card. We try to set LollypopFileSystem wrapper before session start but it does not work. Please tell us where we are wrong. Sample code is given bellow

 if (Build.VERSION.SDK_INT >= 21) {
                    LollipopFileSystem lollipopFileSystem = new LollipopFileSystem(getApplication());
                    LibTorrent.setPosixWrapper(new PosixCalls(lollipopFileSystem));
                }

**Comment by aldenml** [comment]
Sorry, but android SAF support is out of scope in this project. We do provide minimal support for a "posix layer" in android, but not more. What are you using is from https://github.com/frostwire/frostwire, and that's not prepared for third party use, but I can tell you that torrent creation in SAF does not work at this moment. Coding help is welcome

**Comment by proninyaroslav** [comment]
@aldenml 
Is there a workaround for download torrents on the external storage (with SAF)?

**Comment by aldenml** [comment]
The only workaround we have is the one used in frostwire (using the posix wrapper). The reason we didn't bring the feature here is because that solution still is very experimental.
