### ISSUE TITLE
Tracker scrape problems, getting seeder and leecher counts for torrents.

### ISSUE THREAD

**Issue by dessalines** [frostwire/frostwire-jlibtorrent#133]
Hey, I'm having an issue with tracker scraping. I'm wanting to get seeding/leeching counts from the first successful tracker reply(that's the only way I can think of, since an `ANNOUNCE_REPLY_ALERT` only seems to give `numPeers()`. I call `scrapeTracker()`, on every torrent added to my session, but for some reason, it only scrapes the first 3 or 4 torrents in queue. 

```java
case TORRENT_ADDED:
  TorrentAddedAlert a = (TorrentAddedAlert) alert;
  a.handle().scrapeTracker();
  break;
```

I've also had to add a map from infoHash to tracker number, because if a tracker scrape fails, it doesn't automatically call the next tracker in the list. So I have to increment a counter, and call 
```java
case SCRAPE_FAILED:
  // some logic to get the next tracker in the list
  v.handle().swig().scrape_tracker(count);
  break;
```

I've tried increasing both the `maxActiveDownloads` and `maxActiveSeeds`, and turning the torrents `automanaged` to false after adding, none of which helped.

Also, I've noticed that a tracker scrape will basically never be called, unless I explicitly call it.

Another note, I'm doing this with all torrents paused, as I **just want the seeder/leecher counts** for the torrents in my queue. It still works for paused torrents, but will only scrape the first 3 or 4 torrents in my queue.

**Comment by gubatron** [comment]
> I'm doing this with all torrents paused

tried unpausing them and seeing if `scrapeTracker()` gets called automatically once active?

The idea of pausing is to basically not be part of the swarm and minimize all network activity for that torrent. I believe it behaves like this by design. If a torrent is paused it should always return 0 on all those things, as it's paused.

**Comment by dessalines** [comment]
Cool, I'll try this when I get home later. Are tracker scrapes automatic for resumed torrents? I remember trying this, but not seeing any scrapes for them.

**Comment by dessalines** [comment]
I'll close this out, I've found that tracker scrapes are unreliable for getting peer counts.

Better options are turning out to be:

```java
alert.listSeeds();
alert.listPeers();
alert.numPeers();
alert.numSeeds();
```

`alert.numIncomplete()` and `alert.numComplete()` are the tracker scrape counts, and they are almost always -1, as tracker scrapes seem to never get called, unless explicitly. 

With `listPeers` seeming to be the most reliable.
