### ISSUE TITLE
[tests] TorrentBuilder::generate() might not be calling listener

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#138]
`CreateTorrentTest.java` is failing on line 160.

```
final AtomicBoolean b1 = new AtomicBoolean();
        final AtomicBoolean b2 = new AtomicBoolean();

        TorrentBuilder b = new TorrentBuilder();
        TorrentBuilder.Result r = b.path(dir)
                .listener(new TorrentBuilder.Listener() {
                    @Override
                    public boolean accept(String filename) {
                        b1.set(true);
                        return true;
                    }

                    @Override
                    public void progress(int piece, int total) {
                        b2.set(true);
                    }
                })
                .generate();

        TorrentInfo ti = TorrentInfo.bdecode(r.entry().bencode());
        assertEquals(2, ti.numFiles());
        assertTrue(b1.get()); // line 160 <<<<<<<
        assertTrue(b2.get());
```

That `b1` is an `AtomicBoolean` that's supposed to be set to true when the `TorrentBuilder.Listener::accept(String filename)` method is called.

I took a look around `TorrentBuilder::generate()`:

```
public Result generate() throws IOException {
        if (path == null) {
            throw new IOException("path can't be null");
        }

        File absPath = path.getAbsoluteFile();

        file_storage fs = new file_storage();
        add_files_listener l1 = new add_files_listener() {
            @Override
            public boolean pred(String p) {
                return listener != null ? listener.accept(p) : true;
            }
        };
        add_files_ex(fs, absPath.getPath(), l1, flags);
```

So I see that the listener that we set when we did `b.path(dir).listener(...` is not getting invoked, since the `b1.set(true)` never happens.

The code inside `generate()` seems good, by the time that `add_files_listener()` is called `listener` is certainly non `null`.

So either there's something wrong with the test itself that no files are being added and the method `add_files_ex` in libtorrent land doesn't feel like it needs to invoke `pred(p)`, or something broke.

Will keep investigating.

**Comment by gubatron** [comment]
The folder is created fine, the files are created fine, and the .torrent seems to be creating itself fine:

```
d13:creation datei1481863802e4:infod5:filesld6:lengthi2e4:pathl8:test.txteed6:lengthi2e4:pathl9:test1.txteee4:name24:junit267717299617323769412:piece lengthi16384e6:pieces20:�i�x�E
(QsC>R��R��see
```

**Comment by gubatron** [comment]
maybe this change has something to do with this:
https://github.com/frostwire/frostwire-jlibtorrent/commit/671a1e94fe757198b9cbaedbe96412012328fc8d#diff-e328102d0d0a557bd287f8c67b4e5547R1359

**Comment by aldenml** [comment]
bug was confirmed, fixed with https://github.com/frostwire/frostwire-jlibtorrent/commit/00cb0acf18c80d602626032e5c1fe40401267aec
