### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jlibtorrent in java.library.path

### ISSUE THREAD

**Issue by pierrewessman** [frostwire/frostwire-jlibtorrent#14]
Sorry for beeing a noob, but Im having issues getting "System.out.println("Using libtorrent version: " + LibTorrent.version());" run.

I have included everything in src so that all imports looks ok in Eclipse, but I have no idea how to do the build stuff, can I use the provided binaries or do I have to build something myself? It says "The result will be a libjlibtorrent.dylib", and thats provided in the rep. But how do I use it?

This is my code:
```
import java.io.File;
import java.util.concurrent.CountDownLatch;

import com.frostwire.jlibtorrent.LibTorrent;
import com.frostwire.jlibtorrent.Session;
import com.frostwire.jlibtorrent.TorrentAlertAdapter;
import com.frostwire.jlibtorrent.TorrentHandle;
import com.frostwire.jlibtorrent.alerts.BlockFinishedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentFinishedAlert;

public class Main {
	
	public static void main(String[] args) {
        System.out.println("Using libtorrent version: " + LibTorrent.version());
	}

}
```

And this is the complete error message:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jlibtorrent in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:14)
	at com.frostwire.jlibtorrent.swig.libtorrentConstants.<clinit>(libtorrentConstants.java:12)
	at com.frostwire.jlibtorrent.LibTorrent.version(LibTorrent.java:15)
	at Main.main(Main.java:14)

**Comment by aldenml** [comment]
Which OS are you using? Just grab the corresponding library from https://github.com/frostwire/frostwire-jlibtorrent/tree/master/binaries and put it in the root of your eclipse project (the one you are running). Other method is set up properly the java.library.path in your eclipse project.

**Comment by pierrewessman** [comment]
I am using Linux, but could try Windows also if needed. 

Ok, I´ll try that. Thanks!
