### ISSUE TITLE
Link on armhf architecture does not exists into get-binaries.sh script.

### ISSUE THREAD

**Issue by thesolwind** [frostwire/frostwire-jlibtorrent#143]
at the main page are specified linux architectures x86, x86_64, armhf, arm64 but link to armhf doesn't exists in swig/get-binaries.sh script.

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire-jlibtorrent/commit/d9ca7b06b3dfad9a13e2b361bc1fc509975ea474
