### ISSUE TITLE
torrenthandle.movestorage(...) deletes the ALL internal storage. if used with lolipopfilesystem.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#145]
opened by mistake on [frostwire/frostwire](https://github.com/frostwire/frostwire/issues/310#issuecomment-269733784) by @mianharisali

**Comment by aldenml** [comment]
Well, strictly speaking, anything related to `lolipopfilesystem` is out of `jlibtorrent`, however this happens to be relevant here. There is a similar (and more limited) issue reported in `libtorrent` with a fix already in `RC_1_1`, still not merged in `master`.

See issue https://github.com/arvidn/libtorrent/issues/1473 and PR https://github.com/arvidn/libtorrent/pull/1487

As soon as it gets into master, I will release `beta3` for testing.

**Comment by aldenml** [comment]
Hi @mianharisali, can you test `1.2.0.6-beta3` to see if the issue persists?

**Comment by mianharisali** [comment]
@aldenml  i will test in few hours and will let you know.

**Comment by mianharisali** [comment]
@aldenml i just tested ,same issue is still there.

**Comment by aldenml** [comment]
do you mind testing with `1.2.0.6-beta4` again?

**Comment by mianharisali** [comment]
@aldenml unfortunately this issue still exists .
