### ISSUE TITLE
Stability of 1.2

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#150]
Currently I am still using 1.1.x. How stable is the new version 1.2? Is it better to move to 1.2 to prevent crashes? Is the API of 1.2 already very final or will there some more changes in the future?

And thank you for your work :)

**Comment by aldenml** [comment]
I consider 1.2 a lot better version than 1.1.x. In the java side, I'm not adding anything new there, and in the `libtorrent` side, all bug fixes from `RC_1_1` are going to `master` regularly. I expect more API changes but not dramatic ones.

and thank you for the feedback :)
