### ISSUE TITLE
[Crash][Android][1.2.0.6-RC4] java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#158]
This error occurs randomly.

FATAL EXCEPTION: FinalizerWatchdogDaemon
                                                                                Process: com.gamemalt.streamtorrentvideos, PID: 1436
                                                                                java.util.concurrent.TimeoutException: com.frostwire.jlibtorrent.swig.session.finalize() timed out after 10 seconds
                                                                                    at com.frostwire.jlibtorrent.swig.libtorrent_jni.delete_session(Native Method)
                                                                                    at com.frostwire.jlibtorrent.swig.session.delete(session.java:31)
                                                                                    at com.frostwire.jlibtorrent.swig.session.finalize(session.java:24)
                                                                                    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                                    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                                    at java.lang.Thread.run(Thread.java:761)

**Comment by aldenml** [comment]
I believe https://github.com/frostwire/frostwire-jlibtorrent/issues/117 is related. Can you give me more information about the places do you dereference the session?

**Comment by mianharisali** [comment]
```
    public void stop() 
    {
        //remove all callbacks from handler
        if (libTorrentHandler != null)
            libTorrentHandler.removeCallbacksAndMessages(null);
        torrentSession.stop();
    }
```

**Comment by aldenml** [comment]
link to the source code?

**Comment by mianharisali** [comment]
It is not open source , but i am using 2 sessionManagers , 1 for fetching magnets and 1 for downloading.

after fetching the magnet , i close the magnet sessionManager.

but this error occurs randomly .

**Comment by aldenml** [comment]
That's ok.

Well, you need to remember that having 2 sessionManagers is equivalent to have two `libtorrent` sessions. Aren't you able to use the same?

**Comment by mianharisali** [comment]
ok , i will try one session , and will let you know.

Thank you 👍

**Comment by mianharisali** [comment]
the reason behind using 2 session was , few months ago , we faced a lot of problems for using single session for magnets and downloads.

the function in sessionmanager for fetching magnet timeouts a lot.

**Comment by proninyaroslav** [comment]
I still can't beat this problem. I think that to blame the Android garbage collection. For example, this occurs upon waking device from sleep mode.

**Comment by mianharisali** [comment]
@proninyaroslav are you using single session? if yes then does this problem still exists on single session?

**Comment by proninyaroslav** [comment]
@mianharisali Yes, this session running in a separate service throughout the work.

**Comment by aldenml** [comment]
device info? (just to get more information)

**Comment by mianharisali** [comment]
@aldenml 
Nexus 6p , Android 7.1.1

**Comment by proninyaroslav** [comment]
This happens on different devices and on all versions of Android 4.0 and above. I have a lot of bug reports.

**Comment by mianharisali** [comment]
Update : i am using 1 session , i am still getting this crash.

**Comment by mianharisali** [comment]
tried a lot but this issue is really random ,i think it occurs when you create and stop session frequently.
i am using 1 session in my app and getting this report very randomly after 5-20 seconds of closing my app.

**Comment by mianharisali** [comment]
i think it has to do with this method "sessionManager.stop()"

**Comment by gubatron** [comment]
yeah, you don't want to be stopping the session unless you want to destroy all bittorrent related activity.

**Comment by proninyaroslav** [comment]
@gubatron 
I terminate the session only at the time the app is terminated, but session is destroyed during sleep mode.

**Comment by mianharisali** [comment]
@gubatron i stop the session when the download task is finished.

but i think even stopping the session should not cause this problem.

**Comment by mianharisali** [comment]
@gubatron  @proninyaroslav  @aldenml 
i think this might be related/helpful

http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

**Comment by aldenml** [comment]
@mianharisali thanks for the SO link, I will take a deep look at it

**Comment by aldenml** [comment]
I expect this change (https://github.com/frostwire/frostwire-jlibtorrent/commit/841132071cd82ca2638f557d9582006fb7c36ec4) to alleviate the issue, since without it, there was a possibility that `session` by `s` was elected for GC but was still working, now, calling `.delete()` in `s` and avoid any call to `abort()` (or creation of `session_proxy`) the object is pinned. Let's see in the next RC.

**Comment by aldenml** [comment]
@mianharisali `1.2.0.7-RC3` is out, give it a try. It contains an important fix inside `libtorrent` related to memory corruption (https://github.com/arvidn/libtorrent/pull/1782). Let us know if this version improve (or solves) the `java.util.concurrent.TimeoutException`

**Comment by aldenml** [comment]
any news here?

**Comment by mianharisali** [comment]
@aldenml i was out of city and just got back, i will test it today , but it can take some time because this crash occurs randomly.

**Comment by aldenml** [comment]
I will close this, but feel free to reopen if the crash reappears.
