### ISSUE TITLE
Applying Settings

### ISSUE THREAD

**Issue by darkfrog26** [frostwire/frostwire-jlibtorrent#159]
There doesn't seem to be any documentation about how to apply settings.  I see there are references in `settings_pack` to proxy settings but it is incredibly unclear how to do this.  I'm quite surprised there's absolutely no demos or wiki information about how to accomplish this.

**Comment by gubatron** [comment]
Feel free to submit a SettingsTest.java PR.
You can find plenty of examples of how to use the settings API on FrostWire's source code.
