### ISSUE TITLE
[Android][1.2.0.6] Downloads remain at 0%

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#162]
Hello. After the upgrade to `1.2.0.6`, there were problems with downloading. Details here https://github.com/proninyaroslav/libretorrent/issues/79

**Comment by aldenml** [comment]
I will need more information, we are not experience this problem in our clients. Do you mind trying `1.2.0.7-RC3`?

**Comment by proninyaroslav** [comment]
Ok, i will be try `1.2.0.7-RC3`.

**Comment by proninyaroslav** [comment]
I tested a new version and still get this behavior. My steps to reproduce the problem:
1. Add torrent
2. After adding download doesn't take place. Removing and adding again doesn't always help
3. Reboot the app
4. After that downloading takes place. Even if I delete the torrent and add it again I don't need reboot

**Comment by mianharisali** [comment]
yes , some times i face this same issue , i occurs randomly.
sometimes downloading starts and some times it does not start.
same goes for fetch magnet , some time it fetches magnet quickly some times it timeouts a lot.

**Comment by proninyaroslav** [comment]
I revealed the pattern of this problem: this problem occurs only for those torrents that have been added using magnet links. With .torrent files this doesn't happen.

**Comment by aldenml** [comment]
Ok, now we are talking :) can you point me to a source code link in github where I can see the relevant logic?

**Comment by proninyaroslav** [comment]
Code for downloading magnet here https://github.com/proninyaroslav/libretorrent/blob/master/app/src/main/java/org/proninyaroslav/libretorrent/core/TorrentFetcher.java . Before updating to `1.2.0.6`, I did not make any changes to the logic's work. I just updated lib to this version and this problem appeared.

**Comment by aldenml** [comment]
I'm telling you, you need to stop creating a `SessionManager` for `fetchMagnet`, you are creating a session every time, and that mess with the DHT. I improved the code there, try to use `SessionManager` as a singleton and let me know.

**Comment by proninyaroslav** [comment]
Yes, you told me about this problem, but I don't think that this affects the lack of trackers.

**Comment by aldenml** [comment]
You are right, the lack of trackers is another problem, but I encourage you to change the code as soon as possible.

In any case, you need to remember that info-dicts stored in the DHT (the one retrieved via magnets) does not store the trackers. You have the trackers (and other parameters) in the magnet link url. If you want to retrieve all that information merged in the return of `SessionManager#fetchManget`, use the override with the parameter `extra=true`.
```java
public byte[] fetchMagnet(String uri, int timeout, boolean extra);
public byte[] fetchMagnet(String uri, int timeout, final boolean extra, final int maxSize);
```

**Comment by proninyaroslav** [comment]
Ok, I will reorganize code and try changing call to the `fetchMagnet`

**Comment by gubatron** [comment]
any luck @proninyaroslav ?

**Comment by mianharisali** [comment]
@gubatron i am not facing this problem anymore.

**Comment by aldenml** [comment]
good to know!
