### ISSUE TITLE
[1.2.0.8 - 1.2.0.9][Android] TorrentStatus.pieces() returns empty bitfield

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#168]
Hello. Starting with version `1.2.0.8` `TorrentStatus.pieces()` returns empty bitfield even when torrent is being downloaded or seeding. Moreover, `TorrentStatus.numPieces()` returns number of downloaded pieces.

**Comment by aldenml** [comment]
You need to use `TorrentHandle#status(long flags)` with the flag `StatusFlags.QUERY_PIECES`, that's an expensive field to retrieve. I'm closing this, but feel free to reopen if the API is not working as expected.
