### ISSUE TITLE
[1.2.0.9] Nev behaviour of AnnounceEntry

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#169]
Hello. Prior to version `1.2.0.9`, I used the following code to determine tracker status:
```Java
if (entry.swig().getVerified() && entry.swig().is_working()) {
    return Status.WORKING;
} else if ((entry.swig().getFails() == 0) && entry.swig().getUpdating()) {
    return Status.UPDATING;
} else if (entry.swig().getFails() == 0) {
    return Status.NOT_CONTACTED;
} else {
    return Status.NOT_WORKING;
}
```
but now these methods are removed from the libtorrent. Is there a similar way to get tracker status?

**Comment by aldenml** [comment]
Well, there is no way at this moment. When the refactor was done in `libtorrent` (related to the multi-home support) I didn't expose the new API via SWIG. I think I can do that in short time, I will let you know. Thanks for reporting this.

**Comment by proninyaroslav** [comment]
Very operational work, thank you! I'll test this feature right after lib appears in maven.

**Comment by aldenml** [comment]
@proninyaroslav `1.2.0.10` is ready in maven.

Remember that now `libtorrent` is multi-home. You need to take the `announce_entry` and ask for the vector of `announce_endpoint`s, then ask for the fields you were looking.
