### ISSUE TITLE
Save state of downloadable metadata

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#171]
Hello. Is it possible to save state of downloadable magnet using `fast resume`? From the `libtorrent` documentation I realized that it is impossible to do this, but in `qbittorrent` it is work. I believe that they use modified `fast resume`.

**Comment by aldenml** [comment]
Can you post the url link of `qbittorrent`? Are you talking about saving the part of the info-hash, in case the download is interrupted, to not request that parts again?

**Comment by proninyaroslav** [comment]
https://github.com/qbittorrent/qBittorrent

> Are you talking about saving the part of the info-hash

Yes, including saving itself magnet links.

**Comment by proninyaroslav** [comment]
For example `fast resume ` of added magnet link from `qbittorrent` 
[ed14485bfcee5daa5daa91193a7547b7a1317622.zip](https://github.com/frostwire/frostwire-jlibtorrent/files/1099501/ed14485bfcee5daa5daa91193a7547b7a1317622.zip)

**Comment by aldenml** [comment]
hehe, not the link of qbittorrent, but the link to documentation when they mention/document the feature.

Anyway, what I see in the `fastresume` file is just information to "reload the download" on app restart, no information related to the inner download state of the info-hash. (just open it in a text editor)

What I see is a pure UI/UX feature, and to really save the  "download state" of the metadata, we will need some support from `libtorrent`.
