### ISSUE TITLE
[Android][1.2.0.11-RC4] No alert is called if torrent is added with resume file.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#173]
is it normal ?
i think an alert should be called.

**Comment by aldenml** [comment]
I don't think it's normal, let me check, because we add torrents with resume file in our clients and we are getting the alert, otherwise the transfer is not added.

Are you sure you are adding the listener before adding the torrents?

**Comment by mianharisali** [comment]
@aldenml yes we are adding the listener before the torrent, but i will recheck the code again.

**Comment by mianharisali** [comment]
sorry , we checked the code and the fault was at our end.
thanks for your help :)
