### ISSUE TITLE
Can i specify file piece index to download?

### ISSUE THREAD

**Issue by kevinkindom** [frostwire/frostwire-jlibtorrent#175]
i want specify to download the video file, and real time to play it.

and i want specify time to play, Is this possible?

**Comment by aldenml** [comment]
The scope of this library (or `libtorrent` in general) is only download related. You can specify the file, blocks inside the file, and progressive download mode, but any matter related to actual play (real time or not), or video seeking, belongs to another layer (the media framework you select).
