### ISSUE TITLE
Most stable 1.2 version

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#179]
Please tell me which version is currently the most stable.

Latest 1.2.0.13-RC version or should I better use 1.2.0.12?

**Comment by aldenml** [comment]
For now, always use the latest RC one, I will improve the version handling situation in the future

**Comment by aldenml** [comment]
Ok, as an update, `>= 1.2.0.13-RC11` has an ugly bug, working on it

**Comment by aldenml** [comment]
I strongly recommend you use `1.2.0.13-RC14`

**Comment by gubatron** [comment]
I think we should now tag it to 1.2.0.13, seems pretty stable now.

**Comment by aldenml** [comment]
Waiting to have upstream CI jobs working to use it instead of custom fork

**Comment by gubatron** [comment]
👍
