### ISSUE TITLE
Android libjlibtorrent.so cross-compile ARM build instructions

### ISSUE THREAD

**Issue by j3g** [frostwire/frostwire-jlibtorrent#18]
You guys rock!!!
I have jlibtorrent working wonderfully in my Android App.
And for that, I think you. (documentation was great)

I love the build scripts...so helpful.
I am attempting to build libjlibtorrent.so  (libtorrent)
Step 1: get libtorrent sources
Step 2: set all environment variables
Step 3: run_swig.sh
Step 4: build_android.sh

Is this the correct order?

Getting missing file errors.
QUESTION: which libtorrent source version? 1.0.2, 1.0.4, latest?

Compiling on OSX Yosemite.

**Comment by j3g** [comment]
ok. I see from the commit statements that you have updating the build scripts to run against the latest trunk of the libtorrent source. The problem is that when I pull from a tag for 1.0.5, or download the source for 1.0.5...
i'm  missing some files when I run 'run_swig.sh':

swig/libtorrent.i:677: Error: Unable to find 'libtorrent/operations.hpp'
swig/libtorrent.i:678: Error: Unable to find 'libtorrent/performance_counters.hpp'
swig/libtorrent.i:679: Error: Unable to find 'libtorrent/close_reason.hpp'
swig/libtorrent.i:688: Error: Unable to find 'libtorrent/torrent_peer.hpp'
swig/libtorrent.i:692: Error: Unable to find 'libtorrent/aux_/session_settings.hpp'
swig/libtorrent.i:693: Error: Unable to find 'libtorrent/settings_pack.hpp'
swig/libtorrent.i:694: Error: Unable to find 'libtorrent/peer_class.hpp'
swig/libtorrent.i:695: Error: Unable to find 'libtorrent/peer_class_type_filter.hpp'
swig/libtorrent.i:699: Error: Unable to find 'libtorrent/disk_io_job.hpp'
swig/libtorrent.i:706: Error: Unable to find 'libtorrent/bdecode.hpp'

It seems the source code tagging is broken on their end.
The trunk has these files. The tags and source download are missing these files.
Will you please confirm?
Thank you!!!

**Comment by aldenml** [comment]
Hi @j3g and thank for your comments.

You should run from master (corresponding to libtorrent 1.0.4). Your only task should be run build_android.sh, since we are in charge of generating the libtorrent_jni.cpp (run_swig.sh). (You can do/run whatever you want of course). If you are working with master and libtorrent 1.0.4, you will need to replace "const static int" for "static const int" in alert_types.hpp.

Working with libtorrent-trunk branch is to risky.

I will keep this issue open in case you need further help.

**Comment by j3g** [comment]
I appreciate the feedback.
I'm making progress =)

I have more questions about 'build_android.sh'
What is this 'JDK_INCLUDE_2' ?

What path is this: 'LIBTORRENT_LIBS' ?

What is this? (I don't have these binary in my BOOST_ROOT)
#$BOOST_ROOT/b2 toolset=gcc-arm variant=release link=static target-os=linux --stagedir="android-arm" stage --without-context --without-coroutine --without-python --without-mpi --without-wave --without-test --without-graph --without-graph_parallel --without-iostreams --without-math
#$BOOST_ROOT/bjam toolset=gcc-arm variant=release link=static target-os=linux deprecated-functions=off logging=none boost=source

**Comment by j3g** [comment]
Do you get this warning when you build?
libtorrent-code-1.0.4/include/libtorrent/alert_types.hpp:819:3: note: in expansion of macro 'TORRENT_DEFINE_ALERT'
   TORRENT_DEFINE_ALERT(block_timeout_alert);
   ^
libtorrent-code-1.0.4/include/libtorrent/alert_types.hpp: At global scope:
libtorrent-code-1.0.4/include/libtorrent/alert_types.hpp:126:39: warning: 'auto_ptr' is deprecated (declared at toolchain-platform-15-arm-gcc-4.9/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  virtual std::auto_ptr<alert> clone() const \

**Comment by j3g** [comment]
seeing errors like this at compile:

toolchain-platform-15-arm-gcc-4.9/bin/../sysroot/usr/lib/crtbegin_dynamic.o:crtbrand.c:function _start: error: undefined reference to 'main'

/var/folders/8f/jtv44c2d231_rbvtfy2k4cc80000gq/T//ccyTtP6O.o:libtorrent_jni.cpp:function dht_get_peers_fun(std::vector<boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, std::allocator<boost::asio::ip::basic_endpoint<boost::asio::ip::tcp> > > const&, boost::shared_ptr<libtorrent::aux::session_impl>, libtorrent::sha1_hash const&): error: undefined reference to 'libtorrent::alert::alert()'

/var/folders/8f/jtv44c2d231_rbvtfy2k4cc80000gq/T//ccyTtP6O.o:libtorrent_jni.cpp:function Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_new_1block_1timeout_1alert: error: undefined reference to 'vtable for libtorrent::block_timeout_alert'

toolchain-platform-15-arm-gcc-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function

**Comment by aldenml** [comment]
The painful process of native compiling.

The JDK_INCLUDE_2 path is the Java JNI include path that is platform specific.
LIBTORRENT_LIBS is where you will put all the static libraries for compiling jlibtorrent.

```
MBP:arm aldenml$ ls -l
total 16264
-rw-r--r--  1 aldenml  staff     2226 Apr 22 23:58 libboost_atomic.a
-rw-r--r--  1 aldenml  staff   117726 Apr 22 23:59 libboost_chrono.a
-rw-r--r--  1 aldenml  staff   140616 Apr 22 23:59 libboost_date_time.a
-rw-r--r--  1 aldenml  staff    39614 Apr 23 00:02 libboost_random.a
-rw-r--r--  1 aldenml  staff    12266 Apr 22 23:58 libboost_system.a
-rw-r--r--  1 aldenml  staff   305018 Apr 22 23:59 libboost_thread.a
-rw-r--r--  1 aldenml  staff  7698092 Apr 23 00:09 libtorrent.a
MBP:arm aldenml$ 
```

Read build_windows.bat for more information about BOOST_ROOT.

Once you have all of this, let's check again the errors with the android toolchain.

**Comment by j3g** [comment]
do I need to cross-compile using NDK to get libtorrent.a?

**Comment by aldenml** [comment]
Yes, you need to compile boost and libtorrent with android NDK. For this, don't forget to copy the build/user-config.jam file to your home.

**Comment by drewtenn** [comment]
What version of SWIG are you using? I'm running 3.0.5 and I get the following error:

/libtorrent-android/jni/include/libtorrent/alert_types.hpp:58: Error: Syntax error in input(1).

Apparently SWIG doesn't like the const static (https://github.com/swig/swig/issues/241).

First time using SWIG. How are you guys getting around this?

**Comment by aldenml** [comment]
Check the comments above: "you will need to replace "const static int" for "static const int" in alert_types.hpp."

In libtorrent-trunk is already changed in the libtorrent side.

**Comment by drewtenn** [comment]
Bah, I missed that. Thanks.
