### ISSUE TITLE
[libtorrrent] download rate / upload rate unlimited values seem inconsistent

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#182]
CC: @arvidn

I think I found some buggy behavior with `BTDownload.java` which uses libtorrent's `torrent_handle` rate limit methods.

To make a story short:
Unlimited Download Limit = -1
Unlimited Upload Limit = 0

Download Limits cannot be set to 0
Upload Limits cannot be set to -1

Wonder if this is by design, or if this is a bug.

# with downloads
```setDownloadRateLimit(100)
getDownloadRateLimit() -> 100

setDownloadRateLimit(0)
getDownloadRateLimit() -> returns -1.

setDownloadRateLimit(-1)
btDL.getDownloadRateLimit() -> returns -1
```

# then with uploads
```setUploadRateLimit(100)
getUploadRateLimit() -> 100

setUploadRateLimit(0)
getUploadRateLimit() -> 0 (with download it returns -1)

setUploadRateLimit(-1)
getUploadRateLimit() -> 0
```

Here's the relevant code in libtorrent (I believe)

`torrent_handle.cpp`
```cpp
	void torrent_handle::set_upload_limit(int limit) const
	{
		TORRENT_ASSERT_PRECOND(limit >= -1);
		async_call(&torrent::set_upload_limit, limit);
	}

	int torrent_handle::upload_limit() const
	{
		return sync_call_ret<int>(0, &torrent::upload_limit);
	}

	void torrent_handle::set_download_limit(int limit) const
	{
		TORRENT_ASSERT_PRECOND(limit >= -1);
		async_call(&torrent::set_download_limit, limit);
	}

	int torrent_handle::download_limit() const
	{
		return sync_call_ret<int>(0, &torrent::download_limit);
	}
```

then in `torrent.cpp`

```cpp
void torrent::set_upload_limit(int limit)
	{
		set_limit_impl(limit, peer_connection::upload_channel);
		set_need_save_resume();
#ifndef TORRENT_DISABLE_LOGGING
		debug_log("*** set-upload-limit: %d", limit);
#endif
	}

	void torrent::set_download_limit(int limit)
	{
		set_limit_impl(limit, peer_connection::download_channel);
		set_need_save_resume();
#ifndef TORRENT_DISABLE_LOGGING
		debug_log("*** set-download-limit: %d", limit);
#endif
	}

	void torrent::set_limit_impl(int limit, int channel, bool state_update)
	{
		TORRENT_ASSERT(is_single_thread());
		TORRENT_ASSERT(limit >= -1);
		if (limit <= 0) limit = 0;

		if (m_peer_class == peer_class_t{0})
		{
			if (limit == 0) return;
			setup_peer_class();
		}

		struct peer_class* tpc = m_ses.peer_classes().at(m_peer_class);
		TORRENT_ASSERT(tpc);
		if (tpc->channel[channel].throttle() != limit && state_update)
			state_updated();
		tpc->channel[channel].throttle(limit);
	}

	void torrent::setup_peer_class()
	{
		TORRENT_ASSERT(m_peer_class == peer_class_t{0});
		m_peer_class = m_ses.peer_classes().new_peer_class(name());
		add_class(m_ses.peer_classes(), m_peer_class);
	}

	int torrent::limit_impl(int channel) const
	{
		TORRENT_ASSERT(is_single_thread());

		if (m_peer_class == peer_class_t{0}) return -1;
		int limit = m_ses.peer_classes().at(m_peer_class)->channel[channel].throttle();
		if (limit == (std::numeric_limits<int>::max)()) limit = -1;
		return limit;
	}

	int torrent::upload_limit() const
	{
		return limit_impl(peer_connection::upload_channel);
	}

	int torrent::download_limit() const
	{
		return limit_impl(peer_connection::download_channel);
	}
```

**Comment by arvidn** [comment]
I haven't looked deeper into this, but in the code you post here, it looks like the upload and download cases are symmetric.

btw, the intention is that -1 indicates unlimited, and that 0 can be made to mean literally 0 bytes per second (but originally 0 meant unlimited, so I've left it to still mean that, for backwards compatibility).

**Comment by gubatron** [comment]
I see, so to set download limit to 0, just pause the transfer, but then again what if I wish to not download and only upload (weird case).

what I don't get is how do I set upload rate to unlimited? or do I interpret upload to 0 bytes/sec to unlimited?

**Comment by gubatron** [comment]
what I don't like about the Max int solution for upload is that I bet that some bit is set with regards to throttling, and I'll always have cpu cycles being used to check if the upload rate is being hit, when in reality I want it to be un-throttled

**Comment by arvidn** [comment]
i'm suggesting that you should set the rate limit to -1 if you want it to be unlimited. and if anything fails when you do that, that's a bug that should be fixed.

**Comment by gubatron** [comment]
Thank you! I'll close this for now, if it fails, then I'll open a bug report.

**Comment by arvidn** [comment]
it still looks like there are a few questionable behaviors. like:

"Upload Limits cannot be set to -1"

and that -1 isn't returned consistently for unlimited settings.
