### ISSUE TITLE
Checking resume data status

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#185]
I add torrents with SessionManager.download(TorrentInfo ti, File saveDir)

But for a short time I can see that the added torrent has the status 'checking_resume_data'.

Does that make any sense or is it a bug maybe?

**Comment by aldenml** [comment]
well, let me take a look at it, that logic is inside `libtorrent`, not in this java wrapper

**Comment by aldenml** [comment]
See https://github.com/arvidn/libtorrent/issues/2535

**Comment by aldenml** [comment]
It's that way by design. if UI/UX is an issue, I think you can keep track of the fact that actual resume data was provided or not, and adjust the GUI accordingly.
