### ISSUE TITLE
resume_data_flags_t

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#187]
Is it possible that something is missing in your resume_data_flags_t class?

I miss the 3 constants.

**Comment by gubatron** [comment]
could please you elaborate more what you're trying to do and what 3 constants you're missing on?

Cheers

**Comment by WhiteTrashLord** [comment]
I found this in the Libtorrent documentation:

enum save_resume_flags_t

flush_disk_cache  1
save_info_dict 2
only_if_modified 4

How could I set it with JLibtorrent?

**Comment by aldenml** [comment]
Fixed with https://github.com/frostwire/frostwire-jlibtorrent/commit/fba73a29b1fbe23a9387502e9339fefffebd8442.

@WhiteTrashLord in the meantime you can use `torrent_handle.flush_disk_cache`, `torrent_handle.save_info_dict` and `torrent_handle.only_if_modified` directly in the `swig()` object.

**Comment by gubatron** [comment]
so you'd now use it like this I suppose

```java
TorrentHandle th;
...
// save_info_dict | flush_disk_cache
th.saveResumeData(TorrentHandle.SAVE_INFO_DICT.or_(TorrentHandle.FLUSH_DISK_CACHE));
```

**Comment by aldenml** [comment]
yes
