### ISSUE TITLE
torrent_status::paused

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#188]
I would like to check if a torrent is paused.
I found this comment in your code:

 To know if a * torrent is active or not, you need to inspect both
     * ``torrent_status::paused`` and ``session::is_paused()``.

But torrent_status doesn't have a paused field :(

Will you add it?

**Comment by gubatron** [comment]
I believe that flag is still there, we use it like this:
```
private static boolean isPaused(TorrentStatus s) {
        return s.flags().and_(TorrentFlags.PAUSED).nonZero();
    }
```

however you also need to check things like, is your session paused, and is your torrent handle still valid.
