### ISSUE TITLE
Crash SIGSEGV

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#193]
Jlibtorrent was working very stable. But now I am seeing a lot of crashes :(

I hope this information is helpful and you can fix the problem. I also upgraded to the latest version but it didn't help. The OS is Linux 64 bit.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fad14aa1bd9, pid=3013, tid=0x00007fad0ffff700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjlibtorrent-1.2.0.16.so+0x20abd9]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000000f8

Registers:
RAX=0x0000000000000000, RBX=0x00007facc0090270, RCX=0x0000000000000000, RDX=0x0000000000000084
RSP=0x00007fad0fffe5b0, RBP=0x0000000000000000, RSI=0x00007facc048b2e0, RDI=0x00007facc05e1028
R8 =0x0000000000004000, R9 =0x0000000000000001, R10=0x00007facbc72d530, R11=0x0000000000000000
R12=0x0000000000000013, R13=0x0000000000000000, R14=0x00007facc05e1020, R15=0x0000000000000009
RIP=0x00007fad14aa1bd9, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fad0fffe5b0)
0x00007fad0fffe5b0:   00007facc05e1028 0000000000000000
0x00007fad0fffe5c0:   0000000000000000 0000000000000000
0x00007fad0fffe5d0:   0000000000000000 0000000000000000
0x00007fad0fffe5e0:   0000000000000000 0000000000000000
0x00007fad0fffe5f0:   0000000000000000 0000000000000000
0x00007fad0fffe600:   0000000000000000 ffffffff00000000
0x00007fad0fffe610:   00007fad0fffe650 00007ffd1ebc1ce4
0x00007fad0fffe620:   00007fad0fffe680 0000000100000000
0x00007fad0fffe630:   0000000000000000 00007facbc7295d8
0x00007fad0fffe640:   00007facc0208330 0000000000000000
0x00007fad0fffe650:   00007facbc7295d8 0000000000000049
0x00007fad0fffe660:   0000000000000049 00007facc073a758
0x00007fad0fffe670:   00007facc0283940 00007fad14af5fd3
0x00007fad0fffe680:   00007facc0283940 00007fad0fffe6c0
0x00007fad0fffe690:   00007facbc7295d8 00007fad0fffe6b0
0x00007fad0fffe6a0:   00007facc04c9e80 00007facc048bed0
0x00007fad0fffe6b0:   00007facc073a758 0000000000000000
0x00007fad0fffe6c0:   00007facc0090270 00007facc0580820
0x00007fad0fffe6d0:   00007facc0283940 00007fad14ca42a9
0x00007fad0fffe6e0:   00007facbc7294f8 00007fad14b19787
0x00007fad0fffe6f0:   00007facbc7294f8 00007facbc729510
0x00007fad0fffe700:   00007fad0fffe720 00007fad14aae73f
0x00007fad0fffe710:   00007facbc7295d8 00007fad0fffe7a8
0x00007fad0fffe720:   00007facbc7294f8 e4aacdee47b08a00
0x00007fad0fffe730:   00007facc0090270 00007facc0090270
0x00007fad0fffe740:   00007fad0fffe860 00007fad0fffe701
0x00007fad0fffe750:   000000000001892c 00007fad0fffe7a8
0x00007fad0fffe760:   00007facc0a60010 00007fad14aa37c4
0x00007fad0fffe770:   00007fad0fffe8e0 00007fad0fffe7d0
0x00007fad0fffe780:   00007fad0fffe8c0 00007fad00000000
0x00007fad0fffe790:   00007fad15070970 00007fad14c829e8
0x00007fad0fffe7a0:   000000000000000a 00007facc0090270 

Instructions: (pc=0x00007fad14aa1bd9)
0x00007fad14aa1bb9:   eb da 48 8d bc 24 f0 00 00 00 e8 3c 89 00 00 4c
0x00007fad14aa1bc9:   89 e7 e8 42 89 00 00 45 85 ff 74 0b 48 8b 43 08
0x00007fad14aa1bd9:   44 89 b8 f8 00 00 00 be 07 00 00 00 48 89 df 4c
0x00007fad14aa1be9:   8d b4 24 d8 00 00 00 e8 9b ed ff ff 48 8b 73 10 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007facc0090270 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000084 is an unknown value
RSP=0x00007fad0fffe5b0 is an unknown value
RBP=0x0000000000000000 is an unknown value
RSI=0x00007facc048b2e0 is an unknown value
RDI=0x00007facc05e1028 is an unknown value
R8 =0x0000000000004000 is an unknown value
R9 =0x0000000000000001 is an unknown value
R10=0x00007facbc72d530 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x0000000000000013 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x00007facc05e1020 is an unknown value
R15=0x0000000000000009 is an unknown value

Stack: [0x00007fad0f7ff000,0x00007fad10000000],  sp=0x00007fad0fffe5b0,  free space=8189k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjlibtorrent-1.2.0.16.so+0x20abd9]

[error occurred during error reporting (printing native stack), id 0xb]

---------------  P R O C E S S  ---------------

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 139776K, used 67632K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 129024K, 52% used [0x000000076ca00000,0x0000000770c0c1d8,0x0000000774800000)
  from space 10752K, 0% used [0x0000000775280000,0x0000000775280000,0x0000000775d00000)
  to   space 10752K, 0% used [0x0000000774800000,0x0000000774800000,0x0000000775280000)
 ParOldGen       total 104448K, used 17472K [0x00000006c5e00000, 0x00000006cc400000, 0x000000076ca00000)
  object space 104448K, 16% used [0x00000006c5e00000,0x00000006c6f10240,0x00000006cc400000)
 Metaspace       used 24330K, capacity 24712K, committed 25088K, reserved 1071104K
  class space    used 2612K, capacity 2702K, committed 2816K, reserved 1048576K

Card table byte_map: [0x00007fad3a0fa000,0x00007fad3a8cc000] byte_map_base: 0x00007fad36acb000

Marking Bits: (ParMarkBitMap*) 0x00007fad3cffdf80
 Begin Bits: [0x00007facf02f0000, 0x00007facf4178000)
 End Bits:   [0x00007facf4178000, 0x00007facf8000000)

Polling page: 0x00007fad3dc4e000

CodeCache: size=245760Kb used=7725Kb max_used=7725Kb free=238034Kb
 bounds [0x00007fad25000000, 0x00007fad257c0000, 0x00007fad34000000]
 total_blobs=2629 nmethods=2175 adapters=367
 compilation: enabled

Compilation events (10 events):
Event: 19.780 Thread 0x00007fad340c7800 2612       3       java.text.DigitList::set (346 bytes)
Event: 19.781 Thread 0x00007fad340c7800 nmethod 2612 0x00007fad254f6810 code [0x00007fad254f6a20, 0x00007fad254f76b8]
Event: 19.782 Thread 0x00007fad340c7800 2614       3       com.frostwire.jlibtorrent.swig.session_handle::post_torrent_updates (9 bytes)
Event: 19.782 Thread 0x00007fad340c7800 nmethod 2614 0x00007fad254f6490 code [0x00007fad254f6600, 0x00007fad254f6788]
Event: 19.783 Thread 0x00007fad340c7800 2615       3       com.frostwire.jlibtorrent.swig.torrent_status::getTotal_wanted (9 bytes)
Event: 19.783 Thread 0x00007fad340c7800 nmethod 2615 0x00007fad254f5d90 code [0x00007fad254f5f00, 0x00007fad254f6088]
Event: 19.784 Thread 0x00007fad340c7800 2617       3       com.frostwire.jlibtorrent.swig.torrent_status::getDownload_payload_rate (9 bytes)
Event: 19.784 Thread 0x00007fad340c7800 nmethod 2617 0x00007fad254f5a10 code [0x00007fad254f5b80, 0x00007fad254f5d08]
Event: 19.784 Thread 0x00007fad340c7800 2618       3       java.lang.Double::isInfinite (22 bytes)
Event: 19.784 Thread 0x00007fad340c7800 nmethod 2618 0x00007fad254f5610 code [0x00007fad254f57a0, 0x00007fad254f59b0]

GC Heap History (10 events):
Event: 1.850 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 75264K, used 64512K [0x000000076ca00000, 0x0000000771e00000, 0x00000007c0000000)
  eden space 64512K, 100% used [0x000000076ca00000,0x0000000770900000,0x0000000770900000)
  from space 10752K, 0% used [0x0000000771380000,0x0000000771380000,0x0000000771e00000)
  to   space 10752K, 0% used [0x0000000770900000,0x0000000770900000,0x0000000771380000)
 ParOldGen       total 172032K, used 0K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 0% used [0x00000006c5e00000,0x00000006c5e00000,0x00000006d0600000)
 Metaspace       used 13299K, capacity 13542K, committed 13824K, reserved 1060864K
  class space    used 1450K, capacity 1492K, committed 1536K, reserved 1048576K
Event: 1.860 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 75264K, used 10746K [0x000000076ca00000, 0x0000000771e00000, 0x00000007c0000000)
  eden space 64512K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000770900000)
  from space 10752K, 99% used [0x0000000770900000,0x000000077137eb08,0x0000000771380000)
  to   space 10752K, 0% used [0x0000000771380000,0x0000000771380000,0x0000000771e00000)
 ParOldGen       total 172032K, used 1425K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 0% used [0x00000006c5e00000,0x00000006c5f646d0,0x00000006d0600000)
 Metaspace       used 13299K, capacity 13542K, committed 13824K, reserved 1060864K
  class space    used 1450K, capacity 1492K, committed 1536K, reserved 1048576K
}
Event: 1.986 GC heap before
{Heap before GC invocations=2 (full 0):
 PSYoungGen      total 75264K, used 75258K [0x000000076ca00000, 0x0000000771e00000, 0x00000007c0000000)
  eden space 64512K, 100% used [0x000000076ca00000,0x0000000770900000,0x0000000770900000)
  from space 10752K, 99% used [0x0000000770900000,0x000000077137eb08,0x0000000771380000)
  to   space 10752K, 0% used [0x0000000771380000,0x0000000771380000,0x0000000771e00000)
 ParOldGen       total 172032K, used 1425K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 0% used [0x00000006c5e00000,0x00000006c5f646d0,0x00000006d0600000)
 Metaspace       used 13389K, capacity 13574K, committed 13824K, reserved 1060864K
  class space    used 1453K, capacity 1524K, committed 1536K, reserved 1048576K
Event: 1.997 GC heap after
Heap after GC invocations=2 (full 0):
 PSYoungGen      total 75264K, used 10726K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 64512K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000770900000)
  from space 10752K, 99% used [0x0000000771380000,0x0000000771df98d0,0x0000000771e00000)
  to   space 10752K, 0% used [0x0000000770900000,0x0000000770900000,0x0000000771380000)
 ParOldGen       total 172032K, used 8936K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 5% used [0x00000006c5e00000,0x00000006c66ba210,0x00000006d0600000)
 Metaspace       used 13389K, capacity 13574K, committed 13824K, reserved 1060864K
  class space    used 1453K, capacity 1524K, committed 1536K, reserved 1048576K
}
Event: 3.614 GC heap before
{Heap before GC invocations=3 (full 0):
 PSYoungGen      total 75264K, used 75238K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 64512K, 100% used [0x000000076ca00000,0x0000000770900000,0x0000000770900000)
  from space 10752K, 99% used [0x0000000771380000,0x0000000771df98d0,0x0000000771e00000)
  to   space 10752K, 0% used [0x0000000770900000,0x0000000770900000,0x0000000771380000)
 ParOldGen       total 172032K, used 8936K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 5% used [0x00000006c5e00000,0x00000006c66ba210,0x00000006d0600000)
 Metaspace       used 17966K, capacity 18206K, committed 18432K, reserved 1064960K
  class space    used 1912K, capacity 1980K, committed 2048K, reserved 1048576K
Event: 3.623 GC heap after
Heap after GC invocations=3 (full 0):
 PSYoungGen      total 75264K, used 10737K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 64512K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000770900000)
  from space 10752K, 99% used [0x0000000770900000,0x000000077137c638,0x0000000771380000)
  to   space 10752K, 0% used [0x0000000775280000,0x0000000775280000,0x0000000775d00000)
 ParOldGen       total 172032K, used 15642K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 9% used [0x00000006c5e00000,0x00000006c6d46b08,0x00000006d0600000)
 Metaspace       used 17966K, capacity 18206K, committed 18432K, reserved 1064960K
  class space    used 1912K, capacity 1980K, committed 2048K, reserved 1048576K
}
Event: 9.047 GC heap before
{Heap before GC invocations=4 (full 0):
 PSYoungGen      total 75264K, used 41028K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 64512K, 46% used [0x000000076ca00000,0x000000076e794c08,0x0000000770900000)
  from space 10752K, 99% used [0x0000000770900000,0x000000077137c638,0x0000000771380000)
  to   space 10752K, 0% used [0x0000000775280000,0x0000000775280000,0x0000000775d00000)
 ParOldGen       total 172032K, used 15642K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 9% used [0x00000006c5e00000,0x00000006c6d46b08,0x00000006d0600000)
 Metaspace       used 20771K, capacity 21054K, committed 21296K, reserved 1069056K
  class space    used 2258K, capacity 2332K, committed 2432K, reserved 1048576K
Event: 9.078 GC heap after
Heap after GC invocations=4 (full 0):
 PSYoungGen      total 139776K, used 10739K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 129024K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000774800000)
  from space 10752K, 99% used [0x0000000775280000,0x0000000775cfce88,0x0000000775d00000)
  to   space 10752K, 0% used [0x0000000774800000,0x0000000774800000,0x0000000775280000)
 ParOldGen       total 172032K, used 22596K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 13% used [0x00000006c5e00000,0x00000006c7411130,0x00000006d0600000)
 Metaspace       used 20771K, capacity 21054K, committed 21296K, reserved 1069056K
  class space    used 2258K, capacity 2332K, committed 2432K, reserved 1048576K
}
Event: 9.078 GC heap before
{Heap before GC invocations=5 (full 1):
 PSYoungGen      total 139776K, used 10739K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 129024K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000774800000)
  from space 10752K, 99% used [0x0000000775280000,0x0000000775cfce88,0x0000000775d00000)
  to   space 10752K, 0% used [0x0000000774800000,0x0000000774800000,0x0000000775280000)
 ParOldGen       total 172032K, used 22596K [0x00000006c5e00000, 0x00000006d0600000, 0x000000076ca00000)
  object space 172032K, 13% used [0x00000006c5e00000,0x00000006c7411130,0x00000006d0600000)
 Metaspace       used 20771K, capacity 21054K, committed 21296K, reserved 1069056K
  class space    used 2258K, capacity 2332K, committed 2432K, reserved 1048576K
Event: 9.129 GC heap after
Heap after GC invocations=5 (full 1):
 PSYoungGen      total 139776K, used 0K [0x000000076ca00000, 0x0000000775d00000, 0x00000007c0000000)
  eden space 129024K, 0% used [0x000000076ca00000,0x000000076ca00000,0x0000000774800000)
  from space 10752K, 0% used [0x0000000775280000,0x0000000775280000,0x0000000775d00000)
  to   space 10752K, 0% used [0x0000000774800000,0x0000000774800000,0x0000000775280000)
 ParOldGen       total 104448K, used 17472K [0x00000006c5e00000, 0x00000006cc400000, 0x000000076ca00000)
  object space 104448K, 16% used [0x00000006c5e00000,0x00000006c6f10240,0x00000006cc400000)
 Metaspace       used 20771K, capacity 21054K, committed 21296K, reserved 1069056K
  class space    used 2258K, capacity 2332K, committed 2432K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 9.381 Thread 0x00007fad342a7800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007fad254a8b10 method=java.lang.StringCoding.safeTrim([CILjava/nio/charset/Charset;Z)[C @ 3
Event: 9.382 Thread 0x00007fad342a7800 Uncommon trap: reason=range_check action=make_not_entrant pc=0x00007fad251c5dc8 method=sun.reflect.generics.parser.SignatureParser.current()C @ 34
Event: 9.388 Thread 0x00007fad34288000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00007fad253e1ed4 method=java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(Ljava/lang/ThreadLocal;ILjava/lang/ThreadLocal$ThreadLocalMap$Entry;)Ljava/lang/ThreadLocal$ThreadLocalMap$Entry; 
Event: 9.388 Thread 0x00007fac4800b800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00007fad253e1ed4 method=java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(Ljava/lang/ThreadLocal;ILjava/lang/ThreadLocal$ThreadLocalMap$Entry;)Ljava/lang/ThreadLocal$ThreadLocalMap$Entry; 
Event: 9.448 Thread 0x00007fac7000d000 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00007fad2574ce08 method=java.nio.charset.CharsetDecoder.reset()Ljava/nio/charset/CharsetDecoder; @ 1
Event: 9.453 Thread 0x00007fac3c015800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00007fad2574ce08 method=java.nio.charset.CharsetDecoder.reset()Ljava/nio/charset/CharsetDecoder; @ 1
Event: 9.463 Thread 0x00007fac34019800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00007fad2574ce08 method=java.nio.charset.CharsetDecoder.reset()Ljava/nio/charset/CharsetDecoder; @ 1
Event: 9.499 Thread 0x00007fac40048000 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00007fad2574ce08 method=java.nio.charset.CharsetDecoder.reset()Ljava/nio/charset/CharsetDecoder; @ 1
Event: 16.215 Thread 0x00007fac4800d000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00007fad25764674 method=sun.misc.URLClassPath.getLoader(I)Lsun/misc/URLClassPath$Loader; @ 94
Event: 16.215 Thread 0x00007fac4800d000 Uncommon trap: reason=unloaded action=reinterpret pc=0x00007fad25666670 method=sun.misc.URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; @ 142

Internal exceptions (10 events):
Event: 9.381 Thread 0x00007fac4800f000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x000000076d9c2c00) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 605]
Event: 9.381 Thread 0x00007fac48009800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x000000076d424d48) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 605]
Event: 9.382 Thread 0x00007fad342a7800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 139> (0x000000076d604848) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.382 Thread 0x00007fac48013000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076dc2fc18) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.381 Thread 0x00007fac4800d000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x000000076da34578) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 605]
Event: 9.382 Thread 0x00007fad34412800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076d186530) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.382 Thread 0x00007fac4800b800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076f287140) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.382 Thread 0x00007fad34288000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076d28c2f0) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.383 Thread 0x00007fad3428d800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076d33b280) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]
Event: 9.383 Thread 0x00007fad342ad000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 61> (0x000000076d767d78) thrown at [/HUDSON/workspace/8-2-build-linux-amd64/jdk8u151/9699/hotspot/src/share/vm/interpreter/interpreterRuntime.cpp, line 366]

Events (10 events):
Event: 17.742 Executing VM operation: RevokeBias
Event: 17.742 Executing VM operation: RevokeBias done
Event: 18.977 Thread 0x00007facc8002000 Thread exited: 0x00007facc8002000
Event: 18.977 Thread 0x00007fad3440d000 Thread exited: 0x00007fad3440d000
Event: 18.978 loading class java/util/concurrent/ConcurrentHashMap$ValueIterator
Event: 18.978 loading class java/util/concurrent/ConcurrentHashMap$ValueIterator done
Event: 19.770 Thread 0x00007fad340c7800 flushing nmethod 0x00007fad25136190
Event: 19.770 Thread 0x00007fad340c7800 flushing nmethod 0x00007fad25147f50
Event: 19.771 Thread 0x00007fad340c7800 flushing nmethod 0x00007fad25184f50
Event: 19.771 Thread 0x00007fad340c7800 flushing nmethod 0x00007fad2518ad50

**Comment by WhiteTrashLord** [comment]
I think I found 1 or 2 torrents which are responsible for the crashes. Can you give me your email so I can send you more information?

**Comment by aldenml** [comment]
This crash looks strange to me, at least it's not the format I get in macOS and Windows. Are these torrents clear, content wise?

**Comment by WhiteTrashLord** [comment]
They are Anime torrents so I am not very sure :D

**Comment by WhiteTrashLord** [comment]
I submited a request on your website. You can check it if you want. I really would like to have a fix. I could reproduce the crash multiple times. But I didn't get any confirmation on your website that you received my request.

**Comment by WhiteTrashLord** [comment]
@gubatron 

I opened a ticket via support.frostwire.com with details about the torrents which will cause a crash.

**Comment by WhiteTrashLord** [comment]
https://github.com/arvidn/libtorrent/pull/2778

Will this bugfix be included in the next jlibtorrent version? I would like to test if it solved the problems I had.

**Comment by aldenml** [comment]
yes, it will be

**Comment by aldenml** [comment]
Hi @WhiteTrashLord, `1.2.0.17-RC1` is out, can you give it a try? Now I have debug information that I can look at once you give me some crash logs. I prefer if you attach the files (at least two).

**Comment by WhiteTrashLord** [comment]
Thank you. It seems this bugfix solved it :)
