### ISSUE TITLE
[Android] Again about SAF

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#197]
Hi. I recently tried the code to work with SAF from the Frostwire project, which uses a posix wrapper https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/LollipopFileSystem.java . This works fine, but there is one big enough problem: if for the external storage the method `StorageVolume#getUuid` returns null (in the `LollipopFilesystem#getVolumeId` method), then I can't get path to the file or path to the external storage itself, and so I can't download file. I checked on some emulators and phones and many SD cards and USB devices don't return UUID. Is there another workaround for getting path to the external storage?

**Comment by aldenml** [comment]
thanks for pointing this out, probably we are hitting the same problem but not noticing it due to the silent try-catch. Let met take a look at it.

**Comment by proninyaroslav** [comment]
A small typo - `getUuid` in `LollipopFilesystem#getVolumePath`, not in `getVolumeId`.

**Comment by proninyaroslav** [comment]
Hi. Is there any news on this issue?

**Comment by aldenml** [comment]
Hi @proninyaroslav, unfortunately I have no progress on this, I was doing some research to see how I can improve this overall, but still working on it.
