### ISSUE TITLE
Can you provide construct method of TorrentInfo 

### ISSUE THREAD

**Issue by waltli** [frostwire/frostwire-jlibtorrent#202]
Get TorrentInfo object only :
`public TorrentInfo(File torrent) {
        this(bdecode0(torrent));
    }`
 Please provide two construct method below:
`public TorrentInfo(InputStream is, long fileSize) {
        this(bdecode0(is, fileSize));
    }`
   
`public TorrentInfo(byte[] data) {
        this(bdecode0(data));
    }`
    

Thanks

**Comment by aldenml** [comment]
I will only add `public TorrentInfo(byte[] data)`, since the one taking an `InputStream` will be implemented using the one with `byte[]`, I rather the user of the library implement that logic. Btw, this particular class is not for high performance parsing of torrents.

**Comment by aldenml** [comment]
See https://github.com/frostwire/frostwire-jlibtorrent/commit/ec2324ad3c3b1212e99ba5a4f88f3405f9442bc7

**Comment by waltli** [comment]
Ok, thank you very much!
