### ISSUE TITLE
[1.2.0.18-RC10] Strange behaviour of overridden PeerInfo::init() method

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#205]
Hi. I needed to extend `PeerInfo` class and add some fields (`port`, `pieces`). I inherited this class, and also override `init()` method to fill in my own fields. I saw a warning comment. As a result, if I override `init()` method and call it in constructor, after this all fields of the superclass become null or zero (`ip`, `client`, etc). So I deleted the overridden method and fill fields in constructor, and it works great. Why is this happening?

**Comment by aldenml** [comment]
did you call `super.init()` in your override? and you should not need to call it in your constructor. In any case, I have seconds thoughts about this design, since it's an anti-pattern to call a virtual method in a constructor, more so if it's the "actual constructor" such a method.

**Comment by proninyaroslav** [comment]
I thought that calling `super.init()` in an overridden method is superfluous, as it is already done in the superclass constructor.

**Comment by aldenml** [comment]
actually, it's not :)

**Comment by proninyaroslav** [comment]
This is an example with problem:
```Java
public AdvancedPeeeInfo(peer_info p) {
    super(p);
    init(p);
}

@Override
protected void init(peer_info p) {
    //init fields
}
```

An example without problem:
```Java
public AdvancedPeeeInfo(peer_info p) {
    super(p);
    //init fields
}
```

**Comment by aldenml** [comment]
Make it like this
```java
public AdvancedPeeeInfo(peer_info p) {
    super(p);
}

@Override
protected void init(peer_info p) {
    super.init(p);
    //your extra logic here
}
```

**Comment by proninyaroslav** [comment]
Thanks, every time I open new things in Java)

**Comment by gubatron** [comment]
yeah, the whole point of overriding a method in a child is that you have the option if completely changing the behavior, or doing something before or after the parent behavior if you choose to call the super method.
