### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by AntonAleksandrov13** [frostwire/frostwire-jlibtorrent#211]
Good afternoon,
I am not quite experienced with your library. I need to know if there is a way to know if a peer has fully downloaded a file I am seeding.

Kind regards,
Anton Aleksandrov

**Comment by gubatron** [comment]
do you have a piece of code already that's a starting point?
This library is now unmaintained, your best bet is to look at FrostWire's code, look inside the 'common' folder, and to read libtorrent's docs.

My guess is that you need to use some sort of peer_alert mechanism and check if the other peer has all the pieces corresponding to the file you're wondering if they've fully downloaded.

Important to note that pieces span across one or more files. Think of the start of a file or the ending of a file, those pieces might also correspond to surrounding files.

**Comment by proninyaroslav** [comment]
@aldenml I could give any help :)

**Comment by aldenml** [comment]
Sure, testing :)

**Comment by AntonAleksandrov13** [comment]
Thank you for your quick responses. 
My best guess was to catch "peer snubbed" event or keep track if a peer is being interested in receiving.
I am not quite sure if your library supports that
