### ISSUE TITLE
Select files to download from torrent

### ISSUE THREAD

**Issue by Larsg310** [frostwire/frostwire-jlibtorrent#212]
I'm currently looking for a way to download a single file from a torrent containing multiple files. 

For example, I have a torrent with an MKV file and a readme.txt file.
I only want to download the MKV file, and not the readme.txt file, as I don't need it.

Is this possible?

**Comment by proninyaroslav** [comment]
You can ignore other files, just setting their priority as ignore:
```Java
torrentHandle.filePriority(fileIndex0, Priority.IGNORE);
torrentHandle.filePriority(fileIndex1, Priority.IGNORE);
...
```
