### ISSUE TITLE
Torrent is not downloading

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#213]
I tested jlibtorrent with a torrent file with a HTTPS tracker.
It's not working and jlibtorrent does not download anything. It also doesn't find any peers.
I also tested it with FrostWire. There I have the same problem. Nothing happens.

But qBittorrent 4.1.4 is downloading without any problems. It uses Libtorrent 1.1.11.
What could be the problem?

**Comment by proninyaroslav** [comment]
HTTPS trackers should work https://github.com/frostwire/frostwire-jlibtorrent/issues/170

**Comment by aldenml** [comment]
@WhiteTrashLord  Can you provide me a torrent that's "content clear" (no copyrighted material) with such a problem?

**Comment by WhiteTrashLord** [comment]
@aldenml Yes, I can send you a Public Domain torrent file. What is your email address or how can I send it to you? One of the tracker errors show also this message: unexpected end of file in bencoded string ""

**Comment by aldenml** [comment]
good, for Public Domain I think you can just attach it here in a PR comment, my email: aldenml at gmail.com

**Comment by WhiteTrashLord** [comment]
@aldenml

Please check your emails :) In another issue I read that you might work on a fork. Or you can still work on this codebase?
