### ISSUE TITLE
Please update v1.2.0.19 on Maven.

### ISSUE THREAD

**Issue by lucca2011** [frostwire/frostwire-jlibtorrent#219]
Thanks so much for your work.

**Comment by gubatron** [comment]
I'm going to try and migrate the project instead to https://jitpack.io/

I don't have access to update Maven and the process to get there is too bureaucratic.

**Comment by gubatron** [comment]
PR requests to do this are much welcome

**Comment by proninyaroslav** [comment]
Also you can use actual fork of this project https://github.com/aldenml/libtorrent4j

**Comment by rajatpundir** [comment]
TorrentStream have the jitpack.io, can it be utilised?

**Comment by lucca2011** [comment]
Hi guys, i have built it  with travis, thanks so much.
