### ISSUE TITLE
"feature to disable DHT, PEX and LSD per torrent" is not part of 1.2.2.0 release

### ISSUE THREAD

**Issue by gunjanvishwakarma** [frostwire/frostwire-jlibtorrent#227]
TorrentFlags.java does not contain field DISABLE_DHT, DISABLE_LSD, DISABLE_PEX

**Comment by gubatron** [comment]
it's now part of 1.2.3

https://github.com/frostwire/frostwire-jlibtorrent/commit/ea10db85bbf65b78c0d05252c813d844efba97dc

Cheers!
