### ISSUE TITLE
Some issues with POSIX wrapper

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#228]
Hi. I know that your projects were split, but I think that these are common problems for everyone:
 - [[Android][POSIX wrapper] Native crash if open() function returns -1](https://github.com/aldenml/libtorrent4j/issues/52)
 - [libtorrent doesn't call remove() in POSIX wrapper](https://github.com/aldenml/libtorrent4j/issues/45)
 - [[TorrentBuilder] Incorrect work with Storage Access Framework](https://github.com/aldenml/libtorrent4j/issues/47)
 - [[TorrentBuilder] crash when creating a large torrent with POSIX wrapper](https://github.com/aldenml/libtorrent4j/issues/48)
 - [[Android] An app with POSIX wrapper crashes if launched in debug mode](https://github.com/aldenml/libtorrent4j/issues/49)
 - [[Android][POSIX wrapper] Periodic `Try again` (code 11) error during downloading](https://github.com/aldenml/libtorrent4j/issues/58)

Please see `master` branch of the app for example of usage: https://github.com/proninyaroslav/libretorrent/tree/master. If necessary, I can create a separate branch with `frostwire-jlibtorrent` instead of `libtorrent4j`

The main code that can help you navigate:
 - [core/system/LibTorrentSafAdapter.java](https://github.com/proninyaroslav/libretorrent/blob/2.0-beta/app/src/main/java/org/proninyaroslav/libretorrent/core/system/LibTorrentSafAdapter.java) - a POSIX wrapper class.
 - [core/system/SafFileSystem.java](https://github.com/proninyaroslav/libretorrent/blob/2.0-beta/app/src/main/java/org/proninyaroslav/libretorrent/core/system/SafFileSystem.java) - used to work with SAF, for example in POSIX wrapper.
 - [core/TorrentBuilder.java](https://github.com/proninyaroslav/libretorrent/blob/2.0-beta/app/src/main/java/org/proninyaroslav/libretorrent/core/TorrentBuilder.java) - a wrapper for `org.libtorrent4.TorrentBuilder` class.
 - [ui/createtorrent/CreateTorrentViewModel.java](https://github.com/proninyaroslav/libretorrent/blob/2.0-beta/app/src/main/java/org/proninyaroslav/libretorrent/ui/createtorrent/CreateTorrentViewModel.java) - a view model logic that uses `TorrentBuilder` wrapper.
 - [core/model/session](https://github.com/proninyaroslav/libretorrent/tree/2.0-beta/app/src/main/java/org/proninyaroslav/libretorrent/core/model/session) - implementation of `org.libtorrent4.SessionManager`.

**Comment by proninyaroslav** [comment]
@gubatron 
Why did you close the issue? These issues are relevant to this day, although they were opened in another repository.

**Comment by gubatron** [comment]
a lot has changed with android 11 and 12

**Comment by proninyaroslav** [comment]
@gubatron 
Much has been fixed, or is there a much that cannot be fixed?

**Comment by proninyaroslav** [comment]
You are using posix_wrapper in the frostwire app, but it makes little sense if it doesn't work as expected. You have to do something about it.

**Comment by gubatron** [comment]
not sure what you mean by "doesn't work as expected", downloads writes and reads just fine on all android versions.
