### ISSUE TITLE
android 11  Unable to download？

### ISSUE THREAD

**Issue by XiongKe94** [frostwire/frostwire-jlibtorrent#239]
Seed no problem

**Comment by XiongKe94** [comment]
Depository directory data/data/packname/files, does not require permissions

**Comment by master255** [comment]
@XiongKe94 11 Android - not yet in Android Studio. Why run ahead of the locomotive?
![Снимок](https://user-images.githubusercontent.com/5380115/93136125-16941000-f6e4-11ea-811a-120b8999a87f.PNG)

**Comment by gubatron** [comment]
Android R is Android 11. When you install it and check the About, it says Android 11.

**Comment by gubatron** [comment]
<img width="703" alt="Screen Shot 2020-09-14 at 9 42 07 PM" src="https://user-images.githubusercontent.com/163977/93162966-28b98280-f6d3-11ea-9260-8baffa6ecb3d.png">
<img width="703" alt="Screen Shot 2020-09-14 at 9 43 22 PM" src="https://user-images.githubusercontent.com/163977/93163049-5d2d3e80-f6d3-11ea-82db-242be4d069d5.png">

**Comment by gubatron** [comment]
That was running with new jlibtorrent 1.2.10.0

**Comment by gubatron** [comment]
multiple downloads and seeding
<img width="703" alt="Screen Shot 2020-09-14 at 9 46 52 PM" src="https://user-images.githubusercontent.com/163977/93163243-d7f65980-f6d3-11ea-9c41-ea7044e213cf.png">

But nothing like testing with a real device

**Comment by XiongKe94** [comment]
Thank you very much
