### ISSUE TITLE
 signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by XiongKe94** [frostwire/frostwire-jlibtorrent#244]
`
10-09 11:12:18.460 8346-9113/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 9113 (trix.arya.debug)

10-09 11:12:18.565 195-195/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-09 11:12:18.565 195-195/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
10-09 11:12:18.565 195-195/? A/DEBUG: Revision: '11'
10-09 11:12:18.565 195-195/? A/DEBUG: ABI: 'arm'
10-09 11:12:18.565 195-195/? A/DEBUG: pid: 8346, tid: 9113, name: trix.arya.debug  >>> com.apkmatrix.arya.debug <<<
10-09 11:12:18.565 195-195/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
10-09 11:12:18.586 195-195/? A/DEBUG:     r0 00000000  r1 00000000  r2 94cf9900  r3 9c91e02d
10-09 11:12:18.586 195-195/? A/DEBUG:     r4 987c6300  r5 92e6dc94  r6 00000001  r7 00000001
10-09 11:12:18.587 195-195/? A/DEBUG:     r8 94cf95b8  r9 00000000  sl 94cf95d8  fp 9493f558
10-09 11:12:18.587 195-195/? A/DEBUG:     ip 9303c2dc  sp 9493f538  lr 92e6ddd0  pc 92e75ba8  cpsr 200d0010
10-09 11:12:18.588 195-195/? A/DEBUG: backtrace:
10-09 11:12:18.588 195-195/? A/DEBUG:     #00 pc 003f5ba8  /data/app/com.apkmatrix.arya.debug-1/lib/arm/libjlibtorrent-1.2.10.0.so
10-09 11:12:20.026 195-195/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
10-09 11:12:20.026 195-195/? E/DEBUG: AM write failed: Broken pipe
`
iPhone:Android 6.0.1 LGE Nexus5
arm/libjlibtorrent-1.2.10.0.so

Occasionally crashes when downloading multiple tasks

**Comment by gubatron** [comment]
need more context and a way to reproduce the crash every time

**Comment by XiongKe94** [comment]
It's not every time it collapses, it's every once in a while
