### ISSUE TITLE
[Feature Request] Always contact all trackers

### ISSUE THREAD

**Issue by vickyoo7** [frostwire/frostwire-jlibtorrent#247]
I'm not sure if it's possible or already available but I'd like to request the feature to always contact all trackers, currently only couple of trackers are being contacted and rest are in not contacted state even after force announcing trackers are no contacted.

**Comment by gubatron** [comment]
I wonder if this is a libtorrent heuristic or if it's already an option that we might have not exposed in the Java wrapper.

Could you please check the libtorrent documentation and/or source code, look for "tracker" "announce" "announcement"

Let's see what you can find before we bother Arvid with questions.

For all we know it might just be a torrent_handle option that's already there.

**Comment by vickyoo7** [comment]
> announcement

I couldn't find any reference for contacting all trackers in libtorrent source or documentation

**Comment by gubatron** [comment]
I's suggest reading announce endpoint and announce entry to understand the timing of the announces and when they can be done
https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/announce_entry.hpp

**Comment by gubatron** [comment]
Also relevant:
https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/tracker_manager.hpp
https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/udp_tracker_connection.hpp

**Comment by vickyoo7** [comment]
> Also relevant:
> https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/tracker_manager.hpp
> https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/udp_tracker_connection.hpp

Thanks, I'll check it out and update

**Comment by gubatron** [comment]
I think what I'd do would be to write a quick program in C++ with libtorrent and put a breakpoint in the tracker_manager and announce_endpoint calls to see if all the trackers in the torrent are being called as you expect.
