### ISSUE TITLE
A little question - Peers and Seeders

### ISSUE THREAD

**Issue by carlos-hns** [frostwire/frostwire-jlibtorrent#248]
I'm new using the library and torrent, i've been reading the code examples and i've trying to understand but the question persist..I want get the amount of peers and seeders currently are in a magnet link, how i can do it?

**Comment by gubatron** [comment]
Check this out Carlos
https://github.com/frostwire/frostwire/blob/master/desktop/src/com/frostwire/gui/components/transfers/TransferDetailPeers.java

**Comment by gubatron** [comment]
Also, on the regular transfer's table, you can checkout how the dataline fills up the number of connections/seeders

Here
https://github.com/frostwire/frostwire/blob/master/desktop/src/com/frostwire/gui/bittorrent/BTDownloadDataLine.java

And here
https://github.com/frostwire/frostwire/blob/master/desktop/src/com/frostwire/gui/bittorrent/BTDownloadMediator.java
