### ISSUE TITLE
DHT and PEX features enabled by default?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#25]
Hey, so I'm using the frontpage example, or here: https://github.com/frostwire/frostwire-jlibtorrent/blob/a367e8f845f501c533ceaf33cf44ebea814198d0/src/com/frostwire/jlibtorrent/demo/DownloadTorrent.java

Are the DHT and PEX features are enabled by default? Am I getting all the peers I should be? 

Does anyone know of a more complicated downloader example that has these features?

**Comment by aldenml** [comment]
We enable the default plugins (including DHT and PEX), so you are getting all the peers and info hashes you need. If you want to look for a more complicate use of this API, take a look at https://github.com/frostwire/frostwire-common/blob/master/core/com/frostwire/bittorrent/BTEngine.java

**Comment by tchoulihan** [comment]
That's pretty much what I needed, thanks @aldenml .l
