### ISSUE TITLE
No file is created while downloading

### ISSUE THREAD

**Issue by MCrissDev** [frostwire/frostwire-jlibtorrent#251]
Hello,

For some torrents, seems that even if the progress changes, there is no file created:

 public TorrentInputStream getVideoStream() throws FileNotFoundException {
        File file = getVideoFile();
        TorrentInputStream inputStream = new TorrentInputStream(this, file);
        torrentStreamReferences.add(new WeakReference<>(inputStream));
        return inputStream;
    }
This function will throw a FileNotFoundException but onStreamProgress is reporting that it is still downloading (in some cases more than 30% total file download but no file is actually created).

**Comment by gubatron** [comment]
you might want to want to share the code in `getVideoFile()`

**Comment by MCrissDev** [comment]
Hello,

This is it.

   public File getVideoFile() {
        Log.e(TAG, "getVideoFile(): torrentHandle save path = " + torrentHandle.savePath());
        return new File(torrentHandle.savePath() + "/" +
                torrentHandle.torrentFile().files().filePath(selectedFileIndex));
    }

Strange thing it is that this issue is maybe 80% reproducible. The same code in 20% of the times creates that file.

**Comment by gubatron** [comment]
have you checked that the pieces for that file were downloaded? perhaps you
are trying to open a file in the torrent that's not there yet

**Comment by MCrissDev** [comment]
The torrent contains just 1 single file so I doubt that is the case :)

**Comment by gubatron** [comment]
sounds like you haven't really checked the pieces are there.

libtorrent will usually save those pieces elsewhere and then at the end they will be at the location you are trying to open the file.

You need to use the piece checker to make sure the torrent has finally downloaded and assembled into the target file.
