### ISSUE TITLE
BitTorrent v2

### ISSUE THREAD

**Issue by cyrillicw** [frostwire/frostwire-jlibtorrent#253]
Is BitTorrent v2 with BEP52 supported?

**Comment by gubatron** [comment]
Not yet, we'll start a branch VERY soon to provide Bittorrent v2 support.

**Comment by gubatron** [comment]
If you need Bittorrent V2 support asap, you can try our sister fork project [libtorrent4j](https://github.com/aldenml/libtorrent4j), however this project does not support (out of the box) file system integration with Android.

**Comment by cyrillicw** [comment]
Great!
