### ISSUE TITLE
JLibtorrent 1.2.3.0 crashes the app with Process exited due to signal (4) error on some Devices

### ISSUE THREAD

**Issue by pillaryang** [frostwire/frostwire-jlibtorrent#256]
ABI: 'arm'
Timestamp: 2021-02-06 21:25:33+0530
pid: 9416, tid: 9416, name: .vidmate:remote  >>> com.nemo.vidmate:remote <<<
uid: 10278
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xbf77a548 (*pc=0xec510f1e)
    r0  0000003f  r1  ffcaea54  r2  00000030  r3  d58a3820
    r4  d589e238  r5  00000000  r6  da3f9b34  r7  00000000
    r8  f25ae944  r9  e1675600  r10 f25adc2c  r11 ffcaea30
    ip  bf97634c  sp  ffcaea10  lr  bf7c9fb0  pc  bf77a548

backtrace:
    NOTE: Function names and BuildId information is missing for some frames due
    NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 003d2548  /data/user/0/com.nemo.vidmate/files/applibs/libjlibtorrent_1230.so

**Comment by pillaryang** [comment]
This crash occurs frequently on mtk6771 platform.

**Comment by gubatron** [comment]
please test with the new jlibtorrent 1.2.14

**Comment by gubatron** [comment]
closing for now, re-open if crash still happens with 1.2.14.x+ and submit full backtrace if problem still occurs.
