### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by Rubydesic** [frostwire/frostwire-jlibtorrent#257]
The discord link is to a discord *channel*, but the link needs to be an *invite* (discord.gg/xxxxx), otherwise only people who have already joined the group will be able to view it.

**Comment by gubatron** [comment]
any clue on how to make a link that doesn't expire?
![Uploading Screen Shot 2021-04-12 at 4.02.46 PM.png…]()

**Comment by gubatron** [comment]
<img width="282" alt="Screen Shot 2021-04-12 at 4 02 46 PM" src="https://user-images.githubusercontent.com/163977/114468390-a2054f00-9ba8-11eb-86f4-58dd7252c9b5.png">

any clue on how to make a link that doesn't expire?

Can you try going through frostwire.com/chat and see if that works for you?

**Comment by gubatron** [comment]
This is the invite link we have there
https://discord.gg/CKFmYcJ
Perhaps that doesn't expire. please let me know if it works for you, then I can put that one here on the readme

**Comment by Rubydesic** [comment]
To make a link that doesn't expire, you need to press the "edit invite link" hyperlink. Here is one I made: 

https://discord.gg/8nWfSGhNdX

**Comment by gubatron** [comment]
Thank you Rubydesic, link updated in the readme
