### ISSUE TITLE
LinkageError - GLIBC_2.27 not found

### ISSUE THREAD

**Issue by rpithadia25** [frostwire/frostwire-jlibtorrent#260]
Hey @aldenml,

I was trying to run the 1.2.11.0 version on Linux and saw the following exception:
java.lang.UnsatisfiedLinkError: libjlibtorrent-1.2.11.0.so: /lib64/libm.so.6: version `GLIBC_2.27' not found.

I'm running the Oracle Linux Server 7.7 x86_64
Its running GLIBC 2.17

Is there a particular version of jlibtorrent I can use?

**Comment by aldenml** [comment]
Hi @rpithadia25 I don't maintain binaries in this project (fyi I work in a fork at https://github.com/aldenml/libtorrent4j)

**Comment by rpithadia25** [comment]
Thanks for the response @aldenml.

Hey @gubatron, Could you please advice on what version I can use?

**Comment by gubatron** [comment]
try 1.2.13, it should be built with an older glib on a Docker image we now provide.
https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.13.0

**Comment by rpithadia25** [comment]
Hey @gubatron,

Thanks for getting back :)
I was going through the docker file and couldnt find a way to provide the glibc version. I'm assuming its part of g++? (Sorry I have limited knowledge of C/C++ :) )
Could you please let me know which version needs to be changed while building?

Appreciate your help!

**Comment by gubatron** [comment]
The Dockerfile uses an old instance of ubuntu 18.x so that the g++ and
glibc libraries are old enough to not break compatibility with most old
Linux versions out there.
