### ISSUE TITLE
Android/Windows binaries problem

### ISSUE THREAD

**Issue by drakonkat** [frostwire/frostwire-jlibtorrent#263]
Hi,
i cannot make the library work in an android project, or windows too. I cannot understand the binaries logic probably

I have tried on windows to make a simple main program and simply import the dependency from maven, on android i simple imported from gradle the right architecture but in every case i get "Look for your architecture binary instructions at" if there is some guide i will appretiate 

thanks a lot

**Comment by gubatron** [comment]
You need to have 2 jars:
 - the jlibtorrent.jar (java classes)
 - the jlibtorrent-<architecture>.jar (with the shared binary libraries)
 
 You get them here:
 https://github.com/frostwire/frostwire-jlibtorrent/releases
