### ISSUE TITLE
Dramatic increase in size android-x86_64

### ISSUE THREAD

**Issue by Advdman** [frostwire/frostwire-jlibtorrent#264]
From 1.2.14.1 size of android-x86_64.jar has increased 10 times! What happened?

**Comment by gubatron** [comment]
android 11 ridiculous networking requirements happened.

**Comment by Advdman** [comment]
please, see screenshot. From 1.2.14.1 size of android-x86_64.jar has increased 10 times!
![image](https://user-images.githubusercontent.com/94684928/143044935-7e172955-8098-401c-9e76-6faddbfcc764.png)

**Comment by gubatron** [comment]
thank you for clarifying, will check, maybe I left debug symbols in there.
Will revise the android x86_64 build.

**Comment by gubatron** [comment]
![Screen Shot 2021-11-23 at 11 13 23 AM](https://user-images.githubusercontent.com/163977/143081003-4ea8e4fa-75be-44eb-8faa-f13514ff0508.png)

Thank you @Advdman

Uploaded a new binary for [`android x86_64`](https://github.com/frostwire/frostwire-jlibtorrent/releases/download/release%2F1.2.14.2/jlibtorrent-android-x86_64-1.2.14.2.jar) back to only `2.66 MB`

![Screen Shot 2021-11-23 at 11 14 52 AM](https://user-images.githubusercontent.com/163977/143081227-253e38ef-f221-4db3-8a44-4f68876281df.png)

**Comment by Advdman** [comment]
thanks!!!

вт, 23 нояб. 2021 г. в 21:15, Angel Leon ***@***.***>:
