### ISSUE TITLE
Force recheck crashing for finished torrent

### ISSUE THREAD

**Issue by pratik-pattanaik** [frostwire/frostwire-jlibtorrent#267]
Calling force recheck on a finished torrent crashes with the following error log in version 1.2.14.2. Wasn't happening in version 1.2.0.6.

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa8 in tid 22296 (AsyncTask #3)`

**Comment by gubatron** [comment]
Thank you for the report.
However, we need a much more detailed crashlog to see where this is happening.

New libtorrent update is going to be merged very soon and this might go away, plenty of fixes have been included in libtorrent.

**Comment by pratik-pattanaik** [comment]
Thanks for reverting back.
I'm only getting this one line in the crashlog when running on an Android 11 arm64 device. I'll try tinkering with the build to get more native logs.

**Comment by gubatron** [comment]
please test with 1.2.15.1

**Comment by pratik-pattanaik** [comment]
Hi,

The latest release fixed the issue. Thanks !
