### ISSUE TITLE
Download issues in Samsung Galaxy devices

### ISSUE THREAD

**Issue by pratik-pattanaik** [frostwire/frostwire-jlibtorrent#271]
There appears to be a downloading issue with Samsung Galaxy devices, particularly A31 & A32 for v1.2.15.1 running Android 10/11. Too many users using these devices are complaining of 'nothing downloads' after updating to the latest version which is running jlibtorrent 1.2.15.1. These are arm64-v8a devices with Mediatek chipsets. I'm unable to reproduce the issue so far, as it downloads perfectly on Pixel 2 carrying Android 11.

**Comment by gubatron** [comment]
thanks for bringing this up, if you get a full tracelog we'll be able to investigate together

**Comment by pratik-pattanaik** [comment]
I'm not getting these issues in any of my development devices, but I'm pretty sure there's something wrong with the newer libtorrent versions. My ratings plummeted right after making an update which included v1.2.14.2, with the negative reviews complaining about nothing being downloaded. It doesn't happen to everyone, but to those it does, even Ubuntu distributions don't get downloaded (as per my discussions with users). I then made a beta update with v1.2.15.1 but the issue still persists for some users. 

Is there a patch I can apply to v1.2.0.6 to make it work with Android 11 ? 1.2.0.6 crashes if I target Android 11, probably due to using netlink sockets. If I at least make a stable update, I'll be able to investigate the issue with the newer libtorrent versions on the side.

**Comment by gubatron** [comment]
>Is there a patch I can apply to v1.2.0.6 to make it work with Android 11 ? 
No, Android 11+ is a bitch with restrictions.

**Comment by gubatron** [comment]
I'm getting close to a new libtorrent build, hopefully these unknown/unspecified issues will be resolved.
Closing for now, stay alert with our commits and upcoming releases.

**Comment by pratik-pattanaik** [comment]
Hi ! I did not find the issue when I used the [libtorrent4j wrapper](https://github.com/aldenml/libtorrent4j) version 2.0.5-24. Perhaps this can give a lead for the issue ? I've tested with Samsung Galaxy A31.

**Comment by qyzhaojinxi** [comment]
Maybe It's the same question like I met on oppo reno4 pro with android 11. I test it with libretorrent based libtorrent4j on the same device and it works well.

**Comment by qyzhaojinxi** [comment]
If you don't have any devices with problem. You can send me the new apk and I will be glad to test it.

**Comment by pratik-pattanaik** [comment]
You can also test it on Samsung Galaxy A31 using Samsung Remote Test Lab for free.

**Comment by qyzhaojinxi** [comment]
@pratik-pattanaik That's a good idea. I also often test samsung devices with this. https://developer.samsung.com/remotetestlab/deviceList.action?os=101
