### ISSUE TITLE
dhtNodes Always 0

### ISSUE THREAD

**Issue by lqh995204185** [frostwire/frostwire-jlibtorrent#274]
It was good before. The code hasn't changed. I can't get it recently。dhtNodes Always 0

**Comment by gubatron** [comment]
Please try new jlibtorrent 1.2.16.0
https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.16.0

**Comment by qyzhaojinxi** [comment]
Hi, I test 1.2.16.0.jar. And it didn't work on all my test device include android11 and android12. No speed, no peers,  no dht contacts.

**Comment by gubatron** [comment]
I've just confirmed the same, I'll be deleting those android jars and uploading new ones, I believe there was a patch missing in the build.

Once I test and they work for me I'll upload the new binaries and will provide MD5 hashes for you to check you have the new ones.

Thank you

**Comment by gubatron** [comment]
@qyzhaojinxi please try again, just uploaded [new android jars](https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.16.0)
```
MD5 hashes
e5a831edc666ad7daed368d7a97deaf4  jlibtorrent-android-arm-1.2.16.0.jar
9870ac626a0663245fd93bf1a2aa26ab  jlibtorrent-android-arm64-1.2.16.0.jar
7a8da00a9e26f769ef27ed1e7fdb565b  jlibtorrent-android-x86-1.2.16.0.jar
1a5095c052ae0d17beff397d740953f8  jlibtorrent-android-x86_64-1.2.16.0.jar
```

**Comment by gubatron** [comment]
![Screenshot_20220422-120406](https://user-images.githubusercontent.com/163977/164770292-9e2c85ef-a64b-4986-86d7-9120371dae59.jpg)
![Screenshot_20220422-120342](https://user-images.githubusercontent.com/163977/164770295-7aa4898c-0ca5-496a-8478-ff60852fce04.jpg)

**Comment by qyzhaojinxi** [comment]
@gubatron Thank you. I will try the new ones.

**Comment by qyzhaojinxi** [comment]
@gubatron Hi, thak for your fix. I have tested the new jar files and they worked well on my devices.
But they still don't work on the OPPO Reno 4 pro. It's just like the last version and no speed, no peers, no dht contacts.

**Comment by igor-rif-shevchenko** [comment]
@gubatron @qyzhaojinxi @lqh995204185 I think I have the same issue (1.2.16.0). Some users reported that nothing downloads.
I can't reproduce it on my devices. Several users had Samsung Galaxy but I've tried about 10 devices in Samsung Remote Test Lab and coudn't reproduce that issue.
I got logs from one of the users and I've noticed that there is no ListenSucceededAlert, ListenFailedAlert, ExternalIpAlert, LsdPeerAlert, PeerConnectAlert, DhtBootstrapAlert alerts.

**Comment by igor-rif-shevchenko** [comment]
This seems to be related https://github.com/frostwire/frostwire-jlibtorrent/issues/271

**Comment by qyzhaojinxi** [comment]
@igor-rif-shevchenko Yes, I think it's the same problem. I can reproduce it on my friend's OPPO Reno 4 pro. It didn't get any alerts. I try to change target 30 to 29 and then worked well. So I think it's about netlink socket and  ifaddr sockets. Some devices's kernel are different with others.

**Comment by qyzhaojinxi** [comment]
Hi, is there any solution for this problem ?  There was  quit a lot of users meeting this problem.  The dhtNodes is always 0.

**Comment by igor-rif-shevchenko** [comment]
I can confirm, still getting reports that nothing downloads...

**Comment by ivan1986** [comment]
can confrm too
new lib, md5 same, sdk 29
not download

**Comment by igor-rif-shevchenko** [comment]
Hi @gubatron , I see that the ticket mentioned above (https://github.com/popcorn-time-ru/popcorn-android/pull/1)
says that it's working fine in libtorrent4j, maybe there is some clue how it was fixed there?

**Comment by qyzhaojinxi** [comment]
@igor-rif-shevchenko  I'm not sure if it's the same problem.

I can reproduce it on my friend's OPPO Reno 4 pro. It didn't get any alerts and any speed. I try to change target 30 to 29 and then worked well. So I think it's about netlink socket and ifaddr sockets. Some devices's kernel are different with others.

And I test liretorrent app with libtorrent4j on the same device. It works well.

**Comment by igor-rif-shevchenko** [comment]
That's the point, if it works with libtorrent4j then we can see how it is different from frostwire-jlibtorrent.

**Comment by gubatron** [comment]
try adding this to bootstrap your connection to the DHT on your SettingsPack object before creating the SessionParams object

```
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.silotis.us:6881");
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.bittorrent.com:6881");
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "dht.transmissionbt.com:6881");
```

**Comment by igor-rif-shevchenko** [comment]
@gubatron but those are already added inside SessionManager, am I mising something?

```
    private static String dhtBootstrapNodes() {
        StringBuilder sb = new StringBuilder();

        sb.append("dht.libtorrent.org:25401").append(",");
        sb.append("router.bittorrent.com:6881").append(",");
        sb.append("router.utorrent.com:6881").append(",");
        sb.append("dht.transmissionbt.com:6881").append(",");
        // for DHT IPv6
        sb.append("router.silotis.us:6881");

        return sb.toString();
    }
```

**Comment by qyzhaojinxi** [comment]
> try adding this to bootstrap your connection to the DHT on your SettingsPack object before creating the SessionParams object
> 
> ```
> sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.silotis.us:6881");
> sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.bittorrent.com:6881");
> sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "dht.transmissionbt.com:6881");
> ```

If this code is  necessary? Which one is correct comparing with the code in dhtBootstrapNodes?

**Comment by igor-rif-shevchenko** [comment]
@gubatron do you have any idea what's going on? I keep getting feedback that nothing downloads and just can't do anything about it...

**Comment by gubatron** [comment]
will look at this on the next update, which could be as soon as this week. I'm on the road now, will be back home by Wednesday.

My guess is that the patch we did for ifnet sockets doesn't work with some android kernels that the maintainers decided to not do as it was dictated by the android project, so the patch ends up breaking connectivity as it tries to use the wrong type of socket

**Comment by igor-rif-shevchenko** [comment]
@gubatron any news? Does new 1.2.17.0 version have some changes related?

**Comment by gubatron** [comment]
@igor-rif-shevchenko please give it a try and see if it works now

**Comment by igor-rif-shevchenko** [comment]
@qyzhaojinxi can you test? I don't have a device with that issue

**Comment by qyzhaojinxi** [comment]
@igor-rif-shevchenko Sorry about that I can't find the device either. But I will  use the latest verison sdk and see the difference about user feedback.

**Comment by lyxxman** [comment]
There are still such problems
