### ISSUE TITLE
Docker script Q&A

### ISSUE THREAD

**Issue by master255** [frostwire/frostwire-jlibtorrent#276]
@gubatron @aldenml I think it is a very bad idea to switch to compilation in the docker.
There is an error in the library compilation script, and as a third-party programmer I don't understand the meaning of these errors at all.
But even if I figure out what the errors are, docker is a virtual machine in my ubuntu virtual machine. And I don't have any easy tools to fix the error. In order to fix something I need to fully understand how docker works.
I used to have scripts that I could quickly edit in notepad. Now, I have to do a lot of complicated things to fix a script.
You have made things very complicated.
Here is my error and there is the Internet and in the browser this file is downloaded. And the docker can not download. There is no answer anywhere on the Internet. Maybe docker makes sense for corporate use but for compilation it is better to use regular scripts.

```
+ ./gradlew jar
Downloading https://services.gradle.org/distributions/gradle-7.3.2-bin.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)

```

**Comment by master255** [comment]
Ok. This error occurred in the Ubuntu 22 docker. In wsl Windows 11 Docker I was able to get the libraries in the docker.

**Comment by gubatron** [comment]
> I don't understand the meaning of these errors at all.

We all have to learn Docker at some point.

> You have made things very complicated.

No, it's more complicated having to have the perfect build environment, with the right libc libraries.

Docker simplifies all this, doesn't give you 100% determinism, but it gets close.

It also makes the build process faster, just building the image alone gets you the openssl and boost builds out of the way, and then you just invoke the build scripts for windows, linux and then android from a single image. macOS I build on 2 machines, one with x86_64 and another with arm64 cpus.

The same machine I use to build x86_64 mac builds and runs the Docker image no problem.

It should work 100% on an Ubuntu x86_64 host.

**Comment by master255** [comment]
@gubatron You're right. I should study Docker better. But for me, only Docker Windows 11 is acceptable. It has a friendlier interface than all the others.
That's why I need to upgrade Windows. Right now I have Windows 10, which doesn't have Docker.
It takes me about a month to update Windows. So Docker is like a toothache for me.

Right now I'm using Docker on a Windows 11 virtual machine.

**Comment by master255** [comment]
@gubatron How to do a run_swig?

**Comment by gubatron** [comment]
`./run-swig.sh` is meant to have a few environment variables set and it's invoked by the build scripts provided in the frostwire-jlibtorrent/swig folder.

If you really want to run it in the Docker image, then you must set the minimum environment variables required to be present for a build, these are them

<img width="1000" alt="Screen Shot 2022-05-02 at 1 26 14 PM" src="https://user-images.githubusercontent.com/163977/166312199-0679b757-0470-4073-b001-05ae23372422.png">

Say you want to build a linux binary:

```bash
$ ./docker_run_interactive.sh 
root@13a3e237ea6d:/# cd frostwire-jlibtorrent/swig/
root@13a3e237ea6d:/frostwire-jlibtorrent/swig# source build-utils.shinc && linux_env && common_env && ./run-swig.sh
```
<img width="1519" alt="Screen Shot 2022-05-02 at 1 36 37 PM" src="https://user-images.githubusercontent.com/163977/166313685-4993a55e-0077-4593-8652-8a1e46656e16.png">
