### ISSUE TITLE
sessionManager.stats().dhtNodes()  always 0

### ISSUE THREAD

**Issue by qichuangguo** [frostwire/frostwire-jlibtorrent#278]
sessionManager.stats().dhtNodes()

**Comment by gubatron** [comment]
can't replicate, make sure yiu have dht enabled

this works fine on FrostWire
   https://github.com/frostwire/frostwire/blob/85ee08caca8e87a8d3e1c755406f978eeac7563e/android/src/com/frostwire/android/gui/fragments/TransfersFragment.java#L475

on what operating system, device model and jlibtorrent version are you having this issue?

Is it an Android OPPO by any chance?

If so recompile with sdk 29 as your target

**Comment by qichuangguo** [comment]
Android xiaomi  
target is 29


            SessionManager sessionManager = new SessionManager();
            SettingsPack sp = new SettingsPack();
            SessionParams params = new SessionParams(sp);
            sessionManager.start(params);
            
            final CountDownLatch signal = new CountDownLatch(1);
            final Timer timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    long nodes = sessionManager.stats().dhtNodes();
                    // wait for at least 10 nodes in the DHT.
                    Log.i("===========>", "run: "+nodes);
                    if (nodes >= 10) {
                        Log.i("===========>", "run: "+nodes);
                        signal.countDown();
                        timer.cancel();
                    }
                }
            },0,1000);

**Comment by gubatron** [comment]
try adding this to bootstrap your connection to the DHT on your `SettingsPack` object before creating the `SessionParams` object

```java
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.silotis.us:6881");
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "router.bittorrent.com:6881");
sp.setString(settings_pack.string_types.dht_bootstrap_nodes.swigValue(), "dht.transmissionbt.com:6881");
```

**Comment by gubatron** [comment]
did that work @qichuangguo ?
