### ISSUE TITLE
How to merge libraries into one?

### ISSUE THREAD

**Issue by master255** [frostwire/frostwire-jlibtorrent#279]
@gubatron Alyarma alyarma! The enemies are attacking!

After upgrading Android Studio to Chipmunk, it stopped supporting different architecture libraries.
Now only single libraries are supported, which are not divided into architectures.

Almighty Gubatron, could you please write a script on how to merge all the libraries?
Perhaps Alden (@aldenml ), any ideas?

![image](https://user-images.githubusercontent.com/5380115/190299980-246ced57-6e35-4574-bf52-c50694085b69.png)

**Comment by gubatron** [comment]
Opened both the jlibtorrent project, and the frostwire project and I have no issues on our project.

![Screen Shot 2022-09-17 at 3 45 33 PM](https://user-images.githubusercontent.com/163977/190877359-c42c5f99-0687-443e-82de-305a8c2ff14e.png)


Still works fine for jlibtorrent gradle project
![Screen Shot 2022-09-17 at 3 40 48 PM](https://user-images.githubusercontent.com/163977/190877400-e98b9f48-573a-4fa2-a7ab-310b413f3aaf.png)

and for frostwire-android project
![Screen Shot 2022-09-17 at 3 44 36 PM](https://user-images.githubusercontent.com/163977/190877383-d967bdd0-e8c0-403d-afce-2c63839f1300.png)

**How are you storing the different architecture jars in your android projects?**
We simply throw all of them together inside `libs/`
![Screen Shot 2022-09-17 at 3 47 32 PM](https://user-images.githubusercontent.com/163977/190877417-184ac771-f693-4ff7-ad26-cbd743c33579.png)

jlibtorrent classes are added to the classpath by Android Studio from a single `jlibtorrent-w.x.y.z.jar` that contains no binaries, only the .class files

**Comment by master255** [comment]
Indeed. Moving the libraries to the libs directory helped.
