### ISSUE TITLE
Make frostwire-jlibtorrent available on Maven.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#28]
If anybody watching has already gone through this process any help/tips would be appreciated to get the library up there as soon as possible.

**Comment by gubatron** [comment]
First lead:
http://blog.blundell-apps.com/locally-release-an-android-library-for-jcenter-or-maven-central-inclusion/

**Comment by gubatron** [comment]
http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by aldenml** [comment]
More info for sonatype: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by tchoulihan** [comment]
I can help here, gone through this process fully, want me to post some things you need for the pom and dependencies?

For this libraries use in my project, I just had to copy the folder unfortunately, but also would've preferred it to be mavenized.

**Comment by aldenml** [comment]
Did you use gradle?

**Comment by tchoulihan** [comment]
No, I just use straight maven.

**Comment by aldenml** [comment]
Ok, we want to use gradle, but the process should be similar. Post as much as you can, we will appreciate it.

**Comment by tchoulihan** [comment]
Sure.
Main instructions are [here](http://central.sonatype.org/pages/ossrh-guide.html) but basically:

1) First create a login here, http://oss.sonatype.org/,  and a ticket to open up your package domain on sonatype

2) Add your sonatype login to your .m2/settings.xml
Looking in mine, I have:
```
<servers>
  <server>
    <id>sonatype-nexus-snapshots</id>
    <username>...</username>
    <password>...</password>
  </server>
  <server>
    <id>sonatype-nexus-staging</id>
    <username>...</username>
    <password>...</password>
  </server>
<server>
      <id>ossrh</id>
      <username>...</username>
      <password>...</password>
    </server>
</servers>
```

3) You might also have to generate a gpg keyring, but I forget if I did this just in case, or if its not necessary, so I'll leave this off for now.

4) Add some things to your pom. Here's a pom for a simple project I made recently:
https://github.com/tchoulihan/musicbrainz-tagger/blob/master/pom.xml

I think you mainly need <parent, <scm, <licenses, . Sonatype requires that you have them.

Note: normally on sonatype you have to *release* and then *drop* your repository(which includes clicking those buttons on http://oss.sonatype.org/  to actually have it accessible, but the pom I showed does this automatically with some maven plugins.


5) Run this command:
`mvn3 clean install package source:jar javadoc:jar gpg:sign deploy`

Sonatype requires the sources and javadoc for your project too.

If your project is a SNAPSHOT, it will only deploy to the snapshot directory, and users would have to add that manually. If its not a snapshot, it will deploy to *staging*, then once you drop and release it, to *maven central*.

Let me know if you have any problems.

**Comment by aldenml** [comment]
Just an update that we have some progress https://issues.sonatype.org/browse/OSSRH-16814

**Comment by tchoulihan** [comment]
Sounds good. Let me know if you need any help along the way.

**Comment by aldenml** [comment]
Done http://repo1.maven.org/maven2/com/frostwire/jlibtorrent/

**Comment by tchoulihan** [comment]
Great! Its working so far! I was going to suggest adding the maven xml/gradle to the front page, but you guys are on the ball with it already.
