### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by whistlexie** [frostwire/frostwire-jlibtorrent#285]
Crashed: Thread: SIGILL  0x00000000af1c2e48
#00 pc 0x6d3e48 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#01 pc 0x785542 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#02 pc 0x7838b6 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#03 pc 0x6aeefa libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#04 pc 0x363497 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#05 pc 0x50a662 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#06 pc 0x4ec35a libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#07 pc 0x9199 linker (BuildId: 0334f2a170d32392fcf5b93dcf7f07cf51eac2e7)
#08 pc 0xe99148d5
#09 pc 0x1cf307 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#10 pc 0x83dd libc.so (BuildId: d4889a5c02c1657103574aa7fe876a58e6575e9d)
#11 pc 0x17b81 libc.so (BuildId: d4889a5c02c1657103574aa7fe876a58e6575e9d)
#12 pc 0x4d3d32 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#13 pc 0x4d3ea6 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#14 pc 0x4d1aae libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#15 pc 0x3fb2fe libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#16 pc 0x3f4bee libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#17 pc 0x3f4e96 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#18 pc 0x65c16e libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#19 pc 0xb46ff762
#20 pc 0x3e9cf6 libjlibtorrent_12160.so (BuildId: 3392bcbf1a0ab82c859817c410ee68f33a526404)
#21 pc 0xb46ff762
#22 pc 0xe4dd libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#23 pc 0xb46ff762
#24 pc 0x99d5 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#25 pc 0xb46ff762
#26 pc 0x421207 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#27 pc 0x61d41 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#28 pc 0xb46ff75f
#29 pc 0x2e88b1 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#30 pc 0x887cb libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#31 pc 0x6ff0c4a2
#32 pc 0xe3d2cd2e
#33 pc 0xb41e662e
#34 pc 0x1751b1 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#35 pc 0xb46ff75f
#36 pc 0x6ff0c4a2
#37 pc 0xe36438c0
#38 pc 0x421207 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#39 pc 0x16ce71 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#40 pc 0xb451930e
#41 pc 0x415099 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#42 pc 0xb451976e
#43 pc 0xb451930e
#44 pc 0xb451976e
#45 pc 0xcfe libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#46 pc 0x4596 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#47 pc 0xfbb7 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#48 pc 0x414aaf libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#49 pc 0xb451976e
#50 pc 0xb4519766
#51 pc 0xb4507ddc
#52 pc 0xb4519766
#53 pc 0xb4507ddc
#54 pc 0xcfe libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#55 pc 0x4516 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#56 pc 0xfbb7 libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#57 pc 0x4128df libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#58 pc 0xb4507ddc
#59 pc 0xb4507d6a
#60 pc 0xb4507d50
#61 pc 0xb4507d6a
#62 pc 0x7284f libart.so (BuildId: 8d752fe7dc9e0fd1bbdbc4a896e810dbf72a8e50)
#63 pc 0xb4507d50

Hi，The version of jlibtorrent in my app is 1.2.16.0. Threre happend a native crash,we get it in the altas。

**Comment by gubatron** [comment]
wish we had debug symbols to make sense of this
