### ISSUE TITLE
where is the gradle script?

### ISSUE THREAD

**Issue by Jichao** [frostwire/frostwire-jlibtorrent#29]
In the readme, 
```
Building the frostwire-jlibtorrent.jar

inside the build/ folder just invoke gradle build

you will find the resulting frostwire-jlibtorrent.jar at build/build/libs/frostwire-jlibtorrent.jar.
````
But I could not find the gradle script.

**Comment by aldenml** [comment]
Unfortunately not, at some point there was a script but was removed a long time ago. We have plans to put this in maven.

**Comment by Jichao** [comment]
I need to write the gradle script by myself or find it in the git history to build the jar file since there is no binary release?

**Comment by aldenml** [comment]
You can look in the history, but I rather recommend you write a simple gradle script from scratch.

**Comment by Jichao** [comment]
Thanks for your reply, i have managed to create the jar file, and all works fine on android/mac ox yosemite.
````
/*
 Usage:
 gradle build - builds code and creates a single jar in build/libs/frostwire-jlibtorrent.jar
 gradle clean - cleans the build.
 gradle tasks - shows available tasks.
*/
apply plugin: 'java'

if (!System.getenv('ANT_HOME')?.trim()) { 
    throw new GradleException("ERROR: ANT_HOME environment variable not set.\n\n(e.g. on MacOSX: /usr/local/Cellar/ant/1.9.3/libexec\n      on Linux:  /usr/share/ant)")
}

sourceCompatibility = 1.7

sourceSets {
    main {
        java {
            srcDir '../src'
        }
    }
}

jar {
    archiveName='frostwire-jlibtorrent.jar'
    exclude('META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/*.MF')
}
````
Steps to generate this file
`git checkout $(git rev-list -n 1 HEAD -- build/build.gradle)^ -- build/build.gradle`
modify the path from `java/src` to `../src`

**Comment by aldenml** [comment]
Thank you, I probably take this as a starting point.
