### ISSUE TITLE
Cannot build 2.0 binaries

### ISSUE THREAD

**Issue by pvishnyakov** [frostwire/frostwire-jlibtorrent#290]
Hi.

Trying to build non-macos binaries on the Linux machine, cloning branch 2.0, running `cd swig && ./docker_build_binaries.sh`  and after some time getting this error:
````
Step 42/72 : RUN cd /src                && wget -nv https://dl.frostwire.com/other/swig/swig-${SWIG_VERSION}.tar.gz    && tar xzf swig-${SWIG_VERSION}.tar.gz           && cd /src/swig-${SWIG_VERSION}                 && ./configure --without-d              && make -j 8     && make install
 ---> Running in 831575bf410a
ERROR: cannot verify dl.frostwire.com's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to dl.frostwire.com insecurely, use `--no-check-certificate'.
The command '/bin/sh -c cd /src                 && wget -nv https://dl.frostwire.com/other/swig/swig-${SWIG_VERSION}.tar.gz             && tar xzf swig-${SWIG_VERSION}.tar.gz          && cd /src/swig-${SWIG_VERSION}                 && ./configure --without-d              && make -j 8     && make install' returned a non-zero code: 5
Unable to find image 'jlibtorrent-android:latest' locally
docker: Error response from daemon: pull access denied for jlibtorrent-android, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
````
Don't know what's the problem, checked dl.frostwire.com certificate - browser shows it's ok...
What may be wrong?

**Comment by master255** [comment]
You need to set up compilation on your servers. With your links.

**Comment by pvishnyakov** [comment]
What do you mean?
I just following the build instructions for win/linux/android - run commands on the machine with Docker.
However, I have modified the Dockerfile and added option `—no-check-certificate`
The building continued and stuck again on Swig - said it cannot find PCRE2 config file.

Here I don’t know what to do, I have installed (inside container) PCRE2 from repository, built it with the script from Tools folder - config file cannot be found anyway, building stops. 
And finally, if I add non-recommended option `—without-pcre`, the building finished but container has failed to start because there is no `/build.sh` inside. 

What else should I do to build it successfully?

**Comment by master255** [comment]
Obviously I'm talking about all such links:
https://dl.frostwire.com/other/swig/swig

**Comment by pvishnyakov** [comment]
Could you please extend your thought beyond just few words to be understood by an ordinary human?

**Comment by master255** [comment]
I think if you're an ordinary person, not a programmer, and can't handle even such nonsense, even after direct instruction on what to do, then it's not worth continuing.

**Comment by gubatron** [comment]
Hi, the 2.0 branch is still not ready for compilation, I'm working on it.
Still lots to fix.

**Comment by pvishnyakov** [comment]
Got it, thanks
