### ISSUE TITLE
Swig link problem

### ISSUE THREAD

**Issue by master255** [frostwire/frostwire-jlibtorrent#292]
https://github.com/frostwire/frostwire-jlibtorrent/blob/7e2d751f554e3edac2c1ae582bb22279716616e6/swig/Dockerfile#L61

Change it to https://sourceforge.net/projects/swig/files/swig/swig-${SWIG_VERSION}/swig-${SWIG_VERSION}.tar.gz

**Comment by gubatron** [comment]
that's a feature not a bug.
had issues in the past with that mirror, decided to host my own one
I'll make sure to update to the latest version in our mirror.

**Comment by gubatron** [comment]
<img width="536" alt="Screenshot 2024-07-31 at 11 32 57 PM" src="https://github.com/user-attachments/assets/b930ec00-0fc5-4e53-b74e-e436d56cf8f8">

Added the latest 4.2.x versions, hopefully this helps.

**Comment by gubatron** [comment]
SWIG_VERSION 4.2.1 bump on the 2.0 branch
https://github.com/frostwire/frostwire-jlibtorrent/commit/84a99529d4f6674cbd1272006b6d7437f62359d1

Trying not to mess with the master branch for some time, getting closer and closer to a libtorrent 2.0 compatible release
