### ISSUE TITLE
[LT 2.0] SIGSEGV in bdecode_node if the pointer is null

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#296]
I first discovered this in libtorrent4j and was trying to fix it https://github.com/aldenml/libtorrent4j/pull/244. I checked this in jlibtorrent 2.0 and the problem is reproduced here too.

When I try to call a method like `bdecode_node::dict_find_list_s` and if the node is not found, then the method returns a `bdecode_node` object with a null pointer inside. So, if I call any method that works with a pointer (e.g. `bdecode_node::list_size`) then it throws SIGSEGV like this:
```
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5356 (Thread-25), pid 4773 (retorrent.debug)
Cmdline: org.proninyaroslav.libretorrent.debug
```

The solution is to check the pointer and return null `bdecode_node` if the pointer is null, for methods `dict_find_*_s`, `list_at`, `dict_at_node`. But the problem is that this bug is in the auto-generated files and this will require making fixes in the swig files

**Comment by gubatron** [comment]
Looks like here's how you're supposed to use it. The api is supposed to return an empty node I believe
https://github.com/aldenml/libtorrent4j/pull/274/files#diff-e6d40af5f071fb7cbc13ca15b2d656a362f07c8aa39556ce4ad4eb346cd050b3R47

**Comment by gubatron** [comment]
Last night I added [some higher level wrappers](https://github.com/frostwire/frostwire-jlibtorrent/commit/c0e46072c9000317001cbed06abf6b88461fb192#diff-907cf137ed946d4599a20b55611a9c1560aabf8b4a6b7604701074308a0e5fb7) [`hasList`,`getList`, `hasDict`, `getDict`, `hasInt`, `getInt`, `hasString`, `getString`] to `BDecodeNode` so users don't have to figure all that stuff out and use getters that return `null` without crashing.

Then added them to the `BDecodeReadTest::testReadNone()` @aldenml wrote for libtorrent4j, but here on jlibtorrent.
<img width="602" alt="Screenshot 2024-10-23 at 8 20 28 AM" src="https://github.com/user-attachments/assets/e827d952-21c8-4076-9813-b5e5aee13b28">
