### ISSUE TITLE
[LT 2.0] Add `AnnounceEndpoint:swig` and `peer_info::get_pieces` methods

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#297]
I'm currently migrating my app to jlibtorrent and have encountered a couple of methods that are missing from jlibtorrent:
 - `AnnounceEndpoint:swig`
- `peer_info::get_pieces`

I'm using `announce_endpoint` to get `getLast_error` and `get_pieces` is used to calculate torrent availability and relevance value.
I'll try to figure out swig and maybe I'll be able to add these methods and make a PR.

**Comment by aldenml** [comment]
why... :(

I know I know...lacks of update. Is there something I can do for you keep using `libtorrent4j`?

**Comment by proninyaroslav** [comment]
@aldenml 
Hi. I didn't mean to upset you. I'm very grateful for your work, and I would like you to continue releasing updates, but without updates I don't see any other options. For example, 
1. The problem with `bdecode_node` hasn't been solved.
2. Also, since the beginning of 2023, users have started to face mass bans of incoming peers https://github.com/arvidn/libtorrent/issues/7734. I don't know what the reason is, maybe it's fixed in upstream, but without updates from upstream I don't even have a chance to check it.
3. I would like to have a working `posix_wrapper` again for SAF, or the ability to write a custom `disk_interface` to interact with SAF https://github.com/aldenml/libtorrent4j/issues/269

**Comment by aldenml** [comment]
@proninyaroslav I understand and I'm also grateful for you picking `libtorrent4j` early on. The 2) could be difficult to figure out, and yes, maybe that's a problem only in `master` upstream. Hopefully, I can release an update before you complete the migration :)

**Comment by master255** [comment]
On version 1.2 I don't have any problems. Maybe the problem is not bugs, but updates.

**Comment by gubatron** [comment]
please send 2 separate PRs, each on a separate feature branch so I can easily test.

Also notice we are now on the libtorrent 2, if this is for 1.2 make sure to create the branch off of the 1.2 branch (which we more likely not be maintaining, volunteers for that branch welcome)
