### ISSUE TITLE
Need to set the auto_manage_interval for session_settings

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#30]
I need to be able to set the automanage interval, shown here, but I don't see a method for it in SessionSettings.

http://www.libtorrent.org/reference-Settings.html#session_settings

**Comment by gubatron** [comment]
We've not directly exposed everything on the higher level Java API. However, you can always use [`.getSwig()`](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/com/frostwire/jlibtorrent/SessionSettings.java#L24) on the `SessionSettings` object, and you should be able to access the:

`[setAuto_manage_interval(int value)](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/com/frostwire/jlibtorrent/swig/session_settings.java#L567)`
and
[`getAuto_manage_interval() `](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/com/frostwire/jlibtorrent/swig/session_settings.java#L571)
methods of the [`session_settings`](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/com/frostwire/jlibtorrent/swig/session_settings.java) swig class.

**Comment by aldenml** [comment]
This has changed substantially in libtorrent master (now using settings_pack) but we will maintain this stub for a while. I will put this flag (unless you want to send an easy PR).

**Comment by gubatron** [comment]
settings_pack stuff hasn't been merged to our master?

**Comment by aldenml** [comment]
No, it is in our libtorrent-trunk branch until libtorrent(master) becomes the stable one.

**Comment by gubatron** [comment]
i guess that means for now the `.getSwigh().setAuto_manage_inteval(int)` should work then.
I'd add that flag after libtorrent-trunk changes become effective, if it's even necessary as I understand things will work differently then.

**Comment by aldenml** [comment]
Sure

**Comment by tchoulihan** [comment]
Found it, thanks guys. I'll close this out.
