### ISSUE TITLE
session.AddTorrent flags

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#32]
Based on arvid's recommendations, I need to set `seed_mode=true` on a torrent added to the session.

I see the addTorrentParams method, but wouldn't it be better to use it like so?
```java
TorrentHandle torrent = session.addTorrent(File torrent, File saveDir, File saveResumeData, Set<TorrentFlagEnum> flags);
```

If not, could you give me an example of how to set those parameters while adding a torrent with swig?

**Comment by aldenml** [comment]
Take a look at https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L846

Create one for you (getSwig() is public) and add:
``` flags &= ~add_torrent_params.flags_t.flag_auto_managed.swigValue();```

I don't like a set of a java enum, but I will research how to improve the API in the java layer. We left getSwig() to allow for all sort of low level coding like this case.

**Comment by tchoulihan** [comment]
Thanks, this helps a lot.

**Comment by gubatron** [comment]
@tchoulihan
TIP: if you ever need to pass the getSwig() reference to another object, try passing a copy of it instead. It happens that the GC may leave you with an invalid reference which often leads to a crash.

**Comment by tchoulihan** [comment]
I'll keep this in mind.

**Comment by tchoulihan** [comment]
Sorry to ask about this again, but I'm trying to create a custom add_torrent method where by default, auto_manage is false, and seed_mode is true. 

Setting the flags is confusing, because in the settings you appear to be doing bitwise inversions and ORs, instead of setting multiple flags. 

Wouldn't this line in your code be **turning off** automanage, since its using ~(or invert bits)?
https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L942


Would this be correct for me then?
```java
// always set automanage to false
		add_torrent_params p = add_torrent_params.create_instance();
		TorrentInfo ti = new TorrentInfo(torrentFile);
		String savePath = outputParent.getAbsolutePath();
		p.setTi(ti.getSwig().copy());
		p.setSave_path(savePath);
		p.setStorage_mode(storage_mode_t.storage_mode_sparse);
		long flags = p.getFlags();
		if (saveResumeData.exists()) {
			byte[] data;
			try {
				data = Files.readAllBytes(Paths.get(saveResumeData.getAbsolutePath()));
				p.setResume_data(Vectors.bytes2char_vector(data));
				flags |= add_torrent_params.flags_t.flag_use_resume_save_path.swigValue();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

		// Set seed mode
		p.setFlags(flags);
		if (seedMode) {
			flags &= ~add_torrent_params.flags_t.flag_seed_mode.swigValue();
		}

		// Turn off automanage
		flags &= ~add_torrent_params.flags_t.flag_auto_managed.swigValue();


		TorrentHandle torrent = new TorrentHandle(session.getSwig().add_torrent(p));
```

**Comment by gubatron** [comment]
yes, I believe the intention there is to turn off the automanage.

```
>>> f = 0b111
>>> f &= ~0b001
>>> bin(f)
'0b110' # bit is turned off
>>> f &= ~0b001
>>> bin(f)
'0b110' # bit remains turned off
```

**Comment by aldenml** [comment]
I think you can always call TorrentHandle::setAutoManaged, https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/TorrentHandle.java#L297

**Comment by tchoulihan** [comment]
I just figured this out. 
So I converted the long to a binary string, figured out which enum_flags_t were turned on by default. 

Here are what the bits do: 
http://libtorrent.org/reference-Session.html#add_torrent_params

It turns out auto_managed is turned on by default, so you have to do:
`flags -= add_torrent_params.flags_t.flag_auto_managed.swigValue();` to turn it off.

And to turn on the others(that aren't already on by default), you can just add the swig values like so:
`flags += add_torrent_params.flags_t.flag_seed_mode.swigValue();`

Here are the default flags when you run `p.getFlags()`: 
`default flags = 10001001110000`

@aldenml , I actually needed to turn off automanage as I add the torrents, because if you try turning it off afterwards, libtorrent still might have paused them before it receives that message for some reason.

**Comment by gubatron** [comment]
>It turns out auto_managed is turned on by default, so you have to do:
flags -= add_torrent_params.flags_t.flag_auto_managed.swigValue(); to turn it off.

yeah, which is what we do.
