### ISSUE TITLE
Add libtorrent benchmarking to jlibtorrent

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#33]
Would it be possible to add libtorrent's session benchmarking logs as shown [here](http://www.libtorrent.org/tuning.html#benchmarking) ? It would really help to diagnose any problems with jlibtorrent in general.

**Comment by aldenml** [comment]
Just to let you know that I'm waiting for this: https://github.com/arvidn/libtorrent/pull/65

However, the doc you linked is obsolete and probably the tools (in python) too.

**Comment by aldenml** [comment]
Ok, now libtorrent is compiled with `<disk-stats>on` and to effectively enable it you need to do like https://github.com/frostwire/frostwire-jlibtorrent/blob/million-torrents/src/main/java/com/frostwire/jlibtorrent/demo/DownloadTorrent.java#L22

If you want to test, you will need to compile the linux binary yourself until I solve the maven publishing issue.

**Comment by tchoulihan** [comment]
Thanks! I'm out for a few days, but will compile and test this as soon as I get back.

**Comment by tchoulihan** [comment]
Hey @aldenml , I'd like to start testing with disk stats on, let me know the best way to do this. If I need to compile my own binary, which build-linux.sh script I should use(The ones in the swig/ folder don't work).

**Comment by aldenml** [comment]
Hi @tchoulihan, the good thing about the new binary is that it's already compiled with that flag, just call `default_storage.disk_write_access_log(true);` at the beginning and `default_storage.disk_write_access_log(false);` at the end. See https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/demo/DownloadTorrent.java#L22

After that, you should end with a file called "file_access.log" in your working directory.

If still you want to build the binary, let me know what problems are you getting in another ticket.

**Comment by tchoulihan** [comment]
Hey @aldenml, should I take this up with arvid? I'm trying to run the parse_disk_log.py on the file, and its not working. Is that the right test? I just guessed that that python file is the right one, but there are other python tests there, but none of them apparently process a file_access.log file.

```
$: python parse_disk_log.py file_access.log 
Traceback (most recent call last):
  File "parse_disk_log.py", line 43, in <module>
    new_time = long(l[0])
ValueError: invalid literal for long() with base 10: ''
```

**Comment by aldenml** [comment]
Yes, you should solve that with @arvid. I don't know anything about it to help you.

**Comment by tchoulihan** [comment]
Gotcha.
