### ISSUE TITLE
SIGSEGV on Android

### ISSUE THREAD

**Issue by sv244** [frostwire/frostwire-jlibtorrent#37]
So I tried to replace my previous version of jlibtorrent binaries and library code by the maven repositories in Gradle.

Can something be wrong with the binaries? The previous version worked perfectly and this is what's happening now:

`08-07 11:21:44.092  29229-29412/pct.droid.dev A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe02fa40 in tid 29412 (Session-alertsL)`

I first thought that it happened after I added my second listener. But it doesn't. Debugging in Android Studio tells me that some blocks are being finished. And then suddenly some alert comes (I guess, looking at the error) and the app crashes.

**Comment by sv244** [comment]
Ok, solved. I needed to update my AlertListener. Now the part where TorrentInfo is null.

**Comment by sv244** [comment]
That didn't seem to be the whole problem. I'm still getting the error, but I updated all my code.

`08-07 15:22:23.845    2398-2567/pct.droid.dev A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcaae3e20 in tid 2567 (Session-alertsL)`

And I have no idea where to search.

**Comment by aldenml** [comment]
Can you paste a longer log output? I need to see more about the stack trace.

**Comment by sv244** [comment]
```
08-07 16:09:16.843  22307-22307/pct.droid.dev A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcaae3e20 in tid 22307 (pct.droid.dev)
08-07 16:09:19.403  22307-22307/pct.droid.dev W/pct.droid.dev﹕ type=1701 audit(0.0:172): auid=4294967295 uid=10243 gid=10243 ses=4294967295 subj=u:r:untrusted_app:s0 reason="memory violation" sig=11
```

This is all I get.

**Comment by aldenml** [comment]
With version of jlibtorrent are you working with?

**Comment by sv244** [comment]
1.1.0.2

**Comment by aldenml** [comment]
Yesterday I found another null pointer error, it's already mergex (https://github.com/arvidn/libtorrent/pull/72). In a few hours I will release another version, maybe this fix your issue. If not, I will need more info from you. Let's see.

**Comment by sv244** [comment]
Hopefully! Thanks.

**Comment by aldenml** [comment]
@sv244 I released version 1.1.0.3, let me know if you are still getting the error.

**Comment by sv244** [comment]
:+1:

**Comment by gubatron** [comment]
sweet

**Comment by sv244** [comment]
That I'm going to try it doesn't mean it is solved.

**Comment by gubatron** [comment]
gotcha

**Comment by sv244** [comment]
Nope.

`08-07 21:31:16.342  21220-21246/pct.droid.torrentstreamer.sample A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5e76f142 in tid 21246 (Session-alertsL)`

**Comment by gubatron** [comment]
dang

**Comment by sv244** [comment]
I'll push my code to a repo.

**Comment by gubatron** [comment]
:+1:

**Comment by sv244** [comment]
https://github.com/sv244/TorrentStream-Android

**Comment by gubatron** [comment]
link(s) to file(s)?

**Comment by sv244** [comment]
Anything within https://github.com/sv244/TorrentStream-Android/tree/develop/library/src/main/java/pct/droid/torrentstream

**Comment by aldenml** [comment]
Ok, no promise on timing, I will take a close look.

**Comment by sv244** [comment]
No worries. That you will is good enough for me.

**Comment by sv244** [comment]
I also noticed that TorrentInfo is null most of the times.

**Comment by aldenml** [comment]
Ok @sv244 , in this line https://github.com/sv244/TorrentStream-Android/blob/develop/library/src/main/java/pct/droid/torrentstream/TorrentStream.java#L372

you are getting a reference to a torrent handle from an alert. This references are short lived inside libtorrent, then the "Fatal signal 11". Use the following instead:
```
TorrentHandle th = mTorrentSession.findTorrent(((TorrentAddedAlert) alert).getHandle().getInfoHash());
mCurrentTorrent = new Torrent(th, listener);
```

Now, when do you not get the NPE (I will write about it after this), you will get to the point of:
```
08-07 22:29:12.121    9544-9544/pct.droid.torrentstreamer.sample D/Torrent﹕ onStreamProgress: 1
08-07 22:29:12.121    9544-9544/pct.droid.torrentstreamer.sample D/Torrent﹕ onStreamProgress: 1
08-07 22:29:12.121    9544-9544/pct.droid.torrentstreamer.sample D/Torrent﹕ onStreamProgress: 2
```

Now, about the NPE. The problem is that you are downloading a magnet, at the very beginning, the torrent info is null, since the metadata is not available. Check the class ```MetadataReceivedAlert```.

Let us know.

**Comment by sv244** [comment]
You're a hero! It completely works now.
