### ISSUE TITLE
Ability to instantiate jlibtorrent using a custom binary/library path.

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#38]
Its much much easier, instead of trying to fiddle around with the java.library.path, to use the following code in libtorrent_jni.java to load the correct jlibtorrent binary. In other words, setting the binary path explicitly in code as opposed to using command line params.

For example, my program works for mac, linux, and windows, simply by returning the correct binary:
```java
System.loadLibrary("jlibtorrent"); // Get rid of this line
System.load(DataSources.LIBTORRENT_OS_LIBRARY_PATH()); // Chooses the correct binary depending on the system OS.
```

And you guys could create a general constructor, that can optionally use that path:
```java
LibTorrent.setup(LOCATION_OF_BINARY);
System.out.println(LibTorrent.version());
```

**Comment by tchoulihan** [comment]
Also, I've noticed that the build/ folder is gone with these. Could you perhaps provide the binaries in the build folder like you did before, or provide them as part of each new release? I know it stinks that you can't (or at least I don't know how) to bundle them with maven.

**Comment by aldenml** [comment]
I will think about how to provide more flexibility for loading the native library, no a big fan of LibTorrent.setup.

**Comment by tchoulihan** [comment]
Any ideas for this? The name doesn't matter to me, it could be, `loadCustomBinary`, `loadCustomLibrary`, `loadBinary`, `loadLibrary`, anything really.

The code would just be:
```java
    public static void loadBinary(File customBinary) {
        try {
            System.load(customBinary);
        } catch (UnsatisfiedLinkError e) {
            throw new UnsatisfiedLinkError("Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent");
        }
    }
```

**Comment by aldenml** [comment]
I think you can do it yourself before any code related to jlibtorrent. I mean, you can do your custom load library, as long as it's before the one in jlibtorrent. Did you tried that?

**Comment by tchoulihan** [comment]
I thought I tried that, but let me double check.

**Comment by tchoulihan** [comment]
@aldenml Ah okay, so here's the issue. I tried loading the library in multiple places before jlibtorrent is ever imported, but it doesn't seem to make a difference. The error below shows that [this line](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/swig/libtorrent_jni.java#L15) in libtorrent_jni is the issue.

Basically, it still tries to load the library regardless of what I do beforehand, and it fails because its not in the java.library.path, which I hate using because its not dynamic. The solution is to check to see if any of the libraries are already loaded, and if they are, then don't run that line. 

Here's how to find the loaded libraries:
http://stackoverflow.com/questions/1007861/how-do-i-get-a-list-of-jni-libraries-which-are-loaded/1008631#1008631

Another solution might be to set a Boolean flag, something like `loadCustomBinary(default false)`, that will only load it if that is set to true.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:17)
	at com.frostwire.jlibtorrent.swig.default_storage.disk_write_access_log(default_storage.java:91)
	at com.torrenttunes.client.LibtorrentEngine.<init>(LibtorrentEngine.java:95)
	at com.torrenttunes.client.LibtorrentEngine.<clinit>(LibtorrentEngine.java:78)
	at com.torrenttunes.client.Main.setupLibTorrentSettings(Main.java:104)
	at com.torrenttunes.client.Main.setupSettings(Main.java:93)
	at com.torrenttunes.client.Main.doMain(Main.java:70)
	at com.torrenttunes.client.Main.main(Main.java:143)
```

**Comment by aldenml** [comment]
OK, I will check this. I was under the impression that the JVM should avoid the double loading. In the meantime, are you stopped by this issue? or are you able to grab the sources code and continue?

**Comment by tchoulihan** [comment]
No I'm not stopped by the issue, whenever you can get around to it works.

I've got a workaround, its just not ideal and isn't multi-platform.

**Comment by aldenml** [comment]
Now you can specify the path and it will take precedence over the java.library.path, see https://github.com/frostwire/frostwire-jlibtorrent/commit/5fe9c62ff86ed16ef1f1935348528a3b7a6661bd

But it's up to the library caller figure out how to manage these binaries per platform.

**Comment by tchoulihan** [comment]
Cool, looks great! I'll test this out today.
