### ISSUE TITLE
build/ folder and binaries are missing

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#39]
I've noticed the build folder is gone, and also, none of the build shell scripts in the swig/ folder work. So I'm unable to get libtorrent 1.1.0.1-3 working.

**Comment by aldenml** [comment]
Now there is an artifact for each architecture, for example, for windows there is jlibtorrent-windows. The only file inside this jar is the binary for windows. For now, you need to grab the one you want. We added the binaries to the repo just for convenience at the beginning.

I will close the issue. Let's open other issue just for the build script issue you are having.

**Comment by tchoulihan** [comment]
Where can I find these artifacts?

**Comment by aldenml** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cjlibtorrent

**Comment by tchoulihan** [comment]
I tried using just jlibtorrent-linux, but none of the imports seemed to work. Then I tried adding both, and I'm still getting an UnsatisfiedLinkError.

**Comment by tchoulihan** [comment]
I'm using a shaded/fat jar, so I find that it does come packaged in a target directory: lib/x86_64/libjlibtorrent.so . 

But I have no way to load that file in code or otherwise.

**Comment by aldenml** [comment]
I didn't fully explain myself. You to unzip the jar, get the binary and put in the place you defined.

**Comment by tchoulihan** [comment]
Where should I place the binary so that jlibtorrent will find it. In the root directory of the project?

**Comment by aldenml** [comment]
In the root or a path defined by java.library.path (startup working directory is the default).

**Comment by tchoulihan** [comment]
Whew, finally figured it out, thanks @aldenml  . I had to find out what my java.library.path was first:
```java
System.out.println("java library path: " + System.getProperty("java.library.path"));
```
, then copy the resource there. I'll stop commenting here, and just request for the other thread that I can somehow have the ability to load custom binary paths in code(so I can keep on using a self-contained jar that runs on multiple platforms.)

**Comment by aldenml** [comment]
Good to know!
