### ISSUE TITLE
Add SESSION_STATS to jlibtorrent

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#40]
@arvidn is asking me for session stats instead ... 

From here : https://github.com/arvidn/libtorrent/issues/63#issuecomment-129225232

> you get session stats by building with statistics=on (if building with boost-build) or defining TORRENT_STATS

**Comment by aldenml** [comment]
This flag is already on, see https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/Jamfile#L63. and `SessionStatsAlert`.

**Comment by aldenml** [comment]
Ignore my previous comment, it seems that arvidn was mentioning statistics for the RC_1X branch. Ok, see SessionStatsAlert and let me know if you still don't have the required values. See also https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L917

**Comment by arvidn** [comment]
ah, yes. Right. I'm sorry if I haven't been very clear, I keep forgetting that this changed in from 1.0.x to master. It looks like you're building against master now the, right? (because the session_stats_alert is new).

It looks like you know how to use this API already. This is what I would suggest:

Have some stats logging mode, where you dump every value in the session stats alert to a file. I would suggest a file format like this:

first line: <field-name>:<field-name>: etc.
all subsequent lines: <vale>\t<value>\n etc.
Where the field-names are the names as returned by the session_stats_metrics() (see https://github.com/arvidn/libtorrent/blob/master/examples/stats_counters.cpp#L40 ). And where value is the integer reported for the corresponding counter in session_stats_alert. and \t is a tab character.

With this file format, the tools/parse_session_stats.py will be able to parse and generate nice graphs (requires gnuplot).

libtorrent 1.0.x had the file dumping built-in, but was only enabled with a build configuration option, and was not appropriate for production deployment. It would probably make sense for me to add a facility to dump session_stats_alert to a file like that. I haven't gotten around to do that yet, partly because I'm not entirely sure it's a good idea to make that part of libtorrent itself.

**Comment by tchoulihan** [comment]
@aldenml I found a session stats alert that I can use as a torrentAlertAdapter like so
```java
session.addListener(new TorrentAlertAdapter(torrent) {
			@Override
			public void sessionStats(SessionStatsAlert alert) {
				log.debug(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
			}
});
```

Should grepping for these lines be enough? Also, these alerts are torrent-based, not session-based, if I'm reading that right.

**Comment by arvidn** [comment]
libtorrent only keep counters per session, and only post session_stats_alert per session (not per torrent). I would imagine this alert would be called for all torrent alert adapters..

**Comment by aldenml** [comment]
@tchoulihan I think that should be a mistake on my side. Since `SessionStatsAlert` is not a `TorrentAlert` this method will never be called. See https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/TorrentAlertAdapter.java#L33, I will fix that. Just add an AlertListener to listen for this  `SessionStatsAlert`.

**Comment by tchoulihan** [comment]
@aldenml just to verify, does this look like the right code? I'm not sure how to do session-only alerts:
```java
		session.addListener(new AlertListener() {
			
			@Override
			public int[] types() {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public void alert(Alert<?> alert) {
				if (alert.getType() == AlertType.SESSION_STATS) {
					log.debug(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

				}
				
			}
		});
```

**Comment by aldenml** [comment]
```
 session.addListener(new AlertListener() {

            @Override
            public int[] types() {
                return new int[]{AlertType.SESSION_STATS.getSwig()}; // this could be a static field.
// null is for not filter at all
            }

            @Override
            public void alert(Alert<?> alert) {
                if (alert instanceof SesstionStatsAlert) { // you can check for the type too
                    log.debug(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
                }
            }
        });
```

**Comment by tchoulihan** [comment]
Gotcha, thanks a bunch.

**Comment by tchoulihan** [comment]
All that does is create output lines like this:
`DEBUG c.t.client.LibtorrentEngine - SESSION_STATS - session_stats_alert - session stats (2344 values)`

But doesn't write any output files.

**Comment by aldenml** [comment]
All the info is in the alert, use this as a guide: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L1016

**Comment by arvidn** [comment]
the session stats alert has an array of int64 values. Each value has a name. The mapping between name and index into this array is defined by the return value of session_stats_metric(). All these numbers need to be logged to a file, with a correctly named column header indicating the name of the value (as defined by the return value of session_stats_metrics()). Anything that doesn't have a for loop or anything that doesn't have a call to session_stats_metric() will not be able to satisfy these requirements.

**Comment by tchoulihan** [comment]
Okay, so from what I can gather, I have to : 
1) Get the number of session_stat values(presumably from the alert.message?)
2) loop over them and append them to a file with column headers

What should the format look like, @arvidn ?

So something like: 
```java
// Write the column headers first'
// parse the # of alert.values from alert.getSwig().message()

for (int i = 0; i < numberOfAlerts; i++) {
  long value = ((SessionStatsAlert) alert).value(i);
   // Append the value to the file
}
```

**Comment by arvidn** [comment]
@tchoulihan https://github.com/frostwire/frostwire-jlibtorrent/issues/40#issuecomment-129248172

**Comment by tchoulihan** [comment]
@arvidn , just to verify, use `\t` as a delimiter , and `\n` (or standard println) as newlines?

I think I may have found the column names too, using `StatsMetric[] com.frostwire.jlibtorrent.LibTorrent.sessionStatsMetrics()` . 

@aldenml , as long as this array is in order, IE, that `sessionStatsMetrics()[0]` aligns up with `((SessionStatsAlert) alert).value(0)`, then I can get started.

**Comment by aldenml** [comment]
They are aligned, but if you want also see `LibTorrent.findMetricIdx` if you want more checks.

**Comment by aldenml** [comment]
@tchoulihan I will close this issue since I don't see one.

**Comment by arvidn** [comment]
The name -> counter-index mapping returned by session_stats_metrics() is not ordered. Each item in the returned vector has a name and index. See: https://github.com/arvidn/libtorrent/blob/b5a477d7fd193348d1e30f20f9958bea2b012261/include/libtorrent/session_stats.hpp#L45

It's done this way to be able to insert more counters (next to associated counters) without breaking ABI.

**Comment by tchoulihan** [comment]
@arvidn I think I gotcha, I see a `name`, `type`, and `value_index`, and some static `type_counter` and `type_gauge` fields on StatsMetric. Judging by your comments, I'll use the `value_index` field for the correct position.

**Comment by arvidn** [comment]
right. the type is not really relevant for this logging. It just indicates how to interpret the value (whether it's monotonically increasing counter or a snapshot state)

**Comment by tchoulihan** [comment]
@arvidn Okay, so I've been running `parse_session_stats.py` on a session stats log file I've created, and its been taking about 10 minutes so far for a 136 kb file, with no logging messages.

`python parse_session_stats.py session_stats.out`

**Comment by arvidn** [comment]
There are two issues. (1) The first line should use ':' as column separators. (2) it turns out the script expects the left-most column to be a second time-stamp and have a header name "seconds".

**Comment by arvidn** [comment]
it also expects the filename to end with .0000.log (and if there are subsequent files, like 0001.log etc those will be picked up as well). However, it also looks like this script has not been updated with the new names of the counters, but still use the old ones from 1.0.x.

However, there is an updated version here: https://raw.githubusercontent.com/arvidn/libtorrent-webui/master/parse_session_stats.py (you still need the first "second" timestamp column though)

(I should probably remove the one from the libtorrent repo)

**Comment by tchoulihan** [comment]
Okay, I just tried using this new version of parse_session_stats.py, and made the changes you recommended, and am getting the exact same issue, the script stalls, and writes no logging lines.

Here's the link to my new session_stats file, that's not working with the python script:
https://drive.google.com/file/d/0B0PA7XM1BmLMLTYzWjRJRUJfWE0/view?usp=sharing


> it turns out the script expects the left-most column to be a second time-stamp and have a header name "seconds".

@arvidn I'm going to guess that format is just long date seconds.

Also, this seems a bit strange because there is a header with `value_index=0`, meaning that everything will be offset by 1 now, but I'll just go with it.

And just out of curiosity, why use two different delimiters? `:` and `\t`?



Could you show me an example session_stats file and I'll try to recreate its format?

**Comment by arvidn** [comment]
your leftmost column is called "seconds", the script is looking for "second". With that change it works. However, you probably want to have the seconds start at 0 as well.

the delimiters among the values and header have different meanings. The header line should not be treated as values.

**Comment by tchoulihan** [comment]
@arvidn Thanks, that did it! Everything works and its writing out the folder with the index.html perfectly!

I can post / share the folder on my site if you think its necessary, but I think we need to get past this torrents downloading speed issue first: https://github.com/arvidn/libtorrent/issues/77#issuecomment-130146073 , because my program basically broke going from libtorrent 1.0.5.0 to 1.1.0 .
