### ISSUE TITLE
How to set custom swig settings in a SettingsPack correctly?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#41]
Here's how I'm currently doing it, and I have no idea if its working or not:

```java
session = new Session();
sessionSettings = new SettingsPack();

sessionSettings.setActiveSeeds(999999);
sessionSettings.setInteger(int_types.active_limit.swigValue(), 999999); // this line

session.applySettings(sessionSettings);
```

**Comment by aldenml** [comment]
Yes, that's correct.

**Comment by gubatron** [comment]
you can always verify using the `.getXXX` methods.

TIP: Open the `frostwire-desktop` project, and when you have doubts on how to use things, look for ocurrences of that class/method in the `frostwire-desktop` project.

**Comment by gubatron** [comment]
#TODO: Gather all these questions and start a list of **jlibtorrent recipes** on the wiki of this repository.

Other people will probably find them very useful, and once we have enough we could even have an introductory manual. At the moment, probably not worth it as the API is still changing rapidly.

**Comment by gubatron** [comment]
Better yet.

These "recipes" should simply be in the documentation of the class.

That way you just look at the javadoc and that's it. I love javadocs that include examples, they're the best.

**Comment by gubatron** [comment]
Stuff like this should go a long way
https://github.com/frostwire/frostwire-jlibtorrent/commit/55ea6ce8ec27044b1075119574c13adef5449475

cc: @tchoulihan

**Comment by tchoulihan** [comment]
Thanks guys. I like you guys' demo folders, as those are my favorite ways to learn and see usage. @gubatron That works great too!
