### ISSUE TITLE
How to turn on PeerLog alerts/ Peer Logging?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#42]
@arvidn is recommending that I do some logging of PeerLog, and I have the code to do them, but I don't know how to turn the logging on. 

He told me : 
> In 1.1.0 you don't need to rebuild libtorrent to enable verbose peer logging, they are alerts now that can be enabled with an alert mask flag.

Here's my code thats not doing anything :( 
```java
		session.addListener(new AlertListener() {

			@Override
			public int[] types() {
				return new int[]{AlertType.SESSION_STATS.getSwig(), AlertType.PEER_LOG.getSwig()};
				
			}
@Override
public void alert(Alert<?> alert) {
   if (alert instanceof PeerLogAlert) {
						log.debug("peer log alert");
						log.debug(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
						log.debug(((PeerLogAlert) alert).eventType());
						log.debug(((PeerLogAlert) alert).direction().toString());
						log.debug(((PeerLogAlert) alert).getPeerId().toString());
						log.debug(((PeerLogAlert) alert).getPeerIP().toString());
					}
```

**Comment by tchoulihan** [comment]
@aldenml I also just tried doing this with PeerLogAlert as a `TorrentAlertAdapter` too, but neither worked.

**Comment by aldenml** [comment]
Pass true in the logging parameter, see https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L91

**Comment by tchoulihan** [comment]
@aldenml Thanks! Do you guys have some sample values for some of those params. I have no idea what `iface` for example should be:

`Session(Fingerprint print, Pair<Integer, Integer> prange, String iface, List<Pair<String, Integer>> routers, boolean logging)`

**Comment by aldenml** [comment]
Follow this code: https://github.com/frostwire/frostwire-desktop/blob/master/src/com/limegroup/gnutella/gui/Initializer.java#L449

**Comment by tchoulihan** [comment]
Okay, so I have prange, iface, logging, but not Fingerprint or routers. Neither of those are set in BTEngine.java either, because they're using a different constructor.

**Comment by tchoulihan** [comment]
@aldenml wait, nm, I found some defaults in the https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java

Sorry aboot that.

**Comment by tchoulihan** [comment]
It might be useful to make defaultRouters public: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L1071

**Comment by gubatron** [comment]
making `defaultRouters` public won't really do anything for you, it's a fixed list of routers that you can always see in the code. If you need to use different default routers, then you gotta [use the other constructor](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/Session.java#L91) that takes a list of routers of your chosing.
