### ISSUE TITLE
How to set enum types of SettingsPack settings?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#43]
I'm trying to get jlibtorrent to prefer TCP over uTP, and I ned to set Bandwidth_Mixed_Algo, or Mixed_Mode_Algorithm to prefer TCP.

I used to be able to do `sessionSettings.setMixedModeAlgorithm(BandwidthMixedAlgo.PEER_PROPORTIONAL);`

How do I do this now?

**Comment by aldenml** [comment]
Something like this:
```
SessionPack sp = new SessionPack();
sp.setInteger(settings_pack.int_types.mixed_mode_algorithm.swigValue(), settings_pack.bandwidth_mixed_algo_t.peer_proportional.swigValue());
session.applySettings(sp);
```

**Comment by tchoulihan** [comment]
Thanks sir.
