### ISSUE TITLE
Problems with frostwire-jlibtorrent-linux artifact(libjlibtorrent.so) on linux kernel versions 4.x

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#50]
I'm currently using the pre-built linux `libjlibtorrent.so` version `1.1.0.6` from here:

http://mvnrepository.com/artifact/com.frostwire/jlibtorrent-linux

Someone running my client is getting the following error(on kernel version `4.1.6-200.fc22.x86_64`):
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
```

I think we've narrowed it down to a linux kernel version issue: I have many of these clients running on various versions of linux 3.x, but hadn't tried 4.x yet.

What would be the best way to solve this issue?

**Comment by aldenml** [comment]
The only thing I can imagine is a missing library, or different location of one of them. I compile the library in  ubuntu and this is the ldd result:
![screen shot 2015-09-02 at 9 12 03 pm](https://cloud.githubusercontent.com/assets/143813/9648512/7f788132-51b7-11e5-8c8d-ef57d3117d84.png)
Can you request a ldd from one of this computers?

**Comment by tchoulihan** [comment]
On it, waiting for a reply back from the person with the issue.

**Comment by tchoulihan** [comment]
Here's their output:
```
linux-vdso.so.1 (0x00007ffeb1503000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f1c25dde000)
    libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007f1c25b6f000)
    libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f1c25786000)
    libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1c25404000)
    libm.so.6 => /lib64/libm.so.6 (0x00007f1c250fc000)
    libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1c24ee4000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f1c24b24000)
    /lib64/ld-linux-x86-64.so.2 (0x0000563b595cb000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1c24908000)
    libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f1c246ba000)
    libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f1c243d5000)
    libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1c241d1000)
    libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f1c23f9d000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f1c23d99000)
    libz.so.1 => /lib64/libz.so.1 (0x00007f1c23b83000)
    libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f1c23973000)
    libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1c2376f000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1c23554000)
    libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1c2332f000)
    libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f1c230bf000)
```

**Comment by aldenml** [comment]
No idea why so many dependencies are listed here. I suppose that a compilation under kernel 4.x is in order.

**Comment by aldenml** [comment]
Can you ask which distribution is this? may be the problem is related to some libc incompatibility.

**Comment by tchoulihan** [comment]
Its fedora.

**Comment by aldenml** [comment]
I will compile it in fedora for testing, but I don't know if we will support binary per distribution in the near future.

**Comment by tchoulihan** [comment]
They ran `ldd libjlibtorrent.so` , linux-vdso.so.1 was just the first one on the list.

Hrm... their output seems to be resolving everything correctly, but this is out of my realm of expertise. The only possibilities I can think of is a boost dependency issue, or something to do with a different version of `libc`.

I tried a little googling on fedora and libc issues, but couldn't find anything.

**Comment by aldenml** [comment]
Taking a look at it in my VM (fedora 22 with kernel 4.1.6-200.fc22.x86_64).

**Comment by aldenml** [comment]
Just to post and update. It seems that the problem is the version of openssl, even if the ldd resolve them, fedora 22 does not have openssl-1.0.0 (the actual package is >= 1.0.1). It seems to me that this link was manually done. I made the same, and the error is:

`/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found`

**Comment by tchoulihan** [comment]
Should just installing openssl be enough?

**Comment by aldenml** [comment]
no, because the version does not match (in fedora is newer). I'm trying to link statically to openssl and see the resulting size.

**Comment by aldenml** [comment]
Ok, it adds like 2MB. If you are pressed by this issue, I recommend you to compile the binary for this distribution until we figure out a better solution.

**Comment by tchoulihan** [comment]
I'm not pressed by the issue. 

I'm not sure how libtorrent in general gets around this issue, if apps like deluge come packaged with openssl or not, and if they can even run on fedora(I assume they can).

**Comment by aldenml** [comment]
Then, I will try to get this done for 1.1.0.9. I will play with the flags of openssl to get it statically linked.

**Comment by tchoulihan** [comment]
Sounds good.

**Comment by aldenml** [comment]
Fixed and you should be able to run it in next version

![screen shot 2015-09-05 at 10 26 40 pm](https://cloud.githubusercontent.com/assets/143813/9702110/4ed782ae-541d-11e5-92c6-548fec985fb0.png)

**Comment by gubatron** [comment]
sweet.

i wonder if android has issues like these with openssl.

**Comment by aldenml** [comment]
no, because I compile statically with openssl (as in windows), the same will be for linux.

**Comment by tchoulihan** [comment]
@aldenml When will you guys release 1.1.0.9? Some of my users are requesting support for fedora.

**Comment by aldenml** [comment]
Hopefully this week

**Comment by tchoulihan** [comment]
Sounds good, thanks.

**Comment by aldenml** [comment]
Let me reopen this issue to not forget notify you.

**Comment by joaoluiz** [comment]
Hi, I have the same problem with MacOS X Yosemite. 
I will wait  for the next version. Thank you,

**Comment by aldenml** [comment]
@joaoluiz in this case the problem was the openssl version, but mac should be fine, since it's a standard component. Could you provide more details?

**Comment by joaoluiz** [comment]
@aldenml thank you for reply. I found my problem, I needed to put this line before use the Session: 
System.setProperty("jlibtorrent.jni.path", "/Users/joaoluiz/projects/TestTorrent/lib/libjlibtorrent.dylib");

After this, my code works!
Thank you for helping us.

**Comment by aldenml** [comment]
@tchoulihan jlibtorrent 1.1.0.9 is released (http://repo1.maven.org/maven2/com/frostwire/jlibtorrent/1.1.0.9/)

For linux, there are two binaries (x86 and x86_64) and both are compiled with openssl statically.

**Comment by tchoulihan** [comment]
For some reason, 1.1.0.9 isn't working for me now on my ubuntu 64 bit version(the jlibtorrent-linux dependency). It built and wrote the two `libjlibtorrent.so` files correctly, but the 64 bit one doesn't work at least. The last version I had working and tested was 1.1.0.5.
```
tyler@tyler-ThinkPad-Edge-E545:~/git/torrenttunes-client$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
...
16:08:00.725 [main] INFO  c.t.client.tools.DataSources - Operating system: linux, JVM bits: 64
16:08:00.737 [main] INFO  c.t.client.tools.DataSources - Using libtorrent @ /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:22)
```

**Comment by aldenml** [comment]
Can you give me the result of: $md5sum /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so

**Comment by tchoulihan** [comment]
fb1d1314493d4ac27f9f299d73849148  /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so

**Comment by aldenml** [comment]
and $ldd /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so

**Comment by tchoulihan** [comment]
```
tyler@tyler-ThinkPad-Edge-E545:~/git/torrenttunes-client$ ldd /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so
/home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/tyler/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so)
	linux-vdso.so.1 =>  (0x00007fff91300000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2645eb0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2645ba8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f26458a0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2645688000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f26452c0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2646b80000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f26450a0000)
```

**Comment by aldenml** [comment]
I'm compiling with ubuntu 15.04 due to the lack of java 8 un ubuntu 14.04. Let me research about "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found "

**Comment by tchoulihan** [comment]
Maybe this answer?

http://stackoverflow.com/a/19997068/1655478

**Comment by aldenml** [comment]
I think that doing that in linux is a risky proposition, since there are a lot of others shared libraries loaded. What is our OS?

**Comment by tchoulihan** [comment]
Reading through some comments on related threads, people seem to say that's the quickest workaround. 

There seems to be one other solution mentioned in this thread:
http://stackoverflow.com/questions/5216399/usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found

**Comment by tchoulihan** [comment]
Maybe you could just link to a lower version of glibc, my system has up to `GLIBCXX_3.4.19` , but not .20

**Comment by aldenml** [comment]
Yes, maybe. I'm frustrated by this linux shared libraries issues, not in this project, but in general. Anything that comes outside the official packages is the same, binary issues (I started with RedHat 5.3). What's the point :)

Ok, I will recompile the libraries, but I will update them in frostwire-desktop. Is that ok for you?

**Comment by tchoulihan** [comment]
All I really care about is those maven dependencies that hold your libraries, `jlibtorrent-android`, `jlibtorrent-linux`, etc. Its the easiest way for me to use them. You could just overwrite them, and I can run a `mvn -U` to force the update, since probably nobody other than me has pulled down 1.1.0.9 so far.

**Comment by aldenml** [comment]
Ok, I will override only the jblitorrent-linux.

**Comment by tchoulihan** [comment]
Sounds good, let me know when you're ready for me to test.

**Comment by aldenml** [comment]
Compiling it now

**Comment by aldenml** [comment]
Ok, already release to maven, give it like 10 mins and let me know

**Comment by tchoulihan** [comment]
That did it! Thanks @aldenml . I had to manually delete it from my .m2/ folder, but it picked up the new one now.

Question: does this linking issue only exist for the linux version? Is there any reason the same problem we just had might exist for the windows or mac version?

**Comment by aldenml** [comment]
Good to know, thanks for reporting.

Similar problems could happen in windows and mac, but so far, we don't have them.
