### ISSUE TITLE
Torrent_finished alerts not firing

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#52]
I've notice that occasionally, a torrent will be shown to be 100% downloaded, yet will not fire a torrent_finished alerts. It only happens sometimes.

Could you guys think of a possible cause of this? I've been stumped so far.

**Comment by gubatron** [comment]
think it might be a precision error? like in reality the torrent has donwloaded 99.99% but rounding makes it look like 100% and the alert won't be fired until it's truly finished?

**Comment by aldenml** [comment]
Per documentation, that alert is fired if the torrent becomes a seed. Maybe in some case you get 100% and for some reason don't become a seed of the torrent.

Another cause could be so much alerts (do you have logging active?). So much alerts could create some of them removed before we poll them.

**Comment by tchoulihan** [comment]
> think it might be a precision error? like in reality the torrent has donwloaded 99.99% but rounding makes it look like 100% and the alert won't be fired until it's truly finished? 

That's a possibility, let me create a way for me to check that and report back.

> Per documentation, that alert is fired if the torrent becomes a seed

Gotcha, now on to figure out why some torrents aren't becoming seeds.

> Another cause could be so much alerts (do you have logging active?). So much alerts could create some of them removed before we poll them.

I have plenty of torrentAlertListeners in use, but this issue only affects a minority of torrents, and the order in which they are torrented doesn't seem to matter, leading me to believe logging isn't the issue.

**Comment by aldenml** [comment]
For release, you definitively want to put logging = false. To much alerts in the queue and to much overhead.

**Comment by tchoulihan** [comment]
What's the logging line again? My logging currently consists of:
```java
		if (Main.log.getLevel().equals(Level.DEBUG)) {
			// Create a session stats file with headers
			createSessionStatsFile();
			default_storage.disk_write_access_log(true);
			libtorrent.set_utp_stream_logging(true);
			addDefaultSessionAlerts();
		}
```

**Comment by aldenml** [comment]
In the Session constructor.

**Comment by tchoulihan** [comment]
Found it, thanks.

**Comment by tchoulihan** [comment]
Okay, I increased the precision on the torrent progress:
`float progress = th.getStatus().getProgress();`

I just tried one of the torrents that seems to not fire an alert. The result of that line above is `1.0` , but it still doesn't fire a `torrent_finished` alert

**Comment by tchoulihan** [comment]
Hrm... maybe is was the logging=true issue, I'm not getting the problem anymore.

Thanks again @aldenml @gubatron , sorry for wasting time.

**Comment by gubatron** [comment]
ok, then turn off logging to reduce the number of alerts, I think @aldenml's hypotehsis is good.

**Comment by gubatron** [comment]
maybe there's a way to increase the window size for alerts, so you don't lose any alerts when you have logging on.

**Comment by aldenml** [comment]
`settings_pack::alert_queue_size`

**Comment by gubatron** [comment]
#libtorrentMaster!

**Comment by tchoulihan** [comment]
This issue starting cropping again for me, even with logging turned off. What are some sizes I should try for `settings_pack::alert_queue_size` ?

**Comment by aldenml** [comment]
The default number is 1000, if you are dealing with hundred of torrents, I recommend you using 10000 or 20000. Or maybe there is a bug that cause the number not be considered.

**Comment by tchoulihan** [comment]
Thanks, I'll try this.

**Comment by tchoulihan** [comment]
Issue started cropping up again when I restarted my client, not sure what to do. I decreased my `alert_queue` size It kind of shuts my whole service down when it happens.

**Comment by aldenml** [comment]
Did you increase it? What's the current value?

**Comment by tchoulihan** [comment]
I increased it to 100k. It appears to be okay now. I've narrowed down the problem I'm having to this: I'm seeding ~40k torrent, and for some reason, it takes a long time for the queue to clear out when starting up the program, so the `torrent_finished_alert`s take a long time to catch up. 

I was freaking out at first, but if I give it at least 20 minutes, the torrent finished alerts catch up. I'm not sure what to do as an alternative, other than periodically get their status, which I didn't want to do.

**Comment by gubatron** [comment]
wonder if it makes sense to have multiple sessions, each with just 50k.
or even different sessions in different processes.

**Comment by aldenml** [comment]
@tchoulihan I will close the issue since the fundamental problem is the lack of scalability in general, not for this particular alert. It's in our list a review of it. Check this http://blog.libtorrent.org/2012/01/seeding-a-million-torrents/

**Comment by tchoulihan** [comment]
I agree, its not you guys' issue. I read that article a bunch, and got help from @arvidn directly also to fix some of my scalability issues, but not anything with the alert queue. If anything, I should probably forward this problem upstream.
