### ISSUE TITLE
Windows 64 bit support?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#53]
I'm noticing that one of my clients trying to run jlibtorrent with the `jlibtorrent.dll` from the maven/gradle x86/ folder isn't working. They're currently running Windows 10 64-bit. Would it be possible to add the 64 bit version to that maven/gradle build as well?

https://github.com/tchoulihan/torrenttunes-client/issues/13

I've tested the jlibtorrent and it does work fine for windows 32 bit.

**Comment by aldenml** [comment]
I want to clarify that the OS arch does not matter, what matters here is the java arch. You can run the jre 32 bits and you will fine.

The problem with supporting the 64bit version is that we don work with java 64 in windows and we don't test it. Question: If I provide both of them in the same maven jar, how do you setup your library selection?

**Comment by tchoulihan** [comment]
I'm having my client try running the jar with the `java -d32 -jar ...` line, which forces 32 bit. If that works, I'll just close this out.

64 bit isn't absolutely necessary on windows for me.

**Comment by tchoulihan** [comment]
It didn't seem to work for them unfortunately, but using a 32 bit java version did. I'll close this out as its not really too crucial for me.

**Comment by tchoulihan** [comment]
Just a note, I'm getting quite a lot of people requesting Windows java jlibtorrent 64 bit support. Its the only one I think you guys haven't supported yet(linux 32/64, mac 32/64, windows 32)

**Comment by GuacheSuede** [comment]
Second @tchoulihan , been running into heap issues, many suggested switching to 64 bit Windows

**Comment by aldenml** [comment]
Thanks! for the feedback, reopened the issue for evaluation.

**Comment by aldenml** [comment]
1.1.0.10 is released with binaries for windows x86 and x86_64. Give it a try: http://search.maven.org/#search%7Cga%7C1%7Cfrostwire

**Comment by tchoulihan** [comment]
Thanks, this is huge! 

I noticed in this new build, there there is an extra file for a 64 bit mac version, here's the tree:
```
.
├── libjlibtorrent.dylib
├── x86
│   ├── jlibtorrent.dll
│   └── libjlibtorrent.so
└── x86_64
    ├── jlibtorrent.dll
    ├── libjlibtorrent.dylib
    └── libjlibtorrent.so
```
So there seems to be a libjlibtorrent.dll under the 64 bit folder, but also one under the main lib folder. Isn't the mac one jvm bit independent?

**Comment by gubatron** [comment]
i think that is because we dont support mac 32bit

**Comment by aldenml** [comment]
The one in your main should be from not cleaning your environment. I moved it to inside the x86_64 folder for name consistency. Let me know if it doesn't go away after cleaning.

**Comment by tchoulihan** [comment]
You're right it, after cleaning it was removed, and the only one now is in the x86_64 folder, sorry about that.

**Comment by GuacheSuede** [comment]
@aldenml Thanks for the binaries, seems great so far

**Comment by aldenml** [comment]
good to know
