### ISSUE TITLE
Architecture Binary Error 

### ISSUE THREAD

**Issue by GuacheSuede** [frostwire/frostwire-jlibtorrent#56]
Hello Frostwire,
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent`

I am getting this error, which i thought would have been a wrong version or OS , got the Jar from the  releases tab on GitHub which i then decided to build it with `gradle build nativWindowsJar` (please correct me if i am wrong) after getting the exception, but am still getting the same error, I am running Windows 8, 64 Bit. Am i doing anything wrong here which would result in this error ? 

Thank You For Your Help.

**Comment by GuacheSuede** [comment]
PS. got this error while running LazyRead.java

**Comment by aldenml** [comment]
Hi @GuacheSuede, we don't support Windows 64 at this moment. Do you need to work in 64 bits or can you switch to 32 bits? Remember that only the java 32 bits is necessary if you want to switch, not the actual Windows arch.

The `gradle build nativeWindowsJar` is only to build the jar, but you need the actual binary already compiled.

**Comment by GuacheSuede** [comment]
Hello @aldenml thank you for the reply, noted.yes, wouldn't be a problem, would be able to use a VM. Though I am quite confused,  is `gradle build nativeWindowsJar` not enough ? do i need to do some other step ?

**Comment by GuacheSuede** [comment]
would this be the next step ? `compile 'com.frostwire:jlibtorrent:1.1.0.9'`

**Comment by GuacheSuede** [comment]
Alright found the error was missing binaries, Thank you for your help @aldenml.

Refered to [https://github.com/frostwire/frostwire-jlibtorrent/issues/39](https://github.com/frostwire/frostwire-jlibtorrent/issues/39)

**Comment by GuacheSuede** [comment]
Closing this now.

**Comment by aldenml** [comment]
Good that it's working for you.
