### ISSUE TITLE
arm64 for Android

### ISSUE THREAD

**Issue by sv244** [frostwire/frostwire-jlibtorrent#58]
Is there any chance you'll ever add arm64 library for Android to the maven distribution? I'm currently splitting my APK's by architecture to make sure it doesn't become huge (I use another native lib), but the arm64 version doesn't work without a arm64 library.

**Comment by aldenml** [comment]
Supposedly the arm64 should include a core to run 32 bits instructions. Is this a regular market device/phone?

**Comment by sv244** [comment]
> I'm currently splitting my APK's by architecture to make sure it doesn't become huge
No arm64 version of jlibtorrent means that I can't use the arm64 version of my other library. The armv7a version is not automatically included when the arm64 version is missing.

**Comment by aldenml** [comment]
Now I underestand. Well, there is a chance, but I can't say a time. I need to review the build/jar creation. Is this a pressing issue for you?

**Comment by sv244** [comment]
Not really.

You have x86 and armeabi-v7a currently. I didn't have time yet to compile the libraries myself, but I would say that adding the following script to _swig/build-android.sh_ would work?

```
$BOOST_ROOT/bjam --user-config=android-config.jam toolset=gcc-ndk10.android.21.arm64v8a.4.9 target-os=android location=bin/android/arm64-v8a
mv bin/android/arm64-v8a/libjlibtorrent.so.1.1.0 bin/android/arm64-v8a/libjlibtorrent.so
TARGET=bin/android/arm64-v8a/libjlibtorrent.so
$NDK_ROOT/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-strip --strip-unneeded -x $TARGET
```

**Comment by aldenml** [comment]
I need to setup the toolchain for 64 bits in android-config.jam and compile the openssl first.

**Comment by sv244** [comment]
Haha. Yes of course. I understand. I guess you meant `I need to review the build/jar creation` as something else you need to do first?

**Comment by aldenml** [comment]
yes :)

**Comment by sv244** [comment]
Then I misunderstood that you misunderstood me. Just take your time. I'm happy this library exists anyways.

There aren't that many arm64 Android devices out there yet, but I guess the number will increase a lot in the next year. Better be prepared. :D

**Comment by aldenml** [comment]
Ok, 1.1.0.10 is out for arm, x86, arm64 and x86_64 (see the new artifacts): http://search.maven.org/#search%7Cga%7C1%7Cfrostwire

**Comment by sv244** [comment]
Wow. I missed this. Great!
