### ISSUE TITLE
Getting seeders and leechers count

### ISSUE THREAD

**Issue by GuacheSuede** [frostwire/frostwire-jlibtorrent#59]
Hello Frostwire,

I cannot seem to find this anywhere(in the source), i would love to know, how would one find the number of seeders and leechers from a magnet link ?

Thank You for reading.

**Comment by aldenml** [comment]
From a magnet link? I don't think that's possible. You need to start the download to get those numbers.

**Comment by GuacheSuede** [comment]
Ah Noted, Ok Thank you
