### ISSUE TITLE
How to edit and save a .torrent file(Just for reference).

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#61]
So I just wanted to post the question and answer for a problem I just figured out how to solve. You guys might think it worth adding to the examples.

I needed to change the tracker on a ton of my .torrent files, since demonii got shut down, and my torrent's only have 1 tracker and no DHT(for network reasons... there are thousands of them.)

Anyway, here's the method for how to do this:
```java
public static void updateTrackerForTorrent(File torrentFile) {
		
		TorrentInfo ti = new TorrentInfo(torrentFile);

		create_torrent t = new create_torrent(ti.getSwig());

		// Changing the tracker
		for (URI announce : DataSources.ANNOUNCE_LIST()) {
			t.add_tracker(announce.toASCIIString());
		}


		// Get the bencode and write the file
		Entry entry =  new Entry(t.generate());

		Map<String, Entry> entryMap = entry.dictionary();
		Entry entryFromUpdatedMap = Entry.fromMap(entryMap);
		final byte[] bencode = entryFromUpdatedMap.bencode();

		FileOutputStream fos;

		try {
			fos = new FileOutputStream(torrentFile);

			BufferedOutputStream bos = new BufferedOutputStream(fos);
			bos.write(bencode);
			bos.flush();
			bos.close();
			
			log.info("Trackers updated for torrent: " + torrentFile.getName());
		} catch (IOException e) {
			e.printStackTrace();
		}

	}
```

**Comment by aldenml** [comment]
Hi @tchoulihan, thank you for this code. I think that if your are working with tons of torrents, maybe create a TorrentInfo and a create_torrent object is a little on the heavy side. I rather work at the Entry level and add the tracker manually to the dictionary.

**Comment by gubatron** [comment]
tiny detail: the example function missed the list of trackers as a parameter (if you wanted to include something like this in the java api). But I get the gist of it

**Comment by tchoulihan** [comment]
> I rather work at the Entry level and add the tracker manually to the dictionary.

Oops, didn't think of doing it like this. Speed wasn't an issue though; it sweeped through about 30k torrents in about 2 minutes.
