### ISSUE TITLE
Crash SIGSEGV

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#65]
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007ff218585f2b, pid=9787, tid=140677636507392

 JRE version: Java(TM) SE Runtime Environment (7.0_80-b15) (build 1.7.0_80-b15)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libjlibtorrent.so+0x344f2b]  boost::detail::shared_count::shared_count(boost::detail::weak_count const&, boost::detail::sp_nothrow_tag)+0xb

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x00007ff1dd800000):  JavaThread "Thread-3" daemon [_thread_in_native, id=9811, stack(0x00007ff2107d4000,0x00007ff2108d5000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=1 (SEGV_MAPERR), si_addr=0x0000000000000007

Registers:
RAX=0x00000000ebc50f38, RBX=0x00007ff2108d36e0, RCX=0x00007ff2108d3718, RDX=0xffffffffffffffff
RSP=0x00007ff2108d3698, RBP=0x00007ff1f82b6130, RSI=0x00007ff1f82b6138, RDI=0x00007ff2108d36b8
R8 =0x0000000000000095, R9 =0x0000000000000095, R10=0x00007ff21d0e4935, R11=0x00000000ebc50f50
R12=0x0000000000000000, R13=0x00000000ee551140, R14=0x00007ff2108d3740, R15=0x00007ff1dd800000
RIP=0x00007ff218585f2b, EFLAGS=0x0000000000010286, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007ff2108d3698)
0x00007ff2108d3698:   00007ff21861e077 00007ff2108d3700
0x00007ff2108d36a8:   00000000ee551140 0000000000000000
0x00007ff2108d36b8:   ffffffffffffffff 00007ff2108d3700
0x00007ff2108d36c8:   00007ff1dd8001e8 00007ff2108d3750
0x00007ff2108d36d8:   00007ff2184cb9ec 0000000000000000
0x00007ff2108d36e8:   0000000000000000 0000000000000000
0x00007ff2108d36f8:   0000000000000000 00000000ebc50f00
0x00007ff2108d3708:   00007ff21d0e49a7 0000000000000000
0x00007ff2108d3718:   00000000ee551160 00007ff2108d3740
0x00007ff2108d3728:   00007ff1dd800000 00007ff2108d3750
0x00007ff2108d3738:   00007ff2269aa003 00000000c4b57fa0
0x00007ff2108d3748:   000000000006af96 00000000c34c51d8
0x00007ff2108d3758:   00007ff21d42dcd8 00000000ec44a578
0x00007ff2108d3768:   00000000ec44ab08 00000000c34678f8
0x00007ff2108d3778:   00007ff200000009 0000000000000007
0x00007ff2108d3788:   0000000000000000 00000000c47b4ef8
0x00007ff2108d3798:   bf3822d80000000b 00000000c4b4a6d0
0x00007ff2108d37a8:   00000000ee529ea8 00000000c55b9ed0
0x00007ff2108d37b8:   00000000c34c51e8 bff0000000000000
0x00007ff2108d37c8:   000000005efbca51 00000000c4b4a6c0
0x00007ff2108d37d8:   00000000c55b9ec0 00000000ebc50f38
0x00007ff2108d37e8:   00000000ebc50b50 00000000c55b9ec0
0x00007ff2108d37f8:   00000000c55b9ec0 00000000ebc29b20
0x00007ff2108d3808:   00000000ebc29e58 00000000ee529ea8
0x00007ff2108d3818:   0000000000000072 00000000ebc2a070
0x00007ff2108d3828:   00000000c55b9ec0 0000000000000038
0x00007ff2108d3838:   00000000ebc2a600 00000000ee529ef0
0x00007ff2108d3848:   00000000ebc50b18 00000000c34678f8
0x00007ff2108d3858:   0000000000000000 0000000000000035
0x00007ff2108d3868:   00000000ece9b9b0 00007ff2108d38f0
0x00007ff2108d3878:   00007ff21d0004e7 00000000c47b4ef8
0x00007ff2108d3888:   00000000c4ad4660 00007ff200001fa0 

Instructions: (pc=0x00007ff218585f2b)
0x00007ff218585f0b:   80 00 00 00 00 48 8b 07 ff 50 18 eb de 0f 1f 84
0x00007ff218585f1b:   00 00 00 00 00 48 8b 16 48 85 d2 48 89 17 74 1d
0x00007ff218585f2b:   8b 42 08 85 c0 74 0b 89 c1 ff c1 f0 0f b1 4a 08
0x00007ff218585f3b:   75 f1 85 c0 75 07 48 c7 07 00 00 00 00 f3 c3 66 

Register to memory mapping:

RAX=0x00000000ebc50f38 is an oop
com.frostwire.jlibtorrent.swig.sha1_hash 
 - klass: 'com/frostwire/jlibtorrent/swig/sha1_hash'
RBX=0x00007ff2108d36e0 is pointing into the stack for thread: 0x00007ff1dd800000
RCX=0x00007ff2108d3718 is pointing into the stack for thread: 0x00007ff1dd800000
RDX=0xffffffffffffffff is an unknown value
RSP=0x00007ff2108d3698 is pointing into the stack for thread: 0x00007ff1dd800000
RBP=0x00007ff1f82b6130 is an unknown value
RSI=0x00007ff1f82b6138 is an unknown value
RDI=0x00007ff2108d36b8 is pointing into the stack for thread: 0x00007ff1dd800000
R8 =0x0000000000000095 is an unknown value
R9 =0x0000000000000095 is an unknown value
R10=0x00007ff21d0e4935 is at entry_point+85 in (nmethod*)0x00007ff21d0e4750
R11=0x00000000ebc50f50 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x00000000ee551140 is an oop
com.frostwire.jlibtorrent.TorrentHandle 
 - klass: 'com/frostwire/jlibtorrent/TorrentHandle'
R14=0x00007ff2108d3740 is pointing into the stack for thread: 0x00007ff1dd800000
R15=0x00007ff1dd800000 is a thread

Stack: [0x00007ff2107d4000,0x00007ff2108d5000],  sp=0x00007ff2108d3698,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjlibtorrent.so+0x344f2b]  boost::detail::shared_count::shared_count(boost::detail::weak_count const&, boost::detail::sp_nothrow_tag)+0xb

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 984  com.frostwire.jlibtorrent.swig.libtorrent_jni.torrent_handle_info_hash(JLcom/frostwire/jlibtorrent/swig/torrent_handle;)J (0 bytes) @ 0x00007ff21d0e4935 [0x00007ff21d0e48e0+0x55]
J 1436% C2 Torrent.run()V (917 bytes) @ 0x00007ff21d42dcd8 [0x00007ff21d42d860+0x478]
v  ~StubRoutines::call_stub

OS: Ubuntu 14.04 64 bit

Is this enough information?

**Comment by aldenml** [comment]
Is this always happening to you? could you provide a minimal program to reproduce it?

**Comment by gubatron** [comment]
also, what version of libtorrent are you running?

**Comment by WhiteTrashLord** [comment]
I test with jlibtorrent-linux-1.1.0.19.jar.

I saw this crash only 1 time so far.
Sorry, I don't know how to reproduce it.

Where does the problem occur? com.frostwire.jlibtorrent.swig.libtorrent_jni.torrent_handle_info_hash?

I don't know much about JNI :(

**Comment by aldenml** [comment]
JNI is very sensitive to memory management issues. I will keep this open in case we start to get this errors

**Comment by WhiteTrashLord** [comment]
Unfortunately I see a lot of crashes. Older versions might be more stable?

In my test code I get a list of torrents with getSwig().get_torrents() and request several fields from every torrent.

I frequently get a new list of torrents and iterate through it.

**Comment by aldenml** [comment]
Older version if anything are more unstable and with more bugs from libtorrent itself. Can't give you an estimate, but I'm reviewing this (and the others).

**Comment by WhiteTrashLord** [comment]
I think I saw many more crashes when I worked on the session concurrently with several threads. I tried to reduce it which made things better.
You tried to make anything thread-safe?

Probably the safest way is to always use only listeners, or?

**Comment by aldenml** [comment]
I wouldn't treat anything thread-safe unless stated otherwise, specially `Session` since it holds a lot of states (mutable data). Listeners and alerts are the way to interact with the session. A `TorrentHandle` coming from an alert is a very delicate object and should be used for the smaller amount of time and never shared to other threads.

**Comment by WhiteTrashLord** [comment]
What about removing and adding a torrent? I think at least removing can cause a lot of troubles if the AlertLoop-Thread works on a handle of a torrent which was just deleted.

Is it necessary to start  alertsLoop() in the session constructor? I think I would start it once the first listener was added.

Currently I am thinking about modifying the Session-alertsLoop so I can run also my own code on this thread. Do you think this is a good idea?

**Comment by aldenml** [comment]
I need to think a little more about concurrency issues while removing a torrent.

AlertsLoop and Session are there to provide an out-of-the-box solution. I personally don't see an advantage of no starting it in the constructor (you will need it pretty soon anyway).

Can say without knowing what's your modification. If you don't mind sharing it.

**Comment by aldenml** [comment]
@WhiteTrashLord reopening for more review.
