### ISSUE TITLE
invalid torrent handle used

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#67]
java.lang.RuntimeException: invalid torrent handle used
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.session_handle_remove_torrent__SWIG_1(Native Method)
	at com.frostwire.jlibtorrent.swig.session_handle.remove_torrent(session_handle.java:231)
	at com.frostwire.jlibtorrent.Downloader.fetchMagnet(Downloader.java:150)

I sometimes see this exception.
Version: 1.1.0.19

**Comment by aldenml** [comment]
I recommend you wrap your call of fetchMagnet in a try-catch block, I need to review in more detail this fetchMagnet. Thanks for the report.

**Comment by WhiteTrashLord** [comment]
I think I found the reason for this. It seems I have added the same magnet 2 times and both downloads failed. 1 will show this exception because it was already removed.

Will you make the downloader more resilient? Or I have to make sure that the same magnet is only added once at the same time? And thanks for the fast reply btw.

**Comment by aldenml** [comment]
I will make it more resilient, but I want to make it in the context of more bigger refactor.

**Comment by WhiteTrashLord** [comment]
Thanks. It seems there are no problems when you add a magnet several times and fechting is successfully. Only timeouts should lead to this exception. Therefor a fix has a low priority in my case.
