### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#68]
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f340c2eb0d0, pid=16604, tid=139861386065664

 JRE version: Java(TM) SE Runtime Environment (7.0_80-b15) (build 1.7.0_80-b15)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  0x00007f340c2eb0d0

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x00007f342420a800):  JavaThread "pool-1-thread-14" [_thread_in_native, id=16662, stack(0x00007f34042bf000,0x00007f34043c0000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=2 (SEGV_ACCERR), si_addr=0x00007f340c2eb0d0

Registers:
RAX=0x00007f340d38c370, RBX=0x00007f340c3a3530, RCX=0x00007f34043be280, RDX=0x0000000000000084
RSP=0x00007f34043be248, RBP=0x00000000ffffffff, RSI=0x00007f34043be2a0, RDI=0x00007f340c3a3530
R8 =0x0000000000000001, R9 =0x0000000000000000, R10=0x00007f3420000078, R11=0x00007f3420000070
R12=0x00007f340d2e0bd0, R13=0x00007f340c3a3530, R14=0x00007f34043be2a0, R15=0x00007f34201c3118
RIP=0x00007f340c2eb0d0, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000015
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f34043be248)
0x00007f34043be248:   00007f342e1b172e 00007f34201c3110
0x00007f34043be258:   00007f34201c3110 00007f34043be2e0
0x00007f34043be268:   00007f342e1d80dd ffff80cbfbc41d11
0x00007f34043be278:   00007f340c3a3530 0000000000000001
0x00007f34043be288:   0000000000000035 00007f340f0d1011
0x00007f34043be298:   0000000000000000 0000005b00000000
0x00007f34043be2a8:   0000000000000000 0000000000000000
0x00007f34043be2b8:   000000770000006e 0000000000000000
0x00007f34043be2c8:   00007f34043be2ef 00007f342420ba04
0x00007f34043be2d8:   00000000000003d8 62fad70e07d40d25
0x00007f34043be2e8:   ef9db76800000000 0000000000000000
0x00007f34043be2f8:   00007f34043be2e8 00007f34043be2e8
0x00007f34043be308:   0000000000000000 00000000be230f04
0x00007f34043be318:   00007f3420000020 0000000000000101
0x00007f34043be328:   000000005696e27c 00000000bf021e01
0x00007f34043be338:   000000005696e27c 00007f342420a800
0x00007f34043be348:   1892458249c07800 00007f340d73b8c0
0x00007f34043be358:   00007f340d2e0bd0 00007f34201c3110
0x00007f34043be368:   00007f342420a9e8 00000000bf021e08
0x00007f34043be378:   00007f34043be448 00007f342420a800
0x00007f34043be388:   00007f342e193c8d 0000000000000000
0x00007f34043be398:   00000000bf021e08 00007f34043be418
0x00007f34043be3a8:   0000000000000000 00000000bf021e08
0x00007f34043be3b8:   00007f34450127f8 00007f34043be300
0x00007f34043be3c8:   0000000800000001 00007f340000000e
0x00007f34043be3d8:   00007f34043be3d8 0000000000000000
0x00007f34043be3e8:   00007f34043be448 00000000bf0447b8
0x00007f34043be3f8:   0000000000000000 00000000bf021e08
0x00007f34043be408:   0000000000000000 00007f34043be438
0x00007f34043be418:   00007f34043be498 00007f3445006175
0x00007f34043be428:   00000000c40b1690 00007f344500ecd7
0x00007f34043be438:   00000000eec97448 00007f340d2e0bd0 

Instructions: (pc=0x00007f340c2eb0d0)
0x00007f340c2eb0b0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x00007f340c2eb0c0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x00007f340c2eb0d0:   00 00 00 00 00 00 00 00 35 00 00 00 00 00 00 00
0x00007f340c2eb0e0:   00 a8 09 0c 34 7f 00 00 e0 b0 2e 0c 34 7f 00 00 

Register to memory mapping:

RAX=0x00007f340d38c370 is an unknown value
RBX=0x00007f340c3a3530 is an unknown value
RCX=0x00007f34043be280 is pointing into the stack for thread: 0x00007f342420a800
RDX=0x0000000000000084 is an unknown value
RSP=0x00007f34043be248 is pointing into the stack for thread: 0x00007f342420a800
RBP=0x00000000ffffffff is an unallocated location in the heap
RSI=0x00007f34043be2a0 is pointing into the stack for thread: 0x00007f342420a800
RDI=0x00007f340c3a3530 is an unknown value
R8 =0x0000000000000001 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x00007f3420000078 is an unknown value
R11=0x00007f3420000070 is an unknown value
R12=0x00007f340d2e0bd0 is an unknown value
R13=0x00007f340c3a3530 is an unknown value
R14=0x00007f34043be2a0 is pointing into the stack for thread: 0x00007f342420a800
R15=0x00007f34201c3118 is an unknown value

Stack: [0x00007f34042bf000,0x00007f34043c0000],  sp=0x00007f34043be248,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007f340c2eb0d0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.frostwire.jlibtorrent.swig.libtorrent_jni.new_create_torrent__SWIG_5(JLcom/frostwire/jlibtorrent/swig/torrent_info;)J+0
j  com.frostwire.jlibtorrent.swig.create_torrent.<init>(Lcom/frostwire/jlibtorrent/swig/torrent_info;)V+6
j  com.frostwire.jlibtorrent.TorrentInfo.toEntry()Lcom/frostwire/jlibtorrent/Entry;+12
j  com.frostwire.jlibtorrent.TorrentInfo.bencode()[B+1
j  com.frostwire.jlibtorrent.Downloader.fetchMagnet(Ljava/lang/String;J)[B+318
j  MagnetDownload.run()V+33
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

OS: Ubuntu 14.04 64 bit
jlibtorrent-linux-1.1.0.19.jar

Any tips how to reduce the crashes? Should I test with Java 8?

**Comment by aldenml** [comment]
Java 8 will not make any difference. Let me review this. Question: Are you stressing the library with a lot of magnet downloads concurrently?

**Comment by WhiteTrashLord** [comment]
Around 15 magnets downloads were active I think. Most of these magnets will timeout and be added again after some time. So yes, there is some stress.

**Comment by aldenml** [comment]
I think I found a possible reason for this (fetchMagnet needs to be a lot more robust). I will work on it.

**Comment by aldenml** [comment]
@WhiteTrashLord maybe you want to replicate the fetchMagnet source code with some additional internal check. In jlibtorrent there are two layers, the swig, and the one we provide for better API, but nothing prevents you from ignoring our layer and go straight to use the swig one.

**Comment by aldenml** [comment]
@WhiteTrashLord I will reopen the issue, I think it's important to review it in detail.

**Comment by aldenml** [comment]
@WhiteTrashLord just to let you know that I see a lot of potential problems with the current fetchMagnet. Working on it for next version.

**Comment by WhiteTrashLord** [comment]
Thanks. With my own code I have no more crashs :)
