### ISSUE TITLE
LibTorrent.version()

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#69]
Under Windows it gives me this result: 1.1.0.0

I am confused because I expect a version like 1.0.7.

Is it a bug or do you work with an unstable version of libtorrent?

**Comment by aldenml** [comment]
That's correct, we are working with the latest from master, and you can see the exact git revision number with `LibTorrent.revision()`. Btw, libtorrent master is pretty stable.
