### ISSUE TITLE
set_dummy_string_ doesn't persist

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#72]
I made some tests:

        torrent_status ts = th.getSwig().status();        
        ts.set_dummy_string_("test");                 
        
        String dummy = ts.get_dummy_string_();
        System.out.println("Dummy "+dummy);
        if ( dummy != null)
        {
            System.out.println("Dummy length "+dummy.length());
        	
        }    
                
    
        th.getSwig().status().set_dummy_string_("test");                 
        
        String dummy2 = th.getSwig().status().get_dummy_string_();
        System.out.println("Dummy2 "+dummy2);
        if ( dummy2 != null)
        {
            System.out.println("Dummy2 length "+dummy2.length());
        	
        }

I get these results:

Dummy test
Dummy length 4
Dummy2 
Dummy2 length 0

Is this behaviour intended?

Wouldn't make it more sense if the dummy String is stored in all instances of torrent_status?

**Comment by aldenml** [comment]
Actually, this dummy_string is internal, I will remove it from the swig api. But in any case, you can't expect any change in some property in `torrent_status` persists. This object is built (inside libtorrent) every time you request the status.

**Comment by WhiteTrashLord** [comment]
Is there any other way to store custom data for a torrent in a session?

**Comment by aldenml** [comment]
No that I know.

**Comment by gubatron** [comment]
maybe he could alter the info dict, but it'd be better if you just kept another data structure for that, perhaps a `Map<Sha1Hash, MyCustomDataHolder>` would help.
