### ISSUE TITLE
Cross-compilation for Windows fails

### ISSUE THREAD

**Issue by rkfg** [frostwire/frostwire-jlibtorrent#73]
So I've managed to compile it for Linux, no problems. Now I've installed mingw and trying to build the library but stuck at:
```
> ./build.sh --win32
BOOST_ROOT = /home/rkfg/Development/boost_1_60_0
LIBTORRENT_ROOT = /home/rkfg/Development/libtorrent
CXXFLAGS =
LDFLAGS =
OS = LINUX
building boost from source directory:  /home/rkfg/Development/boost_1_60_0
Performing configuration checks

    - 32-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : yes (cached)
...patience...
...patience...
...found 4456 targets...
...updating 3 targets...
gcc.compile.c++ bin/windows/x86/libtorrent_jni.o
In file included from /home/rkfg/Development/libtorrent/include/libtorrent/storage.hpp:55:0,
                 from libtorrent_jni.cpp:704:
/home/rkfg/Development/libtorrent/include/libtorrent/hasher.hpp:53:25: fatal error: openssl/sha.h: No such file or directory
compilation terminated.
```

I have libssl-dev installed and also cloned openssl git repo to ~/Development but it didn't change anything. Instructions on the main page are obsolete and should be updated but in the meantime I'm interested in solving this. I'm on Debian testing amd64. Mingw64 toolchain is installed from repo and symlinked: `~/Development/toolchains/windows-x86/bin -> /usr/bin`

Also I tried to symlink /usr/include/openssl to /usr/local/include (as it's used in compilation: -I"/usr/local/include") but in the end it failed on linking, -lcrypto and -lssl not found so I decided to find a more proper way to compile it.

**Comment by aldenml** [comment]
You need to compile openssl with the mingw toolchain and put the headers and binaries in the right place  (<toolchain-root>)/i686-w64-mingw32/include/openssl and ./i686-w64-mingw32/lib/)

Actually, I strongly recommend you compile openssl for Linux too, since it will have less binary dependencies and could be an up to date version.

**Comment by rkfg** [comment]
Thank you for suggestions. Now, it's not really related to the library but I wasn't able to find any instructions about cross-compiling OpenSSL. I saw some outdated stuff and statements that it "works out of the box" which isn't true in my case.

What I did:

1. cloned https://github.com/openssl/openssl
1. git checkout OpenSSL_1_0_2-stable
1. `./Configure no-dso mingw64` (without no-dso I get `fatal error: tlhelp32.h: No such file or directory` and with just `mingw` — `cc1: error: CPU you selected does not support x86-64 instruction set`)
1. make depend
1. make

It results in this:
```
x86_64cpuid.s: Assembler messages:
x86_64cpuid.s:13: Error: unknown pseudo-op: `.def'
x86_64cpuid.s:13: Error: unknown pseudo-op: `.scl'
x86_64cpuid.s:13: Error: Missing symbol name in directive
x86_64cpuid.s:13: Error: unrecognized symbol type "32"
x86_64cpuid.s:13: Error: unknown pseudo-op: `.endef'
x86_64cpuid.s:27: Error: unknown pseudo-op: `.def'
x86_64cpuid.s:27: Error: unknown pseudo-op: `.scl'
x86_64cpuid.s:27: Error: Missing symbol name in directive
<...>
```

Stuck again, can't find anything like that in google regarding OpenSSL...

**Comment by aldenml** [comment]
Wow, I don't remember having this problems. I do remember built the mingw64 toolchain in the linux box because I didn't trust the one coming in the distro and I want to be in total control of what dependencies are in the final binary.

Give it a try compiling the toolchain, or maybe I can send you my mingw-toolchain.tar.gz for your testing (Ubuntu 14.0,4).

**Comment by rkfg** [comment]
Figured this out though still haven't completed the main task. The rabbit hole happened to be much deeper than I initially thought.

So the problem was that mingw64 wasn't used at all. The right way to cross-compile is to use this command: `./Configure no-shared mingw64 --cross-compile-prefix=x86_64-w64-mingw32-` for 64 bit and `./Configure no-shared mingw --cross-compile-prefix=i686-w64-mingw32-` for 32 bit. That `--cross-compile-prefix=` I missed and it used the default gcc. Found it [here](https://marc.xn--wckerlin-0za.ch/computer/cross-compile-openssl-for-windows-on-linux). It's also a source of confusion that there are seemingly two versions of mingw: mingw32, the old and abandoned, and mingw64 which is being actively developed. Despite the name it supports producing both i686 and x86_64 binaries. OpenSSL adds to the confusion using mingw and mingw64 targets.

Now I'm getting several link errors (different for 32 and 64 bits, sigh). Will try it further.

**Comment by aldenml** [comment]
Good to know. I solve that problem changing the CC and CXX environment variables to the desired compilers in the toolchain.

**Comment by rkfg** [comment]
I tried changing them and got lots of perl errors about undefined vars. The approach I described works much better. That said, I've compiled OpenSSL for x86_64 with mingw, just checked out OpenSSL_1_0_2-stable. Something must be broken in master.

**Comment by rkfg** [comment]
How should I add those includes from openssl and compiled libs (libssl.a, libcrypto.a) to the toolchain? Where exactly to put them?

**Comment by aldenml** [comment]
`<toolchain>/i686-w64-mingw32/include/openssl` and `<toolchain>/i686-w64-mingw32/lib/` in my case of custom toolchains. Just look for the standard include and lib folder of your toolchain, take care of the 32 and 64 bit issue.

**Comment by rkfg** [comment]
Are you sure? The scripts expect `<toolchain>/windows-x86_64/bin/x86_64-w64-mingw32-g++` as a compiler, I suppose `include` and `lib` should go to `<toolchain>/windows-x86_64/include` and `<toolchain>/windows-x86_64/lib`. If that's the case, it doesn't work as expected, it can't find those files:
```
gcc.compile.c++ bin/windows/x86_64/libtorrent_jni.o
In file included from /home/rkfg/Development/libtorrent/include/libtorrent/storage.hpp:55:0,
                 from libtorrent_jni.cpp:704:
/home/rkfg/Development/libtorrent/include/libtorrent/hasher.hpp:53:25: fatal error: openssl/sha.h: No such file or directory
compilation terminated.
```

Of course, I can put them into `/usr/local/include` (for some reason `/usr/include` isn't used) and `/usr/lib` but it doesn't look right.

**Comment by aldenml** [comment]
I'm not an expert in toolchains but I think every toolchain should have a sysroot, where the standard libraries and includes reside. I suggest looking for the 32 bit versions of the windows libraries in the mingw64 toolchain, something similar should exists for the regular 64 bit. The layout should reveal the actual paths to put the openssl.

**Comment by gubatron** [comment]
(the pains of openssl compilation, I feel his pain)

**Comment by rkfg** [comment]
Thank you, @aldenml, I've found the root for includes and libraries. Progress so far: compiled OpenSSL on mingw64, the root for include and lib is /usr/i686-w64-mingw32 and /usr/x86_64-w64-mingw32 (32 and 64 bit). Symlinked include, copied libs, looks fine.

Now the Boost part. Should I compile it per platform or can it be compiled partially just for jlibtorrent? Full mingw compile looks even more complex than OpenSSL, cryptic messages and such. Without compiling it complains about missing SSLv2:
```
gcc.compile.c++ bin/windows/x86/src/alert.o
In file included from /home/rkfg/Development/boost_1_60_0/boost/asio/ssl/context.hpp:786:0,
                 from /home/rkfg/Development/libtorrent/include/libtorrent/tracker_manager.hpp:54,
                 from /home/rkfg/Development/libtorrent/include/libtorrent/torrent.hpp:59,
                 from /home/rkfg/Development/libtorrent/src/alert.cpp:43:
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp: In constructor ‘boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)’:
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp:83:29: error: ‘::SSLv2_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_method());
                             ^
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp:86:29: error: ‘::SSLv2_client_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_client_method());
                             ^
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp:89:29: error: ‘::SSLv2_server_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_server_method());
                             ^
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp: In destructor ‘boost::asio::ssl::context::~context()’:
/home/rkfg/Development/boost_1_60_0/boost/asio/ssl/impl/context.ipp:208:16: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
     if (handle_->default_passwd_callback_userdata)
                ^
In file included from /home/rkfg/Development/openssl/include/openssl/crypto.h:132:0,
                 from /home/rkfg/Development/openssl/include/openssl/bio.h:69,
                 from /home/rkfg/Development/openssl/include/openssl/conf.h:62,
                 from /home/rkfg/Development/boost_1_60_0/boost/asio/ssl/detail/openssl_types.hpp:19,
                 from /home/rkfg/Development/boost_1_60_0/boost/asio/ssl/context_base.hpp:19,
                 from /home/rkfg/Development/boost_1_60_0/boost/asio/ssl/context.hpp:27,
                 from /home/rkfg/Development/libtorrent/include/libtorrent/tracker_manager.hpp:54,
                 from /home/rkfg/Development/libtorrent/include/libtorrent/torrent.hpp:59,
                 from /home/rkfg/Development/libtorrent/src/alert.cpp:43:
/home/rkfg/Development/openssl/include/openssl/ossl_typ.h:183:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
```
From what I found, SSLv2 was disabled in OpenSSL somehow but I found no way to control this in Boost. It has its own build system (like we don't have enough already), bjam (or b2) with rather weird syntax. I saw `--no-ssl2` flag mentioned here and there but I don't know where to put it. Or I can try to enable SSLv2 in OpenSSL, maybe it will be less tricky... any help is appreciated.

**Comment by aldenml** [comment]
You don't need to compile boost. It's used as source during the libtorrent compilation. I'm using openssl-1.0.2d (the tar.gz). I don't remember having problems with SSLv2, could you try with http://openssl.org/source/old/1.0.2/openssl-1.0.2d.tar.gz

**Comment by rkfg** [comment]
Yes, thanks for that tip. I tried on another machine and compiled master again. With 1.0.2 it's good. The only issue left is linking:
```
gcc.compile.c++ bin/windows/x86/libtorrent_jni.o
gcc.link.dll bin/windows/x86/libjlibtorrent.dll.a
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/../../../../i686-w64-mingw32/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xf9d): undefined reference to `_imp__GetDeviceCaps@8'
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/../../../../i686-w64-mingw32/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xfcb): undefined reference to `_imp__CreateCompatibleBitmap@12'
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/../../../../i686-w64-mingw32/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xfed): undefined reference to `_imp__GetObjectA@12'
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/../../../../i686-w64-mingw32/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0x10e0): undefined reference to `_imp__GetDIBits@28'
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/../../../../i686-w64-mingw32/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0x1152): undefined reference to `_imp__DeleteObject@4'
collect2: error: ld returned 1 exit status

    "/home/rkfg/Development/toolchains/windows-x86/bin/i686-w64-mingw32-g++" -L"/opt/local/lib" -L"/usr/lib"  "-Wl,--out-implib,bin/windows/x86/libjlibtorrent.dll.a" -o "bin/windows/x86/libjlibtorrent.dll" -Wl,-h -Wl,libjlibtorrent.dll -shared -Wl,--start-group "bin/windows/x86/libtorrent_jni.o" "bin/windows/x86/libtorrent.a" "bin/windows/x86/libboost_random.a" "bin/windows/x86/libboost_chrono.a" "bin/windows/x86/libboost_system.a"  -Wl,-Bstatic -ladvapi32 -Wl,-Bdynamic -liphlpapi -lssl -lcrypto -lws2_32 -lwsock32 -Wl,--end-group -static 

...failed gcc.link.dll bin/windows/x86/libjlibtorrent.dll.a bin/windows/x86/libjlibtorrent.dll...
...removing bin/windows/x86/libjlibtorrent.dll.a
...failed updating 2 targets...
...updated 1 target...
/home/rkfg/Development/toolchains/windows-x86/bin/i686-w64-mingw32-strip: 'bin/windows/x86/libjlibtorrent.dll': No such file
mv: cannot stat ‘bin/windows/x86/libjlibtorrent.dll’: No such file or directory
```

I hacked a way around it by adding this to libtorrent:
```diff
diff --git a/Jamfile b/Jamfile
index e29f87d..15e7042 100644
--- a/Jamfile
+++ b/Jamfile
@@ -122,6 +122,7 @@ rule linking ( properties * )
                || <target-os>cygwin in $(properties)
        {
                result += <library>ws2_32
+                       <library>gdi32
                        <library>wsock32
                        <library>iphlpapi
                        <define>WIN32_LEAN_AND_MEAN
```
But I'm not sure it's the right way. But now I have a DLL on hands, that's already something. I'd like someone to follow my steps to build it from scratch and see if the process fails the same way.

**Comment by aldenml** [comment]
Good to know you reached this point. Well, I decided not to add gdi32 to libtorrent, it's not the right solution. OpenSSL made the mistake of using those functions at compile time, instead of asking at runtime. I removed the code (function body) in read_win.c and compiled again OpenSSL (it's trivial). Let me know if you need help with this.

**Comment by rkfg** [comment]
That's not rocket science:
```diff
diff --git a/crypto/rand/rand_win.c b/crypto/rand/rand_win.c
index 06670ae..b6364be 100644
--- a/crypto/rand/rand_win.c
+++ b/crypto/rand/rand_win.c
@@ -136,7 +136,6 @@
 # define INTEL_DEF_PROV L"Intel Hardware Cryptographic Service Provider"
 
 static void readtimer(void);
-static void readscreen(void);
 
 /*
  * It appears like CURSORINFO, PCURSORINFO and LPCURSORINFO are only defined
@@ -622,7 +621,6 @@ void RAND_screen(void)
 {                               /* function available for backward
                                  * compatibility */
     RAND_poll();
-    readscreen();
 }
 
 /* feed timing information to the PRNG */
@@ -680,73 +678,4 @@ static void readtimer(void)
  *   Sample Application Files which are modified.
  */
 
-static void readscreen(void)
-{
-# if !defined(OPENSSL_SYS_WINCE) && !defined(OPENSSL_SYS_WIN32_CYGWIN)
-    HDC hScrDC;                 /* screen DC */
-    HBITMAP hBitmap;            /* handle for our bitmap */
-    BITMAP bm;                  /* bitmap properties */
-    unsigned int size;          /* size of bitmap */
-    char *bmbits;               /* contents of bitmap */
-    int w;                      /* screen width */
-    int h;                      /* screen height */
-    int y;                      /* y-coordinate of screen lines to grab */
-    int n = 16;                 /* number of screen lines to grab at a time */
-    BITMAPINFOHEADER bi;        /* info about the bitmap */
-
-    if (check_winnt() && OPENSSL_isservice() > 0)
-        return;
-
-    /* Get a reference to the screen DC */
-    hScrDC = GetDC(NULL);
-
-    /* Get screen resolution */
-    w = GetDeviceCaps(hScrDC, HORZRES);
-    h = GetDeviceCaps(hScrDC, VERTRES);
-
-    /* Create a bitmap compatible with the screen DC */
-    hBitmap = CreateCompatibleBitmap(hScrDC, w, n);
-
-    /* Get bitmap properties */
-    GetObject(hBitmap, sizeof(BITMAP), (LPSTR) & bm);
-    size = (unsigned int)bm.bmWidthBytes * bm.bmHeight * bm.bmPlanes;
-
-    bi.biSize = sizeof(BITMAPINFOHEADER);
-    bi.biWidth = bm.bmWidth;
-    bi.biHeight = bm.bmHeight;
-    bi.biPlanes = bm.bmPlanes;
-    bi.biBitCount = bm.bmBitsPixel;
-    bi.biCompression = BI_RGB;
-    bi.biSizeImage = 0;
-    bi.biXPelsPerMeter = 0;
-    bi.biYPelsPerMeter = 0;
-    bi.biClrUsed = 0;
-    bi.biClrImportant = 0;
-
-    bmbits = OPENSSL_malloc(size);
-    if (bmbits) {
-        /* Now go through the whole screen, repeatedly grabbing n lines */
-        for (y = 0; y < h - n; y += n) {
-            unsigned char md[MD_DIGEST_LENGTH];
-
-            /* Copy the bits of the current line range into the buffer */
-            GetDIBits(hScrDC, hBitmap, y, n,
-                      bmbits, (BITMAPINFO *) & bi, DIB_RGB_COLORS);
-
-            /* Get the hash of the bitmap */
-            MD(bmbits, size, md);
-
-            /* Seed the random generator with the hash value */
-            RAND_add(md, MD_DIGEST_LENGTH, 0);
-        }
-
-        OPENSSL_free(bmbits);
-    }
-
-    /* Clean up */
-    DeleteObject(hBitmap);
-    ReleaseDC(NULL, hScrDC);
-# endif                         /* !OPENSSL_SYS_WINCE */
-}
-
 #endif
```
Yeah, it was very unexpected to find a GDI dependency in OpenSSL. Despite I hate to change such critical code as OpenSSL seems to be, this one looks safe enough. And it's arguably less hacky than changing that Jamfile in libtorrent... but after removing this function it compiled fine without gdi32. Thank you for your time and assistance, @aldenml! I hope all of this wasn't in vain and a guide will appear one days so others won't spend their time on this.

**Comment by gubatron** [comment]
ha, they'd use the screen as a source of entropy (I think that's how crypto guys cal it)

**Comment by rkfg** [comment]
Exactly, and that function is marked as deprecated. Too bad there's no way to correctly turn it off, it's only skipped on WinCE and cygwin.

**Comment by gubatron** [comment]
the proper way should be with a compilation flag IMO, something like `-DWITH_GDI` then use preprocessor `#ifdef WITH_GDI` to include the code, or the other way around, but I rather not have that dependency by default, it'd be up to OpenSSL upstream. But that'd be a nice patch to have, one less dependency that's not even cross OS compatible, and now that you mentioned it's deprecated, it should def. be optional.

**Comment by rkfg** [comment]
Deprecated doesn't mean it's useless, the comment says it's here for backward compatibility. So if it's excluded, some older code that relies on it may break. Legacy may be a tough thing.

**Comment by gubatron** [comment]
true true, so then it should be `-DWITHOUT_GDI`

```
#ifndef WITHOUT_GDI
static void readscreen(void) {
...
```

**Comment by aldenml** [comment]
Closing this. @rkfg if you need something else, feel free to reopen it.
