### ISSUE TITLE
How do I delete a tracker from an existing torrent file? Or clear all the current trackers?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#75]
I thought that this code would work, but it doesn't seem to clear the trackers that are currently there:

```java
public static void updateTrackerForTorrent(File torrentFile) {

		TorrentInfo ti = new TorrentInfo(torrentFile);

		create_torrent t = new create_torrent(ti.getSwig());

		// Changing the tracker
		for (URI announce : DataSources.ANNOUNCE_LIST()) {
			t.add_tracker(announce.toASCIIString());
		}
		

		// Get the bencode and write the file
		Entry entry =  new Entry(t.generate());

		Map<String, Entry> entryMap = entry.dictionary();
		Entry entryFromUpdatedMap = Entry.fromMap(entryMap);
		final byte[] bencode = entryFromUpdatedMap.bencode();

		FileOutputStream fos;

		try {
			fos = new FileOutputStream(torrentFile);

			BufferedOutputStream bos = new BufferedOutputStream(fos);
			bos.write(bencode);
			bos.flush();
			bos.close();

			log.info("Trackers updated for torrent: " + torrentFile.getAbsolutePath());
		} catch (IOException e) {
			e.printStackTrace();
		}

	}
```

**Comment by tchoulihan** [comment]
I've also found `torrentHandle.replaceTrackers(....)` but it doesn't seem to actual change the underlying `TorrentInfo` in order to be able to save the file.

**Comment by aldenml** [comment]
For what I can see in the `create_torrent`, this class receive a `torrent_info` to do a bootstrapping in data, but with limited functionality like for example "remove existing torrents". I hope this new code could help you:

https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/test/java/com/frostwire/jlibtorrent/ChangeTrackersTest.java#L21

Note: remember the high level API `Entry` is for fancy and easy of use, but for real low level manipulation with less memory, use directly `entry`.

**Comment by tchoulihan** [comment]
Thanks for this, testing it out now.

**Comment by tchoulihan** [comment]
Okay, just tested this, and it works! Thanks so much for this. It might be useful to add a `torrent_info.remove_trackers`, instead of manipulating the `string_entry_map` like you're doing, but as long as we have the solution recorded here, then its no prob.

**Comment by tchoulihan** [comment]
Okay, testing now.

**Comment by tchoulihan** [comment]
Yep that `ti.getSwig().trackers().clear();`  works, a lot cleaner too.
