### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#78]
After many weeks without any problems / crashes I got this error:

 A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007fb0b5c75557, pid=26384, tid=140396933371648

 JRE version: Java(TM) SE Runtime Environment (7.0_80-b15) (build 1.7.0_80-b15)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libjlibtorrent.so+0x3fb557]  libtorrent::torrent_peer::address() const+0x17

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=128 (), si_addr=0x0000000000000000

Registers:
RAX=0x00007fb0b5574320, RBX=0x0000000023294d60, RCX=0x00007fb0b5574480, RDX=0x0000000000000000
RSP=0x00007fb0b55742c0, RBP=0x00007fb0b55743e0, RSI=0x55609795c0c364f2, RDI=0x00007fb0b5574320
R8 =0x000000001d1c59e0, R9 =0x00000000000005dc, R10=0x0000000023294eb0, R11=0x000000001b425ec0
R12=0x00000000000000bb, R13=0x0000000000000176, R14=0x000000001d1c59f8, R15=0x0000000023294f60
RIP=0x00007fb0b5c75557, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000000
  TRAPNO=0x000000000000000d

Top of Stack: (sp=0x00007fb0b55742c0)
0x00007fb0b55742c0:   00007fb0b5574320 00000000163d2558
0x00007fb0b55742d0:   00007fb0b5574310 060b0042897bee00
0x00007fb0b55742e0:   ffffffffffffffff 00007fb0b5c466c1
0x00007fb0b55742f0:   0000000023294eb0 00007fb0b5574480
0x00007fb0b5574300:   00007fb0b5574320 00007fb0b5574420
0x00007fb0b5574310:   00007fb0b5574488 00007fb0b5574328
0x00007fb0b5574320:   1f59f26200000000 0000000000000000
0x00007fb0b5574330:   0000000000000000 0000000000000000
0x00007fb0b5574340:   0000000000f0ffff 060b0042897bee00
0x00007fb0b5574350:   730cb6d671f5d73b 00007fb0b55748b0
0x00007fb0b5574360:   00007fb0b5574530 00007fb0b5574460
0x00007fb0b5574370:   000000000000c09b 00007fb0b5574480
0x00007fb0b5574380:   000000001d102e40 00007fb0b5d88b31
0x00007fb0b5574390:   0000000000000000 0000001e00000000
0x00007fb0b55743a0:   0000000000000004 000000001310bb30
0x00007fb0b55743b0:   0000000003e3f650 0000000000000005
0x00007fb0b55743c0:   0000000080000004 0000000000000013
0x00007fb0b55743d0:   6d6c60619bc00002 0000000000000000
0x00007fb0b55743e0:   000000001b425e38 000000001b425cc0
0x00007fb0b55743f0:   000000001b425ec0 000000001d1c59e0
0x00007fb0b5574400:   000000001e6db7a0 000000001e6db750
0x00007fb0b5574410:   000000001e6db950 000000001d1c5aa0
0x00007fb0b5574420:   00007fb0b55745b0 000000000000001e
0x00007fb0b5574430:   000000000000c09b 00007fb0b5ce8065
0x00007fb0b5574440:   0000000000000000 0000000000000000
0x00007fb0b5574450:   00007fb000000000 00007fb0b5631d48
0x00007fb0b5574460:   6d6c606100000000 0000000000000000
0x00007fb0b5574470:   0000000000000000 0000000000000000
0x00007fb0b5574480:   6d6c606100000000 0000000000000000
0x00007fb0b5574490:   0000000000000000 0000000000000000
0x00007fb0b55744a0:   0000000000000004 060b0042897bee00
0x00007fb0b55744b0:   6d6c60619bc00002 000000002157d610 

Instructions: (pc=0x00007fb0b5c75557)
0x00007fb0b5c75537:   2e 0f 1f 84 00 00 00 00 00 48 83 ec 28 48 89 f8
0x00007fb0b5c75547:   64 48 8b 14 25 28 00 00 00 48 89 54 24 18 31 d2
0x00007fb0b5c75557:   80 7e 1d 00 78 6b f6 46 1e 01 c7 07 00 00 00 00
0x00007fb0b5c75567:   75 37 8b 56 20 48 c7 47 08 00 00 00 00 48 c7 47 

Register to memory mapping:

RAX=0x00007fb0b5574320 is an unknown value
RBX=0x0000000023294d60 is an unknown value
RCX=0x00007fb0b5574480 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00007fb0b55742c0 is an unknown value
RBP=0x00007fb0b55743e0 is an unknown value
RSI=0x55609795c0c364f2 is an unknown value
RDI=0x00007fb0b5574320 is an unknown value
R8 =0x000000001d1c59e0 is an unknown value
R9 =0x00000000000005dc is an unknown value
R10=0x0000000023294eb0 is an unknown value
R11=0x000000001b425ec0 is an unknown value
R12=0x00000000000000bb is an unknown value
R13=0x0000000000000176 is an unknown value
R14=0x000000001d1c59f8 is an unknown value
R15=0x0000000023294f60 is an unknown value

Stack: [0x00007fb0b4d75000,0x00007fb0b5576000],  sp=0x00007fb0b55742c0,  free space=8188k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjlibtorrent.so+0x3fb557]  libtorrent::torrent_peer::address() const+0x17

**Comment by aldenml** [comment]
I will close this, but feel free to re-open if the problem persist or you have an example to reproduce it. In any case, the error is coming from the internal libtorrent and I checked the source code and I can't detect any reasonable situation that could trigger this crash.
