### ISSUE TITLE
have no error or exception auto exit

### ISSUE THREAD

**Issue by xwlcn** [frostwire/frostwire-jlibtorrent#80]
example：
`String uri="magnet:?xt=urn:btih:a8955186cd9509af906dcb293795733e62efed48";
		  File saveDir=new File("C:\\Users\\Administrator\\Desktopfrostwire_installer.torrent");
		  Session s=new Session();
		  Downloader d=new Downloader(s);
		  System.out.println("Fetching the magnet uri, please wait...");
		  byte[] data=d.fetchMagnet(uri,30000);
		  if (data != null) {
		    System.out.println(Entry.bdecode(data));
		    //Utils.writeByteArrayToFile(saveDir,data);
		    System.out.println("Torrent data saved to: " + saveDir);
		  }
		 else {
		    System.out.println("Failed to retrieve the magnet");
		  }`

after call byte[] data=d.fetchMagnet(uri,30000);
 there is nothing print out:'System.out.println("Torrent data saved to: " + saveDir);' or 'System.out.println("Failed to retrieve the magnet");'
with the program auto exit.

**Comment by aldenml** [comment]
@xwlcn what do you mean with `program auto exit`? What version of jlibtorrent are you using?

**Comment by aldenml** [comment]
Closing this for lack of info.
