### ISSUE TITLE
Boost error

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#81]
I think now I had a Boost exception which crashed the application :(

I have only this in the logs:

terminate called after throwing an instance of 'boost::bad_weak_ptr'
  what():  tr1::bad_weak_ptr

I think it happened while doing this call:  session.getSwig().get_torrents()

**Comment by aldenml** [comment]
Hi @WhiteTrashLord, I was not able to replicate the issue (see https://github.com/frostwire/frostwire-jlibtorrent/blob/ed0e60a37c946358c3239e664ad0a9d5d7461179/src/test/java/com/frostwire/jlibtorrent/SessionGetTorrentsTest.java#L49). This is called 20 times. I will close this, but feel free to reopen if you can provide more information or a case we can replicate.

Thanks for the report.

**Comment by WhiteTrashLord** [comment]
I have several random crashes these days :(

Now it got this:

java: malloc.c:2842: mremap_chunk: Assertion `((size + offset) & (_rtld_global_ro._dl_pagesize - 1)) == 0' failed.

It's possible that my RAM is defective?

**Comment by aldenml** [comment]
Defective RAM, or any faulty component in the bus, or heat could give you random crashes like this, but you should be able to observe it at any moment. I suggest the following test: Stop any process using jlibtorrent and start a process that demand high CPU/memory usage, like for example, recode a long video to h264.

Any recent upgrade in the system? OS version? JRE version? jlibtorrent version?
