### ISSUE TITLE
Vulnerabilities - OpenSSL

### ISSUE THREAD

**Issue by diaconuliviu85** [frostwire/frostwire-jlibtorrent#82]
Hello
thank you for the work is a good bookstore .
Unfortunately I have a problem with the latest version of OpenSSL version 2015 is now rejected by Google. Please upgrade to a new version of OpenSSL .

compile 'com.frostwire:jlibtorrent:1.1.0.22' is OpenSSL 1.0.2d 9 Jul 2015

**Comment by aldenml** [comment]
@diaconuliviu85 , I will close this issue and follow up in this one https://github.com/frostwire/frostwire-jlibtorrent/issues/83#issuecomment-204784438
