### ISSUE TITLE
Android:Specific saveDir of TorrentHandle is effect in arm but not in x86. 

### ISSUE THREAD

**Issue by cocia** [frostwire/frostwire-jlibtorrent#84]
Latest version:
    compile 'com.frostwire:jlibtorrent:1.1.0.20'
    compile 'com.frostwire:jlibtorrent-android-arm:1.1.0.20'
    compile 'com.frostwire:jlibtorrent-android-x86:1.1.0.20'

I want to make torrent file with local data file and run as seed for others.

data file is at: "/sdcard/test/a.mp4"

code looks like these:
Maket torrent object: ti
File saveDir = new File("/sdcard/test");
session.asyncAddTorrent(ti, saveDir, priorities, resumeFile);

ti.getSavePath() returns value:
in arm version(Android 5.1.1):
 "/sdcard/test"

in x86 version(Genymotion x86 VM Android 5.1.0):
 "/sdcard/test/TorrentsData"
(this is default torrent data download location)

So arm version works fine but x86 version doesn't work.

Did I miss something in my code?
Thanks.

**Comment by aldenml** [comment]
What is the error? can you post the `adb logcat`?

**Comment by gubatron** [comment]
Please include the code of how you make the 'ti' object.

**Comment by cocia** [comment]
@aldenml @gubatron 
Add more: /sdcard/test/TorrentsData is my default torrent data download location.
There are not too much logcat.

This is torrent making utility which is from com.frostwire.jlibtorrent.demo. a little bit change to support Rx observable:
[BTMakeTorrent.java.txt](https://github.com/frostwire/frostwire-jlibtorrent/files/211024/BTMakeTorrent.java.txt)

This is my code to make and download/seed new torrent file and data.
```java
String mediaFilePath = "/sdcard/test/a.mp4";
String torrentFilePath = "/sdcard/test/a.torrent";

BTMakeTorrent.makeTorrentInfo(mediaFilePath)
                        .subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Action1<TorrentInfo>() {
                    @Override
                    public void call(TorrentInfo torrentInfo) {
                        try {
                            FileOutputStream fos = new FileOutputStream(torrentFilePath);
                            byte[] data = torrentInfo.bencode();
                            fos.write(data, 0, data.length);
                            fos.close();
                            Timber.d("Create torrent file %s torrent for %s", torrentFilePath, mediaFilePath);

                            File mediaFile = new File(mediaFilePath);
                            File saveFileFolder = mediaFile.getParentFile();
                            Timber.d("Save file dir:AbsolutePath:%s, CanonicalPath:%s", saveFileFolder.getAbsolutePath(), saveFileFolder.getCanonicalPath());

                            TransferManager.instance().clearComplete();
                            BittorrentDownload bittorrentDownload = TransferManager.instance().getBittorrentDownloadByHash(torrentInfo.getInfoHash().toHex());
                            if(bittorrentDownload != null){
                                bittorrentDownload.cancel();
                                Timber.d("Cancelled existing torrent %s", torrentInfo.getInfoHash().toHex());
                            }
                             //add callback to support async.
                            TransferManager.instance().downloadTorrent(torrentInfo, saveFileFolder.getAbsoluteFile(), new CallbackTask<BittorrentDownload>() {
                                @Override
                                public void onCompleted(BittorrentDownload result) {
                                    if (result instanceof UIBittorrentDownload) {
                                        handleStreamTorrent((UIBittorrentDownload) result);
                                        if (mTorrent == null) {
                                            Log.d("Torrent", "onStreamError: torrentInfo is null");
                                            mButton.setText("Start stream");
                                            return;
                                        }
                                        //torrentInfo.addHttpSeed("http://x.x.x.x:8080/a");
                                        mTorrent.setStreamListener(MkTorrentMainActivity.this);
                                        mTorrent.startDownload();
                                        Timber.d("Started torrent download");
                                    }
                                }

                                @Override
                                public void onError(Throwable error) {
                                    Log.e("Torrent", "onStreamError:" + error.getMessage(), error);
                                    mButton.setText("Start stream");
                                }
                            });
                        }catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                    }
                });
```

**Comment by gubatron** [comment]
you should grep your source code directory for "TorrentsData"
try:

`grep "TorrentsData" * -R`

and see what you can find. That extra path is not in our source code.

**Comment by aldenml** [comment]
I think the effective way to test this is with advanced android unit tests. I'm working on it, but it could take a while

**Comment by aldenml** [comment]
@cocia This is to much code to translate to a test, it could be in your logic. Could you post a minimal code that replicates the issue or at least post the `adb logcat` of the run on both architectures (I see you are logging the paths).

**Comment by gubatron** [comment]
I think we can write a simple test that does this @aldenml , if I understand correctly:

1. Set a default save location. (I suppose that can be done in the settings pack)
2. Create a `File saveDir` object with a custom save location.
3. Add a torrent using the `session.asyncAddTorrent(ti, saveDir, priorities, resumeFile);`
4. `assertNotEquals(ti.getSavePath(), defaultSaveDir);`

However, looking at the current jlibtorrent API, the method `session.asyncAddTorrent(...)` no longer has the signature used by @cocia, he's now supposed to use `session.asyncAddTorrent(AddTorrentParams params)` with a `AddTorrentParams` object.

So @cocia, your code should be more like:

```
AddTorrentParams addTorrentParams = new AddTorrentParams();
addTorrentParams.torrentInfo(ti);
addTorrentParams.savePath(new File("/sdcard/test"));
addTorrentParams.filePriorities(priorities);
addTorrentParams.resumeData(resumeData);
session.asyncAddTorrent(addTorrentParams);
```

Then your `ti` object, should not have a `getSavePath()` method, like you ask. You need to ask later to the session for the corresponding `TorrentHandle` object, `session.findTorrent(Sha1Hash sha1)`, the `TorrentHandle` object can be asked for the `torrentHandle.getTorrentInfo()` and also `torrentHandle.getSavePath()` which should be the one you have set for it on the `AddTorrentParams` object.

**Comment by aldenml** [comment]
The reason I think is in his logic is that there is no default save location.

**Comment by cocia** [comment]
Thank @gubatron and @aldenml . I will try this by your kind suggestion and feedback later.

**Comment by aldenml** [comment]
Any new info here?

**Comment by cocia** [comment]
I tested it on other devices, looks OK. So only this one vm has problem. Let me close it first. Thank you.
