### ISSUE TITLE
start_upnp()

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#86]
Solved

**Comment by aldenml** [comment]
UPnP is enable by default when you create a session (the same way libtorrent behave). We didn't expose a toggle UPnP in jlibtorrent, but you can code it the same way it's for DHT, see https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/DHT.java#L206

**Comment by WhiteTrashLord** [comment]
Thanks for the fast answer. Here you can read that it's off by default:

http://www.rasterbar.com/products/libtorrent/manual.html#start-upnp-stop-upnp

Are you sure that it's really turned on? :D

**Comment by aldenml** [comment]
Thank you for the info, it is always good to double check the default values. The documentation you are pointing out is for a very old version 0.16.18.

Here it is the new documentationhttp://www.rasterbar.com/products/libtorrent/reference-Settings.html#enable_upnp, it is enable by default :)

Do you have any problems with it?

**Comment by WhiteTrashLord** [comment]
I am trying to find out why my Libtorrent doesn't upload very much. Maybe the upload is completely stopped once a torrent is finished (not very sure about that).

Might it help to turn off Auto Managed?

**Comment by aldenml** [comment]
No idea, is this torrent popular? are a lot of peers in the swarm?

**Comment by WhiteTrashLord** [comment]
Yes, more than enough peers. Is there an option to check if Libtorrent can listen on the ports successfully via UPnP?

**Comment by aldenml** [comment]
I think that is the idea, if there are a lot of peers, eventually you get less and less request of pieces.

Put the corresponding mask and print: `ListenSucceededAlert`, `ListenFailedAlert` and `Portmap*` alerts

**Comment by WhiteTrashLord** [comment]
How to increase active_limit? It seems to be very important.

**Comment by aldenml** [comment]
```
SettingsPack sp = new SettingsPack();
pack.setInteger(settings_pack.int_types.active_limit.swigValue(), <value>);
session.applySettings(sp);
```

**Comment by WhiteTrashLord** [comment]
Thanks. Maybe you should make a method like setActiveLimit(int limit).

**Comment by gubatron** [comment]
@WhiteTrashLord here are the settings I use in libtorrent to enable super seeding

```
max_upload_speed -1 
auto_managed 0
max_active_downloading -1
max_active_limit -1
max_active_seeding -1 
max_connections_global 200 
max_connections_per_second 20 
max_connections_per_torrent -1 
max_download_speed -1 
max_download_speed_per_torrent -1 
max_half_open_connections 50 
max_upload_slots_global 100  
max_upload_slots_per_torrent -1
seed_time_limit -1
seed_time_ratio_limit -1
share_ratio_limit -1
stop_seed_ratio -1
```

**Comment by WhiteTrashLord** [comment]
@gubatron 
Thanks but I think your settings are not original Libtorrent settings. Do you use Deluge?

**Comment by gubatron** [comment]
yes those are my deluge server settings
