### ISSUE TITLE
Slow decoding in TorrentInfo if the file is not a torrent

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#88]
Hello. When creating applications for Android, I didn't do check on the correctness of the torrent file and immediately sent a link to it in TorrentInfo. But I noticed one unpleasant feature: if you accidentally decode a large file (> 10 MB) this operation is very long. I could run the decoding in AsyncTask, but it complicates the application and doesn't solve the problem with TorentInfo. Maybe there are other options for the rapid determination of the correctness of the torrent file? If possible, it would be useful to add this to TorrentInfo.

**Comment by aldenml** [comment]
What version of jlibtorrent are you using? Please, provide the way you are constructing the TorrentInfo.

**Comment by proninyaroslav** [comment]
@aldenml
Jlibtorrent 1.1.0.24 and jlibtorrent-android 1.1.0.9. 
Example of use:

TorrentInfo info = new TorrentInfo(pathToTorrent); /* It's a slow block code */

**Comment by aldenml** [comment]
Did you close this by mistake?

**Comment by aldenml** [comment]
in android, you should use 1.1.0.24 too

**Comment by proninyaroslav** [comment]
@aldenml
Jlibtorrent 1.1.0.24 and jlibtorrent-android 1.1.0.9.
Example of use:

TorrentInfo info = new TorrentInfo(pathToTorrent); /* It's a slow block code */
/* Example */
info.getName() /* It does not affect the rate of */

P.S: I'm sorry, I accidentally closed due to uncomfortable typing on smartphone.

**Comment by aldenml** [comment]
Ok, let me look at it. It's not clear to me this is something we can improve, since this is a wrapper of the native libtorrent.

**Comment by proninyaroslav** [comment]
> in android, you should use 1.1.0.24 too

Ok, I'll check and write results.

**Comment by proninyaroslav** [comment]
> in android, you should use 1.1.0.24 too

No, this doesn't solve the problem.

**Comment by proninyaroslav** [comment]
I think that the code is a bottleneck in TorrentInfo:
```
private static torrent_info bdecode0(File file) {
...
            byte[] data = Files.bytes(file);
...
}
```
If a large file, the read speed is reduced, thereby reducing the overall speed.

**Comment by aldenml** [comment]
Well, this is a hard one. If you are in android, loading 10MB in a `byte[]` will put a lot of pressure to the application, to the point that the OS could kill the app. With the current libtorrent API, I don't see any solution to this problem, `AsyncTask` will not help you here.

I think merkle torrents are the solution to this general problem of "very" big torrents. My only suggestion is check the file size before loading it.

**Comment by proninyaroslav** [comment]
AsyncTask slightly improves UI rendering while decoding, since even when decoding correct torrent file can feel the delay.

**Comment by aldenml** [comment]
Sure, what I meant is that the `AsyncTask`, while an improvement in the UI, would not prevent a random kill of the process or a general slowdown in any other part of your program.

**Comment by aldenml** [comment]
Ok, in master you can now memory map the file and try to load it, this solve the problem of slow detection and memory pressure if the file is big and it's not a torrent file. See https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/test/java/com/frostwire/jlibtorrent/demo/ReadTorrent.java#L27

**Comment by proninyaroslav** [comment]
@aldenml 
Good job!

**Comment by gubatron** [comment]
wow this is pretty dope:
```
FileChannel fc = new RandomAccessFile(args[0], "r").getChannel();
MappedByteBuffer buffer = fc.map(FileChannel.MapMode.READ_ONLY, 0, fc.size());
TorrentInfo ti2 = new TorrentInfo(buffer);
```

**Comment by gubatron** [comment]
where is the native code of?
```
long ptr = libtorrent_jni.directBufferAddress(buffer);
long size = libtorrent_jni.directBufferCapacity(buffer);
```
I want to see into what the `MappedByteBuffer` is converted to, to get to libtorrent land.

**Comment by aldenml** [comment]
https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/libtorrent.i#L89

**Comment by aldenml** [comment]
after that, https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/libtorrent.i#L1006

**Comment by gubatron** [comment]
`jenv->GetDirectBufferAddress(jbuf)` is that provided by jvm.dll or is yours?

**Comment by gubatron** [comment]
(just annoyingly curious)

**Comment by aldenml** [comment]
jvm, I didn't know it either :) I didn't want to use `com.sun.Unsafe`
