### ISSUE TITLE
Don't call blockFinished() alert if downloading files by priority

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#89]
Hello. Problem with the PartialDownload and PartialDownload2 demos: don't show progress. The demos run on Linux. Full log:

_PartialDownload.java_
```
Using libtorrent version: 1.1.0.0
Torrent finished
Process finished with exit code 0
```
_PartialDownload2.java_
```
Using libtorrent version: 1.1.0.0
About to download first file.
State change: CHECKING_RESUME_DATA -> CHECKING_FILES
Torrent finished
About to download second file.
State change: CHECKING_FILES -> DOWNLOADING
Torrent finished
State change: DOWNLOADING -> FINISHED
Torrent finished
Torrent finished

Process finished with exit code 0
```

In the DownloadTorrent demo similar problems aren't noticed.

**Comment by aldenml** [comment]
Hi @proninyaroslav, are the torrents already downloaded? Can you verify that no torrent data is already there before running each one of these demos?

**Comment by proninyaroslav** [comment]
@aldenml 
No. This occurs at the first download and also after the full deleting of the data.

**Comment by proninyaroslav** [comment]
I replaced CountDownLatch on System.in.read () and obtained the following result:
```
Using libtorrent version: 1.1.0.0
Torrent finishedProgress: 100
```
The results are displayed after finishing the torrent.

**Comment by proninyaroslav** [comment]
Another observation: if we remove download priority in the demo (as in DownloadTorrent), a progress is displayed normally.

**Comment by aldenml** [comment]
Thanks for the information, let me take a look at it.

**Comment by proninyaroslav** [comment]
A small clarification: blockFinished() is called once at the same time as the torrentFinished() alert.

**Comment by proninyaroslav** [comment]
I wrote a test code for check, that returns `getProgress()`. 
```
int p;
do {
    p = (int) (th.getStatus().getProgress() * 100);
    System.out.println("Progress: " + p);
    Thread.sleep(10);
} while (p != 100);

System.out.println("Finish");
```
Normal result (download all files without priority):
```
Progress: 1
...
Progress: 8
...
Progress: 19
...
Progress: 76
...
Progress: 100
Finish
```

Result for downloading by priority:
```
Progress: 0
...
Many zeros
...
Progress: 100
Finish
```
It turns out that throughout downloading `getProgress()` produces 0 and does not cause `blockFinished()` alert. When called `torrentFinished()`, `getProgress()` returns 100 and sharply generated `blockFinished()`.

**Comment by aldenml** [comment]
`getStatus()` is cached, it's a costly operation (still pending deep review of this issue)

**Comment by proninyaroslav** [comment]
In version 1.1.0.30 the problem don't discovered. Thank you so much.
