### ISSUE TITLE
Add Session::prioritize_dht(torrent) support.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-jlibtorrent#90]
from `session_impl.hpp` on libtorrent
```

			// this is called for torrents when they are started
			// it will prioritize them for announcing to
			// the DHT, to get the initial peers quickly
			void prioritize_dht(boost::weak_ptr<torrent> t) override;
```

I believe this function could be useful to the seeding process when we seed single files from My Files.

*We should also send a patch
Nonetheless, arvid left a TODO on the implementation code in `session_impl.cpp` that I think we should provide. 

He imagines a version of this function that allows you to prioritize a list of torrents to be announced on the DHT and it's because reusing the current function to prioritize a list of torrents to announce would be very inneficient.

Currently he puts the torrent to be prioritized at the front of a queue of torrents to announce on the DHT, and then he delays the next call to check who's next to be announced.

Perhaps it'd be simpler to:
 - write down time left before next dht announce
 - Add a maximum delay to the next `dht_announce` call.
 - write down current time 
 - iterate through the list of torrents given and announce each
 - add them to the dht announce list if they're not there already, towards the end.
 - check time since last timestamp, and substract from time left before dht announce
 - if time > 0 set time as delay until next call, else, set delay 0 so it fires. 

I can see that can be of use in the event of seeding multiple files.

By looking at the current code to

**Comment by aldenml** [comment]
This function is internal and not exported. If we need some logic from libtorrent we should create an issue there.

I'm not sure we have a problem with the `announce` part in the peer creating the torrent, and the `"get the initial peers quickly"` is in the peer downloaders side.
