### ISSUE TITLE
Async work TorrentPausedAlert and TorrentStatus.isPaused()

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#91]
Hello. To pause the torrent I'm using `TorrentHandle.pause()`. But I have noticed one unpleasant feature of the `TorrentStatus.isPaused()`: it doesn't returns `true`, when the `TorrentPausedAlert` (in the` torrentPaused()`) is triggered; `isPaused()` returns `true` in about 100-500 ms after the alert triggering. To update the status in the UI of my application, I have to make an artificial delay of 100 ms, that the `isPaused` returns a valid result.

**Comment by aldenml** [comment]
You can call status with force: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/TorrentHandle.java#L185

**Comment by proninyaroslav** [comment]
Many thanks.

**Comment by gubatron** [comment]
java question: what happens to `th.lastStatus` if `th.stats(true)` is called from multiple threads at the same time? (I know it'd probably wouldn't have a bad effect in this case, but can the thread who asked for this object first lose the reference? or he'll just keep working with that old reference, or do the references get updated across all threads? (I think I need to write a test)

**Comment by aldenml** [comment]
threads will keep working with the old reference

**Comment by gubatron** [comment]
thanks
