### ISSUE TITLE
How to store data to every single file block by block 

### ISSUE THREAD

**Issue by cocia** [frostwire/frostwire-jlibtorrent#98]
By default, we specific a local file as torrent downloading destination. If that size of file is 1GB, the local file will be 1GB also even there only downloaded 10MB of actual data. 

I want to improve the use ratio of storage  in android devices. So I think can jlibtorrent support such feature:
How to store data to every single file block by block. Or somethings similar.

I have seen the interface "StoragePlugin", but it doesn't like such a plugin.

**Comment by gubatron** [comment]
this is because you're using **full allocation**

Read this
http://www.libtorrent.org/manual-ref.html#storage-allocation

**Comment by gubatron** [comment]
https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/AddTorrentParams.java#L219
