### ISSUE TITLE
Save path of added torrent with resume data

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#99]
I add my torrents with the method Session.addTorrent. I have the problem that the save path in the resume file is used and not the save path in the parameter.
So somehow the flag flag_use_resume_save_path must be enabled ( should be disabled by default according to the Libtorrent documentation ).
In your code I cannot find anything which enables this flag. Is this a Jlibtorrent or Libtorrent problem? I am a bit confused.

**Comment by aldenml** [comment]
It's a jlibtorrent problem, it is enable if the resume file is passed (https://github.com/frostwire/frostwire-jlibtorrent/blob/libtorrent-RC_1_1/src/main/java/com/frostwire/jlibtorrent/Session.java#L776). I will add another method to allow for your case.

As a note, in master I'm working in removing all these methods from Session and making it more close to the libtorrent one. I will put all this "user" logic in another class.

**Comment by aldenml** [comment]
See https://github.com/frostwire/frostwire-jlibtorrent/commit/d16ec5e21b7260dd5a61611e681ecc124fc8c515

I will ping here when the new stable version is out

**Comment by aldenml** [comment]
1.1.0.36 is out in maven
